/* Generated by End Language Compiler (endc) — Hyper-Optimized Native Output */
#define BUILDING_END_DLL 1
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
    #include <immintrin.h>
#elif defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif

/* End Hardware Watchdog & CPU Throttling Safety Hooks */
#if defined(_WIN32)
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    #define END_CPU_YIELD() SwitchToThread()
    #define END_CPU_RELAX() YieldProcessor()
    #define END_CPU_SLEEP(ms) Sleep(ms)
#else
    #include <sched.h>
    #include <unistd.h>
    #include <time.h>
    #define END_CPU_YIELD() sched_yield()
    #define END_CPU_RELAX() __builtin_ia32_pause()
    #define END_CPU_SLEEP(ms) usleep((ms) * 1000)
#endif

static inline void cpu_yield(void) { END_CPU_YIELD(); }
static inline void cpu_relax(void) { END_CPU_RELAX(); }
static inline void cpu_sleep_ms(int32_t ms) { END_CPU_SLEEP(ms); }
static inline uint64_t high_res_time_ns(void) {
#if defined(_WIN32)
    LARGE_INTEGER count, freq;
    QueryPerformanceCounter(&count);
    QueryPerformanceFrequency(&freq);
    return (uint64_t)((count.QuadPart * 1000000000ULL) / freq.QuadPart);
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)(ts.tv_sec * 1000000000ULL + ts.tv_nsec);
#endif
}

/* End Cross-Platform Export API Macro */
#if defined(_WIN32) || defined(__CYGWIN__)
    #define END_API __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
    #define END_API __attribute__((visibility("default")))
#else
    #define END_API
#endif

/* End Generic Print & Math Prelude Helpers (Zero-Import Available) */
static inline void _end_print_str(const char* s) { printf("%s\n", s); }
static inline void _end_print_int(long long n) { printf("%lld\n", n); }
static inline void _end_print_float(double f) { printf("%f\n", f); }
static inline void _end_print_bool(bool b) { printf("%s\n", b ? "true" : "false"); }
#define end_println(X) _Generic((X), \
    bool: _end_print_bool, \
    int: _end_print_int, \
    long: _end_print_int, \
    long long: _end_print_int, \
    unsigned int: _end_print_int, \
    unsigned long long: _end_print_int, \
    float: _end_print_float, \
    double: _end_print_float, \
    char*: _end_print_str, \
    const char*: _end_print_str)(X)

/* End Zero-Cost Memory Primitives (64-byte Cache-Line Aligned) */
typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;
typedef struct { char* buffer; size_t capacity; size_t offset; bool is_heap; } EndArena;
#if defined(_MSC_VER)
    static __declspec(thread) char _end_tls_scratchpad[4 * 1024 * 1024];
    static __declspec(thread) size_t _end_tls_offset = 0;
#else
    static __thread char _end_tls_scratchpad[4 * 1024 * 1024];
    static __thread size_t _end_tls_offset = 0;
#endif

static inline EndArena* end_arena_create(size_t cap) {
    if (_end_tls_offset + sizeof(EndArena) + cap <= sizeof(_end_tls_scratchpad)) {
        EndArena* a = (EndArena*)(_end_tls_scratchpad + _end_tls_offset);
        _end_tls_offset += (sizeof(EndArena) + 63) & ~63;
        a->buffer = _end_tls_scratchpad + _end_tls_offset;
        _end_tls_offset += (cap + 63) & ~63;
        a->capacity = cap;
        a->offset = 0;
        a->is_heap = false;
        return a;
    }
    EndArena* a = (EndArena*)malloc(sizeof(EndArena));
    a->buffer = (char*)malloc(cap);
    a->capacity = cap;
    a->offset = 0;
    a->is_heap = true;
    return a;
}
static inline void* end_arena_alloc(EndArena* a, size_t size) {
    size_t aligned = (size + 63) & ~63;
    if (a->offset + aligned > a->capacity) return NULL;
    void* ptr = (void*)(a->buffer + a->offset);
    a->offset += aligned;
    return ptr;
}
static inline void end_arena_destroy(EndArena* a) {
    if (!a) return;
    if (a->is_heap) { free(a->buffer); free(a); }
    else { _end_tls_offset = 0; }
}

/* End Native Desktop Windowing Runtime */
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
typedef struct EndWindow {
    HWND hwnd;
    HDC hdc;
    int32_t width;
    int32_t height;
    bool is_open;
    BITMAPINFO bmi;
} EndWindow;
static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }
    return DefWindowProcA(hWnd, msg, wParam, lParam);
}
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {
    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));
    win->width = width;
    win->height = height;
    win->is_open = true;
    HINSTANCE hInstance = GetModuleHandle(NULL);
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(WNDCLASSEXA);
    wc.lpfnWndProc = EndWndProc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.lpszClassName = "EndNativeWindow";
    RegisterClassExA(&wc);
    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    win->bmi.bmiHeader.biWidth = width;
    win->bmi.bmiHeader.biHeight = -height;
    win->bmi.bmiHeader.biPlanes = 1;
    win->bmi.bmiHeader.biBitCount = 32;
    win->bmi.bmiHeader.biCompression = BI_RGB;
    win->hwnd = CreateWindowExA(0, "EndNativeWindow", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);
    win->hdc = GetDC(win->hwnd);
    ShowWindow(win->hwnd, SW_SHOW);
    UpdateWindow(win->hwnd);
    return win;
}
static inline bool window_poll(EndWindow* win) {
    if (!win) return false;
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        if (msg.message == WM_QUIT) { win->is_open = false; return false; }
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
    return win->is_open;
}
static inline void window_present(EndWindow* win, uint32_t* pixels) {
    if (!win || !win->is_open || !pixels) return;
    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);
}
static inline void window_sleep(int32_t ms) {
    Sleep(ms);
}
#else
typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }
static inline bool window_poll(EndWindow* win) { return false; }
static inline void window_present(EndWindow* win, uint32_t* pixels) {}
static inline void window_sleep(int32_t ms) {}
#endif

/* Hybrid 3-Tier Memory Model Runtime */
typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;
static inline void* end_rc_new(size_t size, const void* src) {
    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);
    h->ref_count = 1;
    if (src) memcpy(h->data, src, size);
    return (void*)h->data;
}
static inline void* end_rc_clone(void* ptr) {
    if (!ptr) return NULL;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count++;
    return ptr;
}
static inline void end_rc_drop(void* ptr) {
    if (!ptr) return;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count--;
    if (h->ref_count <= 0) free(h);
}
static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {
    if (!ptr || !target_arena) return ptr;
    void* new_ptr = end_arena_alloc(target_arena, size);
    if (new_ptr) memcpy(new_ptr, ptr, size);
    return new_ptr ? new_ptr : ptr;
}

/* End Lightweight Concurrency & Channel Runtime */
typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;
static inline EndChannel* channel_create(int32_t cap) {
    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));
    ch->buffer = (void**)malloc(sizeof(void*) * cap);
    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;
    return ch;
}
static inline void channel_send(EndChannel* ch, void* val) {
    if (ch->count < ch->capacity) {
        ch->buffer[ch->tail] = val;
        ch->tail = (ch->tail + 1) % ch->capacity;
        ch->count++;
    }
}
static inline void* channel_recv(EndChannel* ch) {
    if (ch->count == 0) return NULL;
    void* val = ch->buffer[ch->head];
        ch->head = (ch->head + 1) % ch->capacity;
        ch->count--;
    return val;
}

/* End High-Resolution Hardware Timer Runtime (std::time) */
#if defined(_WIN32)
static inline uint64_t end_time_now_nanos(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_micros(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_millis(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);
}
#else
#include <time.h>
static inline uint64_t end_time_now_nanos(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}
static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }
static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }
#endif


typedef struct AccountType AccountType;
typedef struct Account Account;
typedef struct JournalEntry JournalEntry;
typedef struct LedgerLine LedgerLine;
typedef struct Customer Customer;
typedef struct InvoiceItem InvoiceItem;
typedef struct Invoice Invoice;
typedef struct FinancialReport FinancialReport;
typedef struct Card Card;
typedef struct Text Text;

typedef enum {
    AccountType_Asset,
    AccountType_Liability,
    AccountType_Equity,
    AccountType_Revenue,
    AccountType_Expense,
} AccountType_Tag;

struct AccountType {
    AccountType_Tag tag;
};

struct Account {
    int64_t id;
    const char* code;
    const char* name;
    int64_t balance_cents;
    int64_t account_type_id;
};

struct JournalEntry {
    int64_t id;
    const char* reference_no;
    const char* description;
    int64_t total_debit_cents;
    int64_t total_credit_cents;
    bool is_posted;
};

struct LedgerLine {
    int64_t id;
    int64_t entry_id;
    int64_t account_id;
    int64_t debit_cents;
    int64_t credit_cents;
};

struct Customer {
    int64_t id;
    const char* name;
    const char* tax_id;
    int64_t credit_limit_cents;
    int64_t outstanding_balance_cents;
};

struct InvoiceItem {
    int64_t id;
    const char* product_name;
    int64_t quantity;
    int64_t unit_price_cents;
    int64_t total_cents;
};

struct Invoice {
    int64_t id;
    int64_t customer_id;
    const char* invoice_number;
    int64_t subtotal_cents;
    int64_t tax_cents;
    int64_t discount_cents;
    int64_t total_cents;
    bool is_paid;
};

struct FinancialReport {
    int64_t total_revenue_cents;
    int64_t total_expenses_cents;
    int64_t net_income_cents;
    int64_t total_assets_cents;
    int64_t total_liabilities_cents;
};

struct Card {
    const char* title;
    const char* subtitle;
    const char* button_action;
};

struct Text {
    const char* text;
    const char* color;
    const char* font_size;
    const char* font_weight;
};

static inline int64_t get_accounts(void);
static inline bool post_journal_entry(int64_t debit, int64_t credit);
static inline FinancialReport get_financial_summary(void);
static inline Card App(void);
static inline int32_t run_accounting_simulation(void);
int main(void);

static inline bool Account_is_solvent(Account* self);
static inline int64_t Account_deposit(Account* self, int64_t amount_cents);
static inline int64_t Invoice_calculate_final_amount(Invoice* self);
static inline bool Invoice_is_large_order(Invoice* self);
static inline int64_t FinancialReport_get_profit_margin_basis_points(FinancialReport* self);
static inline bool AccountingCore_validate_balance(int64_t total_debit, int64_t total_credit);
static inline int64_t AccountingCore_compute_tax(int64_t subtotal_cents);
static inline int64_t TaxEngine_compute_tax(int64_t subtotal_cents);
static inline Invoice InvoiceManager_create_invoice(int64_t customer_id, int64_t items_count, int64_t unit_price_cents, int64_t discount_pct);

#line 178 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int64_t get_accounts(void) {
    #line 179 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type cash_acc = (Account){ .id = 101, .code = "1010-CASH", .name = "Operating Cash Account", .balance_cents = 5920000, .account_type_id = 0 };
    #line 186 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return cash_acc.balance_cents;
}

#line 192 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline bool post_journal_entry(int64_t debit, int64_t credit) {
    #line 193 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return AccountingCore_validate_balance(debit, credit);
}

#line 199 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline FinancialReport get_financial_summary(void) {
    #line 200 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return (FinancialReport){ .total_revenue_cents = 950000, .total_expenses_cents = 120000, .net_income_cents = 830000, .total_assets_cents = 5920000, .total_liabilities_cents = 5920000 };
}

#line 227 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline Card App(void) {
    #line 228 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return (Card){ .title = "💼 EndLedger: Real-Time Double-Entry Financial Dashboard", .subtitle = "Net Income: $8,300.00 | Total Assets: $59,200.00 | Trial Balance: 100% Balanced", .button_action = "Post New Journal Entry" };
}

#line 239 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int32_t run_accounting_simulation(void) {
    #line 240 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("==================================================================");
    #line 241 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("💼 STARTING ENDLEDGER ENTERPRISE SIMULATION & INVARIANT AUDIT");
    #line 242 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("==================================================================");
    #line 245 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type initial_cash = 5000000;
    #line 246 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type cash = (Account){ .id = 1, .code = "1010-CASH", .name = "Operating Cash Reserve", .balance_cents = initial_cash, .account_type_id = 0 };
    #line 253 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("✔ [Step 1] Initial Cash Balance verified: $50,000.00");
    #line 256 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type inv = InvoiceManager_create_invoice(501, 10, 100000, 5);
    #line 257 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("✔ [Step 2] Customer Invoice Generated:");
    #line 258 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("   - Subtotal: $10000");
    #line 259 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("   - Discount (5%): $500");
    #line 260 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("   - Tax (9% VAT): $855");
    #line 261 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("   - Total Billed: $10355");
    #line 264 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type debit_ar = inv.total_cents;
    #line 265 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type credit_rev = (inv.subtotal_cents - inv.discount_cents);
    #line 266 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type credit_tax = inv.tax_cents;
    #line 267 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type total_credit = (credit_rev + credit_tax);
    #line 269 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type is_balanced = AccountingCore_validate_balance(debit_ar, total_credit);
    #line 270 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    if ((!is_balanced)) {
        #line 271 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
        end_println("❌ FATAL: Double-Entry Invariant Failed!");
        #line 272 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
        return 1;
    }
    #line 274 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("✔ [Step 3] Double-Entry Ledger Invariant Passed: Debits == Credits ($10,355.00)");
    #line 277 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type cash_after_collection = (cash.balance_cents + debit_ar);
    #line 278 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type server_expense = 120000;
    #line 279 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type final_cash = (cash_after_collection - server_expense);
    #line 281 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("✔ [Step 4] Reconciled Final Operating Cash: $59,155.00");
    #line 284 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type report = (FinancialReport){ .total_revenue_cents = credit_rev, .total_expenses_cents = server_expense, .net_income_cents = (credit_rev - server_expense), .total_assets_cents = final_cash, .total_liabilities_cents = final_cash };
    #line 292 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type profit_margin = FinancialReport_get_profit_margin_basis_points(&report);
    #line 293 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("✔ [Step 5] Net Income: $8300");
    #line 294 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("✔ [Step 6] Profit Margin: 87.36%");
    #line 296 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("==================================================================");
    #line 297 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("🎉 ENDLEDGER AUDIT PASSED 100% WITH ZERO FLOATING POINT DRIFT!");
    #line 298 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    end_println("==================================================================");
    #line 299 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return 0;
}

#line 302 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
int main(void) {
    #line 303 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return run_accounting_simulation();
    return 0;
}

#line 87 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline bool Account_is_solvent(Account* self) {
    #line 88 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return (self->balance_cents >= 0);
}

#line 92 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int64_t Account_deposit(Account* self, int64_t amount_cents) {
    #line 93 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return (self->balance_cents + amount_cents);
}

#line 99 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int64_t Invoice_calculate_final_amount(Invoice* self) {
    #line 100 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return ((self->subtotal_cents + self->tax_cents) - self->discount_cents);
}

#line 104 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline bool Invoice_is_large_order(Invoice* self) {
    #line 105 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return (self->subtotal_cents >= 500000);
}

#line 111 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int64_t FinancialReport_get_profit_margin_basis_points(FinancialReport* self) {
    #line 112 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    if ((self->total_revenue_cents == 0)) {
        #line 113 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
        return 0;
    }
    #line 115 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return ((self->net_income_cents * 10000) / self->total_revenue_cents);
}

#line 126 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline bool AccountingCore_validate_balance(int64_t total_debit, int64_t total_credit) {
    #line 127 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return (total_debit == total_credit);
}

#line 131 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int64_t AccountingCore_compute_tax(int64_t subtotal_cents) {
    #line 132 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return ((subtotal_cents * 9) / 100);
}

#line 139 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int64_t TaxEngine_compute_tax(int64_t subtotal_cents) {
    #line 140 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    if ((subtotal_cents > 1000000)) {
        #line 142 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
        return ((subtotal_cents * 15) / 100);
    }
    #line 145 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return ((subtotal_cents * 9) / 100);
}

#line 126 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline bool TaxEngine_validate_balance(int64_t total_debit, int64_t total_credit) {
    #line 126 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return AccountingCore_validate_balance(total_debit, total_credit);
}

#line 152 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline Invoice InvoiceManager_create_invoice(int64_t customer_id, int64_t items_count, int64_t unit_price_cents, int64_t discount_pct) {
    #line 153 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type subtotal = (items_count * unit_price_cents);
    #line 154 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type discount = ((subtotal * discount_pct) / 100);
    #line 155 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type tax = (((subtotal - discount) * 9) / 100);
    #line 156 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    __auto_type total = ((subtotal - discount) + tax);
    #line 158 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return (Invoice){ .id = 1001, .customer_id = customer_id, .invoice_number = "INV-2026-001", .subtotal_cents = subtotal, .tax_cents = tax, .discount_cents = discount, .total_cents = total, .is_paid = false };
}

#line 126 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline bool InvoiceManager_validate_balance(int64_t total_debit, int64_t total_credit) {
    #line 126 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return AccountingCore_validate_balance(total_debit, total_credit);
}

#line 131 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
static inline int64_t InvoiceManager_compute_tax(int64_t subtotal_cents) {
    #line 131 "C:/Users/ASUS/Desktop/flutter_project/end/examples/end_ledger/src/main.end"
    return AccountingCore_compute_tax(subtotal_cents);
}

