[package]
name = "endc"
version = "2.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.1"
toml = "0.8"
sha2 = "0.10"
argon2 = { version = "0.5", default-features = false, features = ["std", "alloc", "password-hash"] }
hmac = "0.12"
subtle = "2.5"
rand_core = { version = "0.6", features = ["std"] }
z3 = "0.20.2"
inkwell = { version = "0.10.0", default-features = false, features = ["llvm22-1-no-llvm-linking", "target-x86"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pki-types = "1.10"
rustls-pemfile = "2.2"
webpki-roots = "0.26"
rcgen = { version = "0.13", features = ["pem", "ring"] }

[profile.release]
opt-level = 2
lto = false
codegen-units = 16
