/* Generated by End Language Compiler (endc) — Hyper-Optimized Native Output */
#define BUILDING_END_DLL 1
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
    #include <immintrin.h>
#elif defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif

/* End Hardware Watchdog & CPU Throttling Safety Hooks */
#if defined(_WIN32)
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    #define END_CPU_YIELD() SwitchToThread()
    #define END_CPU_RELAX() YieldProcessor()
    #define END_CPU_SLEEP(ms) Sleep(ms)
#else
    #include <sched.h>
    #include <unistd.h>
    #include <time.h>
    #define END_CPU_YIELD() sched_yield()
    #define END_CPU_RELAX() __builtin_ia32_pause()
    #define END_CPU_SLEEP(ms) usleep((ms) * 1000)
#endif

static inline void cpu_yield(void) { END_CPU_YIELD(); }
static inline void cpu_relax(void) { END_CPU_RELAX(); }
static inline void cpu_sleep_ms(int32_t ms) { END_CPU_SLEEP(ms); }
static inline uint64_t high_res_time_ns(void) {
#if defined(_WIN32)
    LARGE_INTEGER count, freq;
    QueryPerformanceCounter(&count);
    QueryPerformanceFrequency(&freq);
    return (uint64_t)((count.QuadPart * 1000000000ULL) / freq.QuadPart);
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)(ts.tv_sec * 1000000000ULL + ts.tv_nsec);
#endif
}

/* End Cross-Platform Export API Macro */
#if defined(_WIN32) || defined(__CYGWIN__)
    #define END_API __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
    #define END_API __attribute__((visibility("default")))
#else
    #define END_API
#endif

/* End Generic Print & Math Prelude Helpers (Zero-Import Available) */
static inline void _end_print_str(const char* s) { printf("%s\n", s); }
static inline void _end_print_int(long long n) { printf("%lld\n", n); }
static inline void _end_print_float(double f) { printf("%f\n", f); }
static inline void _end_print_bool(bool b) { printf("%s\n", b ? "true" : "false"); }
#define end_println(X) _Generic((X), \
    bool: _end_print_bool, \
    int: _end_print_int, \
    long: _end_print_int, \
    long long: _end_print_int, \
    unsigned int: _end_print_int, \
    unsigned long long: _end_print_int, \
    float: _end_print_float, \
    double: _end_print_float, \
    char*: _end_print_str, \
    const char*: _end_print_str)(X)

/* End Memory Primitives (64-byte Cache-Line Aligned) */
typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;
typedef struct { char* buffer; size_t capacity; size_t offset; } EndArena;
static EndArena* end_arena_create(size_t cap) {
    EndArena* a = (EndArena*)malloc(sizeof(EndArena));
    a->buffer = (char*)malloc(cap);
    a->capacity = cap;
    a->offset = 0;
    return a;
}
static void* end_arena_alloc(EndArena* a, size_t size) {
    if (a->offset + size > a->capacity) return NULL;
    void* ptr = (void*)(a->buffer + a->offset);
    a->offset += (size + 63) & ~63;
    return ptr;
}
static void end_arena_destroy(EndArena* a) {
    if (a) { free(a->buffer); free(a); }
}

/* End Native Desktop Windowing Runtime */
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
typedef struct EndWindow {
    HWND hwnd;
    HDC hdc;
    int32_t width;
    int32_t height;
    bool is_open;
    BITMAPINFO bmi;
} EndWindow;
static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }
    return DefWindowProcA(hWnd, msg, wParam, lParam);
}
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {
    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));
    win->width = width;
    win->height = height;
    win->is_open = true;
    HINSTANCE hInstance = GetModuleHandle(NULL);
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(WNDCLASSEXA);
    wc.lpfnWndProc = EndWndProc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.lpszClassName = "EndNativeWindow";
    RegisterClassExA(&wc);
    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    win->bmi.bmiHeader.biWidth = width;
    win->bmi.bmiHeader.biHeight = -height;
    win->bmi.bmiHeader.biPlanes = 1;
    win->bmi.bmiHeader.biBitCount = 32;
    win->bmi.bmiHeader.biCompression = BI_RGB;
    win->hwnd = CreateWindowExA(0, "EndNativeWindow", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);
    win->hdc = GetDC(win->hwnd);
    ShowWindow(win->hwnd, SW_SHOW);
    UpdateWindow(win->hwnd);
    return win;
}
static inline bool window_poll(EndWindow* win) {
    if (!win) return false;
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        if (msg.message == WM_QUIT) { win->is_open = false; return false; }
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
    return win->is_open;
}
static inline void window_present(EndWindow* win, uint32_t* pixels) {
    if (!win || !win->is_open || !pixels) return;
    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);
}
static inline void window_sleep(int32_t ms) {
    Sleep(ms);
}
#else
typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }
static inline bool window_poll(EndWindow* win) { return false; }
static inline void window_present(EndWindow* win, uint32_t* pixels) {}
static inline void window_sleep(int32_t ms) {}
#endif

/* Hybrid 3-Tier Memory Model Runtime */
typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;
static inline void* end_rc_new(size_t size, const void* src) {
    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);
    h->ref_count = 1;
    if (src) memcpy(h->data, src, size);
    return (void*)h->data;
}
static inline void* end_rc_clone(void* ptr) {
    if (!ptr) return NULL;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count++;
    return ptr;
}
static inline void end_rc_drop(void* ptr) {
    if (!ptr) return;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count--;
    if (h->ref_count <= 0) free(h);
}
static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {
    if (!ptr || !target_arena) return ptr;
    void* new_ptr = end_arena_alloc(target_arena, size);
    if (new_ptr) memcpy(new_ptr, ptr, size);
    return new_ptr ? new_ptr : ptr;
}

/* End Lightweight Concurrency & Channel Runtime */
typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;
static inline EndChannel* channel_create(int32_t cap) {
    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));
    ch->buffer = (void**)malloc(sizeof(void*) * cap);
    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;
    return ch;
}
static inline void channel_send(EndChannel* ch, void* val) {
    if (ch->count < ch->capacity) {
        ch->buffer[ch->tail] = val;
        ch->tail = (ch->tail + 1) % ch->capacity;
        ch->count++;
    }
}
static inline void* channel_recv(EndChannel* ch) {
    if (ch->count == 0) return NULL;
    void* val = ch->buffer[ch->head];
        ch->head = (ch->head + 1) % ch->capacity;
        ch->count--;
    return val;
}

/* End High-Resolution Hardware Timer Runtime (std::time) */
#if defined(_WIN32)
static inline uint64_t end_time_now_nanos(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_micros(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_millis(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);
}
#else
#include <time.h>
static inline uint64_t end_time_now_nanos(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}
static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }
static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>
#include <windows.h>

typedef struct Repository Repository;
typedef struct Pipeline Pipeline;
typedef struct DiContainer DiContainer;

struct Repository {
    const char* table_name;
    const char* id_field;
    int32_t cached_entities;
    bool is_connected;
};

struct Pipeline {
    int64_t pipeline_id;
    int32_t middleware_stages;
    bool is_sealed;
};

struct DiContainer {
    int32_t service_count;
    bool is_locked;
};

END_API Repository repository_create(const char* table, const char* key_field);
END_API int64_t repository_count(Repository repo);
END_API Pipeline pipeline_create(void);
END_API Pipeline pipeline_pipe(Pipeline pipe);
END_API bool pipeline_execute(Pipeline pipe);
END_API DiContainer di_container_create(void);
END_API int64_t ecommerce_process_order(int64_t item_id, int64_t price, int64_t qty);
END_API void send_http_response(int32_t client_sock, const char* status_code, const char* mime_type, const char* body);
END_API void serve_static(int32_t client_sock, const char* filepath, const char* mime);
END_API void handle_client(int32_t client_sock, int64_t req_seq);
int main(void);

#line 11 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/repository.end"
END_API Repository repository_create(const char* table, const char* key_field) {
    #line 12 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/repository.end"
    return (Repository){ .table_name = table, .id_field = key_field, .cached_entities = 0, .is_connected = true };
}

#line 20 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/repository.end"
END_API int64_t repository_count(Repository repo) {
    #line 21 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/repository.end"
    return repo.cached_entities;
}

#line 10 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
END_API Pipeline pipeline_create(void) {
    #line 11 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
    return (Pipeline){ .pipeline_id = 101, .middleware_stages = 0, .is_sealed = false };
}

#line 18 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
END_API Pipeline pipeline_pipe(Pipeline pipe) {
    #line 19 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
    return (Pipeline){ .pipeline_id = pipe.pipeline_id, .middleware_stages = (pipe.middleware_stages + 1), .is_sealed = pipe.is_sealed };
}

#line 26 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
END_API bool pipeline_execute(Pipeline pipe) {
    #line 27 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
    return (pipe.middleware_stages > 0);
}

#line 9 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/di.end"
END_API DiContainer di_container_create(void) {
    #line 10 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/di.end"
    return (DiContainer){ .service_count = 0, .is_locked = false };
}

#line 9 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
END_API int64_t ecommerce_process_order(int64_t item_id, int64_t price, int64_t qty) {
    #line 10 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
    int64_t total_charged = 0;
    #line 11 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
    /* Enter Region: arena */
    EndArena* region_arena = end_arena_create(64 * 1024);
    {
        #line 12 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
        __auto_type repo = repository_create("orders", "order_id");
        #line 13 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
        __auto_type di = di_container_create();
        #line 14 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
        __auto_type pipe = pipeline_create();
        #line 15 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
        __auto_type p2 = pipeline_pipe(pipe);
        #line 16 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
        __auto_type p3 = pipeline_pipe(p2);
        #line 18 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
        total_charged = ((price * qty) + 15);
    }
    end_arena_destroy(region_arena);
    #line 20 "projects/06_clean_ecommerce_api/server/./modules/ecommerce.end"
    return total_charged;
}

#line 14 "projects/06_clean_ecommerce_api/server/main.end"
END_API void send_http_response(int32_t client_sock, const char* status_code, const char* mime_type, const char* body) {
    #line 15 "projects/06_clean_ecommerce_api/server/main.end"
    /* Enter Region: res_scope */
    EndArena* region_res_scope = end_arena_create(64 * 1024);
    {
        #line 16 "projects/06_clean_ecommerce_api/server/main.end"
        char* header_buf = (char*)malloc(1024 * sizeof(char));
        #line 17 "projects/06_clean_ecommerce_api/server/main.end"
        __auto_type body_len = strlen(body);
        #line 18 "projects/06_clean_ecommerce_api/server/main.end"
        __auto_type crlf = "\r\n";
        #line 19 "projects/06_clean_ecommerce_api/server/main.end"
        sprintf(header_buf, "HTTP/1.1 %s%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sAccess-Control-Allow-Methods: GET, POST, OPTIONS%sAccess-Control-Allow-Headers: *%sCache-Control: no-cache%sContent-Length: %d%sConnection: close%s%s", status_code, crlf, mime_type, crlf, crlf, crlf, crlf, crlf, body_len, crlf, crlf, crlf);
        #line 20 "projects/06_clean_ecommerce_api/server/main.end"
        send(client_sock, header_buf, strlen(header_buf), 0);
        #line 21 "projects/06_clean_ecommerce_api/server/main.end"
        send(client_sock, body, body_len, 0);
    }
    end_arena_destroy(region_res_scope);
}

#line 25 "projects/06_clean_ecommerce_api/server/main.end"
END_API void serve_static(int32_t client_sock, const char* filepath, const char* mime) {
    #line 26 "projects/06_clean_ecommerce_api/server/main.end"
    /* Enter Region: file_scope */
    EndArena* region_file_scope = end_arena_create(64 * 1024);
    {
        #line 27 "projects/06_clean_ecommerce_api/server/main.end"
        __auto_type f = fopen(filepath, "rb");
        #line 28 "projects/06_clean_ecommerce_api/server/main.end"
        if ((f == NULL)) {
            #line 29 "projects/06_clean_ecommerce_api/server/main.end"
            send_http_response(client_sock, "404 Not Found", "text/plain", "Static File Not Found");
            #line 30 "projects/06_clean_ecommerce_api/server/main.end"
            return;
        }
        #line 32 "projects/06_clean_ecommerce_api/server/main.end"
        fseek(f, 0, 2);
        #line 33 "projects/06_clean_ecommerce_api/server/main.end"
        __auto_type fsize = ftell(f);
        #line 34 "projects/06_clean_ecommerce_api/server/main.end"
        fseek(f, 0, 0);
        #line 35 "projects/06_clean_ecommerce_api/server/main.end"
        char* fbuf = (char*)malloc(524288 * sizeof(char));
        #line 36 "projects/06_clean_ecommerce_api/server/main.end"
        __auto_type read_len = fread(fbuf, 1, fsize, f);
        #line 37 "projects/06_clean_ecommerce_api/server/main.end"
        fclose(f);
        #line 39 "projects/06_clean_ecommerce_api/server/main.end"
        char* header_buf = (char*)malloc(512 * sizeof(char));
        #line 40 "projects/06_clean_ecommerce_api/server/main.end"
        __auto_type crlf = "\r\n";
        #line 41 "projects/06_clean_ecommerce_api/server/main.end"
        sprintf(header_buf, "HTTP/1.1 200 OK%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sCache-Control: no-cache%sContent-Length: %d%sConnection: close%s%s", crlf, mime, crlf, crlf, crlf, read_len, crlf, crlf, crlf);
        #line 42 "projects/06_clean_ecommerce_api/server/main.end"
        send(client_sock, header_buf, strlen(header_buf), 0);
        #line 43 "projects/06_clean_ecommerce_api/server/main.end"
        send(client_sock, fbuf, read_len, 0);
    }
    end_arena_destroy(region_file_scope);
}

#line 47 "projects/06_clean_ecommerce_api/server/main.end"
END_API void handle_client(int32_t client_sock, int64_t req_seq) {
    #line 48 "projects/06_clean_ecommerce_api/server/main.end"
    /* Enter Region: client_scope */
    EndArena* region_client_scope = end_arena_create(64 * 1024);
    {
        #line 49 "projects/06_clean_ecommerce_api/server/main.end"
        char* recv_buf = (char*)malloc(8192 * sizeof(char));
        #line 50 "projects/06_clean_ecommerce_api/server/main.end"
        __auto_type bytes_read = recv(client_sock, recv_buf, 8191, 0);
        #line 51 "projects/06_clean_ecommerce_api/server/main.end"
        if ((bytes_read <= 0)) {
            #line 52 "projects/06_clean_ecommerce_api/server/main.end"
            closesocket(client_sock);
            #line 53 "projects/06_clean_ecommerce_api/server/main.end"
            return;
        }
        #line 55 "projects/06_clean_ecommerce_api/server/main.end"
        recv_buf[bytes_read] = 0;
        #line 57 "projects/06_clean_ecommerce_api/server/main.end"
        char* method = (char*)malloc(16 * sizeof(char));
        #line 58 "projects/06_clean_ecommerce_api/server/main.end"
        char* path = (char*)malloc(256 * sizeof(char));
        #line 59 "projects/06_clean_ecommerce_api/server/main.end"
        sscanf(recv_buf, "%15s %255s", method, path);
        #line 61 "projects/06_clean_ecommerce_api/server/main.end"
        if (((strcmp(path, "/") == 0) || (strcmp(path, "/index.html") == 0))) {
            #line 62 "projects/06_clean_ecommerce_api/server/main.end"
            serve_static(client_sock, "projects/06_clean_ecommerce_api/web/index.html", "text/html; charset=utf-8");
        } else {
            #line 63 "projects/06_clean_ecommerce_api/server/main.end"
            if ((strcmp(path, "/style.css") == 0)) {
                #line 64 "projects/06_clean_ecommerce_api/server/main.end"
                serve_static(client_sock, "projects/06_clean_ecommerce_api/web/style.css", "text/css; charset=utf-8");
            } else {
                #line 65 "projects/06_clean_ecommerce_api/server/main.end"
                if ((strcmp(path, "/app.js") == 0)) {
                    #line 66 "projects/06_clean_ecommerce_api/server/main.end"
                    serve_static(client_sock, "projects/06_clean_ecommerce_api/web/app.js", "application/javascript; charset=utf-8");
                } else {
                    #line 67 "projects/06_clean_ecommerce_api/server/main.end"
                    if ((strcmp(path, "/api/shop/checkout") == 0)) {
                        #line 68 "projects/06_clean_ecommerce_api/server/main.end"
                        int64_t price = 299;
                        #line 69 "projects/06_clean_ecommerce_api/server/main.end"
                        int64_t qty = 2;
                        #line 70 "projects/06_clean_ecommerce_api/server/main.end"
                        __auto_type total = ecommerce_process_order(req_seq, price, qty);
                        #line 71 "projects/06_clean_ecommerce_api/server/main.end"
                        char* json_buf = (char*)malloc(2048 * sizeof(char));
                        #line 72 "projects/06_clean_ecommerce_api/server/main.end"
                        sprintf(json_buf, "{\"order_status\":\"CONFIRMED\",\"order_id\":%lld,\"item\":\"Quantum Dev Keyboard\",\"unit_price\":%lld,\"quantity\":%lld,\"shipping_usd\":15,\"total_usd\":%lld,\"patterns_used\":[\"Repository (std/patterns/repository)\",\"Pipeline Middleware (std/patterns/pipeline)\",\"Dependency Injection (std/patterns/di)\"],\"pipeline_stages\":[\"RateLimiter\",\"JwtAuthGuard\",\"InventoryValidation\",\"TaxCalculator\",\"OrderRepositorySave\"],\"architecture\":\"Clean Hexagonal (Strict E0902 Compliant)\"}", req_seq, price, qty, total);
                        #line 73 "projects/06_clean_ecommerce_api/server/main.end"
                        send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_buf);
                    } else {
                        #line 74 "projects/06_clean_ecommerce_api/server/main.end"
                        if ((strcmp(path, "/api/shop/catalog") == 0)) {
                            #line 75 "projects/06_clean_ecommerce_api/server/main.end"
                            char* json_cat = (char*)malloc(1024 * sizeof(char));
                            #line 76 "projects/06_clean_ecommerce_api/server/main.end"
                            sprintf(json_cat, "{\"products\":[{\"id\":101,\"name\":\"End Enterprise Server Box\",\"price\":1299,\"stock\":42},{\"id\":102,\"name\":\"Quantum Dev Keyboard\",\"price\":299,\"stock\":150},{\"id\":103,\"name\":\"AI Neural Accelerator\",\"price\":899,\"stock\":88}],\"repository_cache\":\"Warm (100%% Hit)\"}", 0);
                            #line 77 "projects/06_clean_ecommerce_api/server/main.end"
                            send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_cat);
                        } else {
                            #line 79 "projects/06_clean_ecommerce_api/server/main.end"
                            send_http_response(client_sock, "404 Not Found", "text/plain", "Route Not Found");
                        }
                    }
                }
            }
        }
        #line 82 "projects/06_clean_ecommerce_api/server/main.end"
        closesocket(client_sock);
    }
    end_arena_destroy(region_client_scope);
}

#line 86 "projects/06_clean_ecommerce_api/server/main.end"
int main(void) {
    #line 87 "projects/06_clean_ecommerce_api/server/main.end"
    end_println("============================================================");
    #line 88 "projects/06_clean_ecommerce_api/server/main.end"
    end_println("🛍️ SAMPLE APP 1: CLEAN E-COMMERCE API (PORT 5006)");
    #line 89 "projects/06_clean_ecommerce_api/server/main.end"
    end_println("🔗 Localhost URL: http://localhost:5006");
    #line 90 "projects/06_clean_ecommerce_api/server/main.end"
    end_println("============================================================");
    #line 92 "projects/06_clean_ecommerce_api/server/main.end"
    void* wsa_data = (char*)malloc(512 * sizeof(char));
    #line 93 "projects/06_clean_ecommerce_api/server/main.end"
    WSAStartup(514, wsa_data);
    #line 95 "projects/06_clean_ecommerce_api/server/main.end"
    __auto_type server_sock = socket(2, 1, 6);
    #line 96 "projects/06_clean_ecommerce_api/server/main.end"
    char* server_addr = (char*)malloc(32 * sizeof(char));
    #line 97 "projects/06_clean_ecommerce_api/server/main.end"
    memset(server_addr, 0, 32);
    #line 98 "projects/06_clean_ecommerce_api/server/main.end"
    server_addr[0] = 2;
    #line 99 "projects/06_clean_ecommerce_api/server/main.end"
    server_addr[1] = 0;
    #line 100 "projects/06_clean_ecommerce_api/server/main.end"
    server_addr[2] = 19;
    #line 101 "projects/06_clean_ecommerce_api/server/main.end"
    server_addr[3] = 142;
    #line 103 "projects/06_clean_ecommerce_api/server/main.end"
    int32_t* opt = (int32_t*)malloc(1 * sizeof(int32_t));
    #line 104 "projects/06_clean_ecommerce_api/server/main.end"
    opt[0] = 1;
    #line 105 "projects/06_clean_ecommerce_api/server/main.end"
    setsockopt(server_sock, 65535, 4, opt, 4);
    #line 107 "projects/06_clean_ecommerce_api/server/main.end"
    __auto_type bind_res = bind(server_sock, server_addr, 16);
    #line 108 "projects/06_clean_ecommerce_api/server/main.end"
    if ((bind_res >= 0)) {
        #line 109 "projects/06_clean_ecommerce_api/server/main.end"
        listen(server_sock, 128);
        #line 110 "projects/06_clean_ecommerce_api/server/main.end"
        end_println("E-Commerce Server listening on 0.0.0.0:5006...");
        #line 112 "projects/06_clean_ecommerce_api/server/main.end"
        int64_t req_seq = 1;
        #line 113 "projects/06_clean_ecommerce_api/server/main.end"
        while (true) {
            #line 114 "projects/06_clean_ecommerce_api/server/main.end"
            __auto_type client_sock = accept(server_sock, NULL, NULL);
            #line 115 "projects/06_clean_ecommerce_api/server/main.end"
            if (((client_sock == 4294967295) || (client_sock < 0))) {
                #line 116 "projects/06_clean_ecommerce_api/server/main.end"
                Sleep(10);
            } else {
                #line 118 "projects/06_clean_ecommerce_api/server/main.end"
                handle_client(client_sock, req_seq);
                #line 119 "projects/06_clean_ecommerce_api/server/main.end"
                req_seq = (req_seq + 1);
            }
        }
    } else {
        #line 123 "projects/06_clean_ecommerce_api/server/main.end"
        end_println("ERROR: Failed to bind socket on port 5006!");
    }
    #line 126 "projects/06_clean_ecommerce_api/server/main.end"
    closesocket(server_sock);
    #line 127 "projects/06_clean_ecommerce_api/server/main.end"
    WSACleanup();
    return 0;
}

