/* Generated by End Language Compiler (endc) — Hyper-Optimized Native Output */
#define BUILDING_END_DLL 1
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
    #include <immintrin.h>
#elif defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif

/* End Hardware Watchdog & CPU Throttling Safety Hooks */
#if defined(_WIN32)
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    #define END_CPU_YIELD() SwitchToThread()
    #define END_CPU_RELAX() YieldProcessor()
    #define END_CPU_SLEEP(ms) Sleep(ms)
#else
    #include <sched.h>
    #include <unistd.h>
    #include <time.h>
    #define END_CPU_YIELD() sched_yield()
    #define END_CPU_RELAX() __builtin_ia32_pause()
    #define END_CPU_SLEEP(ms) usleep((ms) * 1000)
#endif

static inline void cpu_yield(void) { END_CPU_YIELD(); }
static inline void cpu_relax(void) { END_CPU_RELAX(); }
static inline void cpu_sleep_ms(int32_t ms) { END_CPU_SLEEP(ms); }
static inline uint64_t high_res_time_ns(void) {
#if defined(_WIN32)
    LARGE_INTEGER count, freq;
    QueryPerformanceCounter(&count);
    QueryPerformanceFrequency(&freq);
    return (uint64_t)((count.QuadPart * 1000000000ULL) / freq.QuadPart);
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)(ts.tv_sec * 1000000000ULL + ts.tv_nsec);
#endif
}

/* End Cross-Platform Export API Macro */
#if defined(_WIN32) || defined(__CYGWIN__)
    #define END_API __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
    #define END_API __attribute__((visibility("default")))
#else
    #define END_API
#endif

/* End Generic Print & Math Prelude Helpers (Zero-Import Available) */
static inline void _end_print_str(const char* s) { printf("%s\n", s); }
static inline void _end_print_int(long long n) { printf("%lld\n", n); }
static inline void _end_print_float(double f) { printf("%f\n", f); }
static inline void _end_print_bool(bool b) { printf("%s\n", b ? "true" : "false"); }
#define end_println(X) _Generic((X), \
    bool: _end_print_bool, \
    int: _end_print_int, \
    long: _end_print_int, \
    long long: _end_print_int, \
    unsigned int: _end_print_int, \
    unsigned long long: _end_print_int, \
    float: _end_print_float, \
    double: _end_print_float, \
    char*: _end_print_str, \
    const char*: _end_print_str)(X)

/* End Zero-Cost Memory Primitives (64-byte Cache-Line Aligned) */
typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;
typedef struct { char* buffer; size_t capacity; size_t offset; bool is_heap; } EndArena;
#if defined(_MSC_VER)
    static __declspec(thread) char _end_tls_scratchpad[4 * 1024 * 1024];
    static __declspec(thread) size_t _end_tls_offset = 0;
#else
    static __thread char _end_tls_scratchpad[4 * 1024 * 1024];
    static __thread size_t _end_tls_offset = 0;
#endif

static inline EndArena* end_arena_create(size_t cap) {
    if (_end_tls_offset + sizeof(EndArena) + cap <= sizeof(_end_tls_scratchpad)) {
        EndArena* a = (EndArena*)(_end_tls_scratchpad + _end_tls_offset);
        _end_tls_offset += (sizeof(EndArena) + 63) & ~63;
        a->buffer = _end_tls_scratchpad + _end_tls_offset;
        _end_tls_offset += (cap + 63) & ~63;
        a->capacity = cap;
        a->offset = 0;
        a->is_heap = false;
        return a;
    }
    EndArena* a = (EndArena*)malloc(sizeof(EndArena));
    a->buffer = (char*)malloc(cap);
    a->capacity = cap;
    a->offset = 0;
    a->is_heap = true;
    return a;
}
static inline void* end_arena_alloc(EndArena* a, size_t size) {
    size_t aligned = (size + 63) & ~63;
    if (a->offset + aligned > a->capacity) return NULL;
    void* ptr = (void*)(a->buffer + a->offset);
    a->offset += aligned;
    return ptr;
}
static inline void end_arena_destroy(EndArena* a) {
    if (!a) return;
    if (a->is_heap) { free(a->buffer); free(a); }
    else { _end_tls_offset = 0; }
}

/* End Native Desktop Windowing Runtime */
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
typedef struct EndWindow {
    HWND hwnd;
    HDC hdc;
    int32_t width;
    int32_t height;
    bool is_open;
    BITMAPINFO bmi;
} EndWindow;
static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }
    return DefWindowProcA(hWnd, msg, wParam, lParam);
}
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {
    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));
    win->width = width;
    win->height = height;
    win->is_open = true;
    HINSTANCE hInstance = GetModuleHandle(NULL);
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(WNDCLASSEXA);
    wc.lpfnWndProc = EndWndProc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.lpszClassName = "EndNativeWindow";
    RegisterClassExA(&wc);
    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    win->bmi.bmiHeader.biWidth = width;
    win->bmi.bmiHeader.biHeight = -height;
    win->bmi.bmiHeader.biPlanes = 1;
    win->bmi.bmiHeader.biBitCount = 32;
    win->bmi.bmiHeader.biCompression = BI_RGB;
    win->hwnd = CreateWindowExA(0, "EndNativeWindow", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);
    win->hdc = GetDC(win->hwnd);
    ShowWindow(win->hwnd, SW_SHOW);
    UpdateWindow(win->hwnd);
    return win;
}
static inline bool window_poll(EndWindow* win) {
    if (!win) return false;
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        if (msg.message == WM_QUIT) { win->is_open = false; return false; }
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
    return win->is_open;
}
static inline void window_present(EndWindow* win, uint32_t* pixels) {
    if (!win || !win->is_open || !pixels) return;
    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);
}
static inline void window_sleep(int32_t ms) {
    Sleep(ms);
}
#else
typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }
static inline bool window_poll(EndWindow* win) { return false; }
static inline void window_present(EndWindow* win, uint32_t* pixels) {}
static inline void window_sleep(int32_t ms) {}
#endif

/* Hybrid 3-Tier Memory Model Runtime */
typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;
static inline void* end_rc_new(size_t size, const void* src) {
    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);
    h->ref_count = 1;
    if (src) memcpy(h->data, src, size);
    return (void*)h->data;
}
static inline void* end_rc_clone(void* ptr) {
    if (!ptr) return NULL;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count++;
    return ptr;
}
static inline void end_rc_drop(void* ptr) {
    if (!ptr) return;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count--;
    if (h->ref_count <= 0) free(h);
}
static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {
    if (!ptr || !target_arena) return ptr;
    void* new_ptr = end_arena_alloc(target_arena, size);
    if (new_ptr) memcpy(new_ptr, ptr, size);
    return new_ptr ? new_ptr : ptr;
}

/* End Lightweight Concurrency & Channel Runtime */
typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;
static inline EndChannel* channel_create(int32_t cap) {
    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));
    ch->buffer = (void**)malloc(sizeof(void*) * cap);
    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;
    return ch;
}
static inline void channel_send(EndChannel* ch, void* val) {
    if (ch->count < ch->capacity) {
        ch->buffer[ch->tail] = val;
        ch->tail = (ch->tail + 1) % ch->capacity;
        ch->count++;
    }
}
static inline void* channel_recv(EndChannel* ch) {
    if (ch->count == 0) return NULL;
    void* val = ch->buffer[ch->head];
        ch->head = (ch->head + 1) % ch->capacity;
        ch->count--;
    return val;
}

/* End High-Resolution Hardware Timer Runtime (std::time) */
#if defined(_WIN32)
static inline uint64_t end_time_now_nanos(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_micros(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_millis(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);
}
#else
#include <time.h>
static inline uint64_t end_time_now_nanos(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}
static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }
static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }
#endif


typedef struct Vector3 Vector3;

struct Vector3 {
    double x;
    double y;
    double z;
};

static inline int64_t double_val(int64_t x);
static inline int64_t add_five(int64_t x);
int main(void);

static inline double Vector3_length_squared(Vector3* self);
static inline int64_t HttpServiceBase_handle(int64_t code);
static inline int64_t OrderService_handle(int64_t code);

#line 30 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
static inline int64_t double_val(int64_t x) {
    #line 31 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    return (x * 2);
}

#line 34 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
static inline int64_t add_five(int64_t x) {
    #line 35 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    return (x + 5);
}

#line 38 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
int main(void) {
    #line 39 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    end_println("--- Testing End Modular & Vibe Coding Features ---");
    #line 42 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    __auto_type v = (Vector3){ .x = 3.000000f, .y = 4.000000f, .z = 0.000000f };
    #line 43 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    __auto_type sq = Vector3_length_squared(&v);
    #line 44 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    end_println(sq);
    #line 47 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    __auto_type base_res = HttpServiceBase_handle(10);
    #line 48 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    end_println(base_res);
    #line 51 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    __auto_type order_res = OrderService_handle(10);
    #line 52 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    end_println(order_res);
    #line 55 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    __auto_type pipe_res = add_five(double_val(10));
    #line 56 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    end_println(pipe_res);
    #line 59 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    printf("[INLINE-C] Direct C execution verified!\n");

    #line 63 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    return 0;
    return 0;
}

#line 11 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
static inline double Vector3_length_squared(Vector3* self) {
    #line 12 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    return (((self->x * self->x) + (self->y * self->y)) + (self->z * self->z));
}

#line 18 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
static inline int64_t HttpServiceBase_handle(int64_t code) {
    #line 19 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    return (code + 100);
}

#line 25 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
static inline int64_t OrderService_handle(int64_t code) {
    #line 26 "C:/Users/ASUS/Desktop/flutter_project/end/tests/test_modular_vibe_coding.end"
    return (code + 500);
}

