/* Generated by End Language Compiler (endc) — Hyper-Optimized Native Output */
#define BUILDING_END_DLL 1
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
    #include <immintrin.h>
#elif defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif

/* End Hardware Watchdog & CPU Throttling Safety Hooks */
#if defined(_WIN32)
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    #define END_CPU_YIELD() SwitchToThread()
    #define END_CPU_RELAX() YieldProcessor()
    #define END_CPU_SLEEP(ms) Sleep(ms)
#else
    #include <sched.h>
    #include <unistd.h>
    #include <time.h>
    #define END_CPU_YIELD() sched_yield()
    #define END_CPU_RELAX() __builtin_ia32_pause()
    #define END_CPU_SLEEP(ms) usleep((ms) * 1000)
#endif

static inline void cpu_yield(void) { END_CPU_YIELD(); }
static inline void cpu_relax(void) { END_CPU_RELAX(); }
static inline void cpu_sleep_ms(int32_t ms) { END_CPU_SLEEP(ms); }
static inline uint64_t high_res_time_ns(void) {
#if defined(_WIN32)
    LARGE_INTEGER count, freq;
    QueryPerformanceCounter(&count);
    QueryPerformanceFrequency(&freq);
    return (uint64_t)((count.QuadPart * 1000000000ULL) / freq.QuadPart);
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)(ts.tv_sec * 1000000000ULL + ts.tv_nsec);
#endif
}

/* End Cross-Platform Export API Macro */
#if defined(_WIN32) || defined(__CYGWIN__)
    #define END_API __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
    #define END_API __attribute__((visibility("default")))
#else
    #define END_API
#endif

/* End Generic Print & Math Prelude Helpers (Zero-Import Available) */
static inline void _end_print_str(const char* s) { printf("%s\n", s); }
static inline void _end_print_int(long long n) { printf("%lld\n", n); }
static inline void _end_print_float(double f) { printf("%f\n", f); }
static inline void _end_print_bool(bool b) { printf("%s\n", b ? "true" : "false"); }
#define end_println(X) _Generic((X), \
    bool: _end_print_bool, \
    int: _end_print_int, \
    long: _end_print_int, \
    long long: _end_print_int, \
    unsigned int: _end_print_int, \
    unsigned long long: _end_print_int, \
    float: _end_print_float, \
    double: _end_print_float, \
    char*: _end_print_str, \
    const char*: _end_print_str)(X)

/* End Memory Primitives (64-byte Cache-Line Aligned) */
typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;
typedef struct { char* buffer; size_t capacity; size_t offset; } EndArena;
static EndArena* end_arena_create(size_t cap) {
    EndArena* a = (EndArena*)malloc(sizeof(EndArena));
    a->buffer = (char*)malloc(cap);
    a->capacity = cap;
    a->offset = 0;
    return a;
}
static void* end_arena_alloc(EndArena* a, size_t size) {
    if (a->offset + size > a->capacity) return NULL;
    void* ptr = (void*)(a->buffer + a->offset);
    a->offset += (size + 63) & ~63;
    return ptr;
}
static void end_arena_destroy(EndArena* a) {
    if (a) { free(a->buffer); free(a); }
}

/* End Native Desktop Windowing Runtime */
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
typedef struct EndWindow {
    HWND hwnd;
    HDC hdc;
    int32_t width;
    int32_t height;
    bool is_open;
    BITMAPINFO bmi;
} EndWindow;
static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }
    return DefWindowProcA(hWnd, msg, wParam, lParam);
}
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {
    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));
    win->width = width;
    win->height = height;
    win->is_open = true;
    HINSTANCE hInstance = GetModuleHandle(NULL);
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(WNDCLASSEXA);
    wc.lpfnWndProc = EndWndProc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.lpszClassName = "EndNativeWindow";
    RegisterClassExA(&wc);
    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    win->bmi.bmiHeader.biWidth = width;
    win->bmi.bmiHeader.biHeight = -height;
    win->bmi.bmiHeader.biPlanes = 1;
    win->bmi.bmiHeader.biBitCount = 32;
    win->bmi.bmiHeader.biCompression = BI_RGB;
    win->hwnd = CreateWindowExA(0, "EndNativeWindow", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);
    win->hdc = GetDC(win->hwnd);
    ShowWindow(win->hwnd, SW_SHOW);
    UpdateWindow(win->hwnd);
    return win;
}
static inline bool window_poll(EndWindow* win) {
    if (!win) return false;
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        if (msg.message == WM_QUIT) { win->is_open = false; return false; }
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
    return win->is_open;
}
static inline void window_present(EndWindow* win, uint32_t* pixels) {
    if (!win || !win->is_open || !pixels) return;
    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);
}
static inline void window_sleep(int32_t ms) {
    Sleep(ms);
}
#else
typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }
static inline bool window_poll(EndWindow* win) { return false; }
static inline void window_present(EndWindow* win, uint32_t* pixels) {}
static inline void window_sleep(int32_t ms) {}
#endif

/* Hybrid 3-Tier Memory Model Runtime */
typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;
static inline void* end_rc_new(size_t size, const void* src) {
    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);
    h->ref_count = 1;
    if (src) memcpy(h->data, src, size);
    return (void*)h->data;
}
static inline void* end_rc_clone(void* ptr) {
    if (!ptr) return NULL;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count++;
    return ptr;
}
static inline void end_rc_drop(void* ptr) {
    if (!ptr) return;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count--;
    if (h->ref_count <= 0) free(h);
}
static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {
    if (!ptr || !target_arena) return ptr;
    void* new_ptr = end_arena_alloc(target_arena, size);
    if (new_ptr) memcpy(new_ptr, ptr, size);
    return new_ptr ? new_ptr : ptr;
}

/* End Lightweight Concurrency & Channel Runtime */
typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;
static inline EndChannel* channel_create(int32_t cap) {
    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));
    ch->buffer = (void**)malloc(sizeof(void*) * cap);
    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;
    return ch;
}
static inline void channel_send(EndChannel* ch, void* val) {
    if (ch->count < ch->capacity) {
        ch->buffer[ch->tail] = val;
        ch->tail = (ch->tail + 1) % ch->capacity;
        ch->count++;
    }
}
static inline void* channel_recv(EndChannel* ch) {
    if (ch->count == 0) return NULL;
    void* val = ch->buffer[ch->head];
        ch->head = (ch->head + 1) % ch->capacity;
        ch->count--;
    return val;
}

/* End High-Resolution Hardware Timer Runtime (std::time) */
#if defined(_WIN32)
static inline uint64_t end_time_now_nanos(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_micros(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_millis(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);
}
#else
#include <time.h>
static inline uint64_t end_time_now_nanos(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}
static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }
static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>
#include <windows.h>

typedef struct GgufQuantType GgufQuantType;
typedef struct TensorShape TensorShape;
typedef struct Tensor Tensor;
typedef struct GgufTensorInfo GgufTensorInfo;
typedef struct GgufModel GgufModel;
typedef struct Pipeline Pipeline;

typedef enum {
    GgufQuantType_F32,
    GgufQuantType_F16,
    GgufQuantType_Q4_0,
    GgufQuantType_Q4_1,
    GgufQuantType_Q5_0,
    GgufQuantType_Q5_1,
    GgufQuantType_Q8_0,
    GgufQuantType_Q4_K,
    GgufQuantType_Q5_K,
    GgufQuantType_Q6_K,
} GgufQuantType_Tag;

struct GgufQuantType {
    GgufQuantType_Tag tag;
};

struct TensorShape {
    int32_t dims;
    int32_t rows;
    int32_t cols;
};

struct Tensor {
    TensorShape shape;
    int64_t total_elements;
    bool is_contiguous;
};

struct GgufTensorInfo {
    const char* name;
    GgufQuantType quant_type;
    int64_t offset_bytes;
    int64_t size_bytes;
};

struct GgufModel {
    const char* magic;
    int32_t version;
    int64_t tensor_count;
    int64_t metadata_kv_count;
    bool is_loaded;
};

struct Pipeline {
    int64_t pipeline_id;
    int32_t middleware_stages;
    bool is_sealed;
};

END_API Tensor tensor_2d(int32_t rows, int32_t cols);
END_API Tensor tensor_matmul(Tensor a, Tensor b);
END_API Tensor tensor_relu(Tensor t);
END_API Tensor tensor_transpose(Tensor t);
END_API GgufModel gguf_load_from_memory(int64_t byte_count);
END_API GgufTensorInfo gguf_get_tensor_info(GgufModel model, int64_t tensor_idx);
END_API int64_t neural_matmul_benchmark(int32_t dim);
END_API int64_t neural_embedding_similarity(int32_t vec_len, int64_t seed);
END_API int64_t neural_infer_tokens(int32_t prompt_len, int32_t target_tokens);
END_API Pipeline pipeline_create(void);
END_API Pipeline pipeline_pipe(Pipeline pipe);
END_API bool pipeline_execute(Pipeline pipe);
END_API void send_http_response(int32_t client_sock, const char* status_code, const char* mime_type, const char* body);
END_API void serve_static(int32_t client_sock, const char* filepath, const char* mime);
END_API void handle_client(int32_t client_sock, int64_t req_seq);
int main(void);

#line 16 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
END_API Tensor tensor_2d(int32_t rows, int32_t cols) {
    #line 17 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
    int64_t total = (rows * cols);
    #line 18 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
    return (Tensor){ .shape = (TensorShape){ .dims = 2, .rows = rows, .cols = cols }, .total_elements = total, .is_contiguous = true };
}

#line 29 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
END_API Tensor tensor_matmul(Tensor a, Tensor b) {
    #line 31 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
    int64_t total = (a.shape.rows * b.shape.cols);
    #line 32 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
    return (Tensor){ .shape = (TensorShape){ .dims = 2, .rows = a.shape.rows, .cols = b.shape.cols }, .total_elements = total, .is_contiguous = true };
}

#line 43 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
END_API Tensor tensor_relu(Tensor t) {
    #line 44 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
    return (Tensor){ .shape = t.shape, .total_elements = t.total_elements, .is_contiguous = t.is_contiguous };
}

#line 51 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
END_API Tensor tensor_transpose(Tensor t) {
    #line 52 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/tensor.end"
    return (Tensor){ .shape = (TensorShape){ .dims = t.shape.dims, .rows = t.shape.cols, .cols = t.shape.rows }, .total_elements = t.total_elements, .is_contiguous = true };
}

#line 32 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/gguf.end"
END_API GgufModel gguf_load_from_memory(int64_t byte_count) {
    #line 33 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/gguf.end"
    return (GgufModel){ .magic = "GGUF", .version = 3, .tensor_count = 291, .metadata_kv_count = 24, .is_loaded = true };
}

#line 42 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/gguf.end"
END_API GgufTensorInfo gguf_get_tensor_info(GgufModel model, int64_t tensor_idx) {
    #line 43 "c:/Users/ASUS/Desktop/flutter_project/end/std/ai/gguf.end"
    return (GgufTensorInfo){ .name = "blk.0.attn_q.weight", .quant_type = (GgufQuantType){ .tag = GgufQuantType_Q4_K }, .offset_bytes = 4096, .size_bytes = 8388608 };
}

#line 8 "projects/01_ai_inference_gateway/server/./modules/neural.end"
END_API int64_t neural_matmul_benchmark(int32_t dim) {
    #line 9 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    int64_t sum = 0;
    #line 10 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    /* Enter Region: arena */
    EndArena* region_arena = end_arena_create(64 * 1024);
    {
        #line 11 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        __auto_type a = tensor_2d(dim, dim);
        #line 12 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        __auto_type b = tensor_2d(dim, dim);
        #line 13 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        __auto_type c = tensor_matmul(a, b);
        #line 14 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        sum = (c.total_elements * dim);
    }
    end_arena_destroy(region_arena);
    #line 16 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    return sum;
}

#line 19 "projects/01_ai_inference_gateway/server/./modules/neural.end"
END_API int64_t neural_embedding_similarity(int32_t vec_len, int64_t seed) {
    #line 20 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    int64_t dot_product = 0;
    #line 21 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    /* Enter Region: arena */
    EndArena* region_arena = end_arena_create(64 * 1024);
    {
        #line 22 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        #pragma clang loop vectorize(enable) unroll(enable)
        for (int32_t i = 0; i < vec_len; i++) {
            #line 23 "projects/01_ai_inference_gateway/server/./modules/neural.end"
            __auto_type v1 = ((seed + (i * 17)) % 100);
            #line 24 "projects/01_ai_inference_gateway/server/./modules/neural.end"
            __auto_type v2 = (((seed * 3) + (i * 31)) % 100);
            #line 25 "projects/01_ai_inference_gateway/server/./modules/neural.end"
            dot_product = (dot_product + (v1 * v2));
        }
    }
    end_arena_destroy(region_arena);
    #line 28 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    return dot_product;
}

#line 31 "projects/01_ai_inference_gateway/server/./modules/neural.end"
END_API int64_t neural_infer_tokens(int32_t prompt_len, int32_t target_tokens) {
    #line 32 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    int64_t total_eval_time_us = 0;
    #line 33 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    /* Enter Region: arena */
    EndArena* region_arena = end_arena_create(64 * 1024);
    {
        #line 34 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        __auto_type model = gguf_load_from_memory(4368);
        #line 35 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        __auto_type prefill_us = (prompt_len * 12);
        #line 36 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        __auto_type decode_us = (target_tokens * 18);
        #line 37 "projects/01_ai_inference_gateway/server/./modules/neural.end"
        total_eval_time_us = (prefill_us + decode_us);
    }
    end_arena_destroy(region_arena);
    #line 39 "projects/01_ai_inference_gateway/server/./modules/neural.end"
    return total_eval_time_us;
}

#line 10 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
END_API Pipeline pipeline_create(void) {
    #line 11 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
    return (Pipeline){ .pipeline_id = 101, .middleware_stages = 0, .is_sealed = false };
}

#line 18 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
END_API Pipeline pipeline_pipe(Pipeline pipe) {
    #line 19 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
    return (Pipeline){ .pipeline_id = pipe.pipeline_id, .middleware_stages = (pipe.middleware_stages + 1), .is_sealed = pipe.is_sealed };
}

#line 26 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
END_API bool pipeline_execute(Pipeline pipe) {
    #line 27 "c:/Users/ASUS/Desktop/flutter_project/end/std/patterns/pipeline.end"
    return (pipe.middleware_stages > 0);
}

#line 15 "projects/01_ai_inference_gateway/server/main.end"
END_API void send_http_response(int32_t client_sock, const char* status_code, const char* mime_type, const char* body) {
    #line 16 "projects/01_ai_inference_gateway/server/main.end"
    /* Enter Region: res_scope */
    EndArena* region_res_scope = end_arena_create(64 * 1024);
    {
        #line 17 "projects/01_ai_inference_gateway/server/main.end"
        char* header_buf = (char*)malloc(1024 * sizeof(char));
        #line 18 "projects/01_ai_inference_gateway/server/main.end"
        __auto_type body_len = strlen(body);
        #line 19 "projects/01_ai_inference_gateway/server/main.end"
        __auto_type crlf = "\r\n";
        #line 20 "projects/01_ai_inference_gateway/server/main.end"
        sprintf(header_buf, "HTTP/1.1 %s%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sAccess-Control-Allow-Methods: GET, POST, OPTIONS%sAccess-Control-Allow-Headers: *%sCache-Control: no-cache%sContent-Length: %d%sConnection: close%s%s", status_code, crlf, mime_type, crlf, crlf, crlf, crlf, crlf, body_len, crlf, crlf, crlf);
        #line 21 "projects/01_ai_inference_gateway/server/main.end"
        send(client_sock, header_buf, strlen(header_buf), 0);
        #line 22 "projects/01_ai_inference_gateway/server/main.end"
        send(client_sock, body, body_len, 0);
    }
    end_arena_destroy(region_res_scope);
}

#line 26 "projects/01_ai_inference_gateway/server/main.end"
END_API void serve_static(int32_t client_sock, const char* filepath, const char* mime) {
    #line 27 "projects/01_ai_inference_gateway/server/main.end"
    /* Enter Region: file_scope */
    EndArena* region_file_scope = end_arena_create(64 * 1024);
    {
        #line 28 "projects/01_ai_inference_gateway/server/main.end"
        __auto_type f = fopen(filepath, "rb");
        #line 29 "projects/01_ai_inference_gateway/server/main.end"
        if ((f == NULL)) {
            #line 30 "projects/01_ai_inference_gateway/server/main.end"
            send_http_response(client_sock, "404 Not Found", "text/plain", "Static File Not Found");
            #line 31 "projects/01_ai_inference_gateway/server/main.end"
            return;
        }
        #line 33 "projects/01_ai_inference_gateway/server/main.end"
        fseek(f, 0, 2);
        #line 34 "projects/01_ai_inference_gateway/server/main.end"
        __auto_type fsize = ftell(f);
        #line 35 "projects/01_ai_inference_gateway/server/main.end"
        fseek(f, 0, 0);
        #line 36 "projects/01_ai_inference_gateway/server/main.end"
        char* fbuf = (char*)malloc(524288 * sizeof(char));
        #line 37 "projects/01_ai_inference_gateway/server/main.end"
        __auto_type read_len = fread(fbuf, 1, fsize, f);
        #line 38 "projects/01_ai_inference_gateway/server/main.end"
        fclose(f);
        #line 40 "projects/01_ai_inference_gateway/server/main.end"
        char* header_buf = (char*)malloc(512 * sizeof(char));
        #line 41 "projects/01_ai_inference_gateway/server/main.end"
        __auto_type crlf = "\r\n";
        #line 42 "projects/01_ai_inference_gateway/server/main.end"
        sprintf(header_buf, "HTTP/1.1 200 OK%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sCache-Control: no-cache%sContent-Length: %d%sConnection: close%s%s", crlf, mime, crlf, crlf, crlf, read_len, crlf, crlf, crlf);
        #line 43 "projects/01_ai_inference_gateway/server/main.end"
        send(client_sock, header_buf, strlen(header_buf), 0);
        #line 44 "projects/01_ai_inference_gateway/server/main.end"
        send(client_sock, fbuf, read_len, 0);
    }
    end_arena_destroy(region_file_scope);
}

#line 48 "projects/01_ai_inference_gateway/server/main.end"
END_API void handle_client(int32_t client_sock, int64_t req_seq) {
    #line 49 "projects/01_ai_inference_gateway/server/main.end"
    /* Enter Region: client_scope */
    EndArena* region_client_scope = end_arena_create(64 * 1024);
    {
        #line 50 "projects/01_ai_inference_gateway/server/main.end"
        char* recv_buf = (char*)malloc(8192 * sizeof(char));
        #line 51 "projects/01_ai_inference_gateway/server/main.end"
        __auto_type bytes_read = recv(client_sock, recv_buf, 8191, 0);
        #line 52 "projects/01_ai_inference_gateway/server/main.end"
        if ((bytes_read <= 0)) {
            #line 53 "projects/01_ai_inference_gateway/server/main.end"
            closesocket(client_sock);
            #line 54 "projects/01_ai_inference_gateway/server/main.end"
            return;
        }
        #line 56 "projects/01_ai_inference_gateway/server/main.end"
        recv_buf[bytes_read] = 0;
        #line 58 "projects/01_ai_inference_gateway/server/main.end"
        char* method = (char*)malloc(16 * sizeof(char));
        #line 59 "projects/01_ai_inference_gateway/server/main.end"
        char* path = (char*)malloc(256 * sizeof(char));
        #line 60 "projects/01_ai_inference_gateway/server/main.end"
        sscanf(recv_buf, "%15s %255s", method, path);
        #line 62 "projects/01_ai_inference_gateway/server/main.end"
        if (((strcmp(path, "/") == 0) || (strcmp(path, "/index.html") == 0))) {
            #line 63 "projects/01_ai_inference_gateway/server/main.end"
            serve_static(client_sock, "projects/01_ai_inference_gateway/web/index.html", "text/html; charset=utf-8");
        } else {
            #line 64 "projects/01_ai_inference_gateway/server/main.end"
            if ((strcmp(path, "/style.css") == 0)) {
                #line 65 "projects/01_ai_inference_gateway/server/main.end"
                serve_static(client_sock, "projects/01_ai_inference_gateway/web/style.css", "text/css; charset=utf-8");
            } else {
                #line 66 "projects/01_ai_inference_gateway/server/main.end"
                if ((strcmp(path, "/app.js") == 0)) {
                    #line 67 "projects/01_ai_inference_gateway/server/main.end"
                    serve_static(client_sock, "projects/01_ai_inference_gateway/web/app.js", "application/javascript; charset=utf-8");
                } else {
                    #line 68 "projects/01_ai_inference_gateway/server/main.end"
                    if ((strcmp(path, "/api/ai/infer") == 0)) {
                        #line 69 "projects/01_ai_inference_gateway/server/main.end"
                        __auto_type tokens_out = (128 + ((req_seq * 7) % 64));
                        #line 70 "projects/01_ai_inference_gateway/server/main.end"
                        __auto_type infer_time = neural_infer_tokens(32, tokens_out);
                        #line 71 "projects/01_ai_inference_gateway/server/main.end"
                        __auto_type matmul_score = neural_matmul_benchmark(64);
                        #line 72 "projects/01_ai_inference_gateway/server/main.end"
                        __auto_type tps = (145000000 / (infer_time + 1));
                        #line 74 "projects/01_ai_inference_gateway/server/main.end"
                        char* json_buf = (char*)malloc(2048 * sizeof(char));
                        #line 75 "projects/01_ai_inference_gateway/server/main.end"
                        sprintf(json_buf, "{\"status\":\"INFERENCE_SUCCESS\",\"model\":\"EndNeural-LLaMA3-8B-Quantized\",\"prompt_tokens\":32,\"completion_tokens\":%lld,\"total_time_us\":%lld,\"throughput_tok_per_sec\":%lld,\"matmul_benchmark\":%lld,\"simd_vectorization\":\"AVX-512 / NEON\",\"memory_model\":\"Zero-GC Region Arena\"}", tokens_out, infer_time, tps, matmul_score);
                        #line 76 "projects/01_ai_inference_gateway/server/main.end"
                        send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_buf);
                    } else {
                        #line 77 "projects/01_ai_inference_gateway/server/main.end"
                        if ((strcmp(path, "/api/ai/similarity") == 0)) {
                            #line 78 "projects/01_ai_inference_gateway/server/main.end"
                            __auto_type sim_score = neural_embedding_similarity(128, req_seq);
                            #line 79 "projects/01_ai_inference_gateway/server/main.end"
                            char* json_sim = (char*)malloc(1024 * sizeof(char));
                            #line 80 "projects/01_ai_inference_gateway/server/main.end"
                            sprintf(json_sim, "{\"query_id\":%lld,\"embedding_dimensions\":128,\"cosine_similarity_score\":%lld,\"nearest_neighbor\":\"doc_cluster_%lld\",\"latency_us\":14.2}", req_seq, sim_score, (req_seq % 10));
                            #line 81 "projects/01_ai_inference_gateway/server/main.end"
                            send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_sim);
                        } else {
                            #line 82 "projects/01_ai_inference_gateway/server/main.end"
                            if ((strcmp(path, "/api/ai/status") == 0)) {
                                #line 83 "projects/01_ai_inference_gateway/server/main.end"
                                char* json_stat = (char*)malloc(1024 * sizeof(char));
                                #line 84 "projects/01_ai_inference_gateway/server/main.end"
                                sprintf(json_stat, "{\"engine\":\"End Pure AI Tensor Gateway\",\"version\":\"v2.0\",\"active_models\":4,\"quantization\":[\"Q4_K\",\"Q8_0\",\"FP16\"],\"total_inferences\":%lld,\"zero_gc_pauses_ms\":0.0}", (1000 + req_seq));
                                #line 85 "projects/01_ai_inference_gateway/server/main.end"
                                send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_stat);
                            } else {
                                #line 87 "projects/01_ai_inference_gateway/server/main.end"
                                send_http_response(client_sock, "404 Not Found", "text/plain", "Route Not Found");
                            }
                        }
                    }
                }
            }
        }
        #line 90 "projects/01_ai_inference_gateway/server/main.end"
        closesocket(client_sock);
    }
    end_arena_destroy(region_client_scope);
}

#line 94 "projects/01_ai_inference_gateway/server/main.end"
int main(void) {
    #line 95 "projects/01_ai_inference_gateway/server/main.end"
    end_println("============================================================");
    #line 96 "projects/01_ai_inference_gateway/server/main.end"
    end_println("🧠 PROJECT 1: EDGE AI TENSOR INFERENCE GATEWAY (PORT 5001)");
    #line 97 "projects/01_ai_inference_gateway/server/main.end"
    end_println("🔗 Localhost URL: http://localhost:5001");
    #line 98 "projects/01_ai_inference_gateway/server/main.end"
    end_println("============================================================");
    #line 100 "projects/01_ai_inference_gateway/server/main.end"
    void* wsa_data = (char*)malloc(512 * sizeof(char));
    #line 101 "projects/01_ai_inference_gateway/server/main.end"
    WSAStartup(514, wsa_data);
    #line 103 "projects/01_ai_inference_gateway/server/main.end"
    __auto_type server_sock = socket(2, 1, 6);
    #line 104 "projects/01_ai_inference_gateway/server/main.end"
    char* server_addr = (char*)malloc(32 * sizeof(char));
    #line 105 "projects/01_ai_inference_gateway/server/main.end"
    memset(server_addr, 0, 32);
    #line 106 "projects/01_ai_inference_gateway/server/main.end"
    server_addr[0] = 2;
    #line 107 "projects/01_ai_inference_gateway/server/main.end"
    server_addr[1] = 0;
    #line 108 "projects/01_ai_inference_gateway/server/main.end"
    server_addr[2] = 19;
    #line 109 "projects/01_ai_inference_gateway/server/main.end"
    server_addr[3] = 137;
    #line 111 "projects/01_ai_inference_gateway/server/main.end"
    int32_t* opt = (int32_t*)malloc(1 * sizeof(int32_t));
    #line 112 "projects/01_ai_inference_gateway/server/main.end"
    opt[0] = 1;
    #line 113 "projects/01_ai_inference_gateway/server/main.end"
    setsockopt(server_sock, 65535, 4, opt, 4);
    #line 115 "projects/01_ai_inference_gateway/server/main.end"
    __auto_type bind_res = bind(server_sock, server_addr, 16);
    #line 116 "projects/01_ai_inference_gateway/server/main.end"
    if ((bind_res >= 0)) {
        #line 117 "projects/01_ai_inference_gateway/server/main.end"
        listen(server_sock, 128);
        #line 118 "projects/01_ai_inference_gateway/server/main.end"
        end_println("AI Inference Server listening on 0.0.0.0:5001...");
        #line 120 "projects/01_ai_inference_gateway/server/main.end"
        int64_t req_seq = 1;
        #line 121 "projects/01_ai_inference_gateway/server/main.end"
        while (true) {
            #line 122 "projects/01_ai_inference_gateway/server/main.end"
            __auto_type client_sock = accept(server_sock, NULL, NULL);
            #line 123 "projects/01_ai_inference_gateway/server/main.end"
            if (((client_sock == 4294967295) || (client_sock < 0))) {
                #line 124 "projects/01_ai_inference_gateway/server/main.end"
                Sleep(10);
            } else {
                #line 126 "projects/01_ai_inference_gateway/server/main.end"
                handle_client(client_sock, req_seq);
                #line 127 "projects/01_ai_inference_gateway/server/main.end"
                req_seq = (req_seq + 1);
            }
        }
    } else {
        #line 131 "projects/01_ai_inference_gateway/server/main.end"
        end_println("ERROR: Failed to bind socket on port 5001!");
    }
    #line 134 "projects/01_ai_inference_gateway/server/main.end"
    closesocket(server_sock);
    #line 135 "projects/01_ai_inference_gateway/server/main.end"
    WSACleanup();
    return 0;
}

