use crate::ast::span::Span;
use super::statement::Statement;

impl Statement {
    pub fn span(&self) -> &Span {
        match self {
            Statement::VarDecl { span, .. } => span,
            Statement::Assignment { span, .. } => span,
            Statement::Return { span, .. } => span,
            Statement::Expression(expr) => expr.span(),
            Statement::If { span, .. } => span,
            Statement::Guard { span, .. } => span,
            Statement::While { span, .. } => span,
            Statement::ForIn { span, .. } => span,
            Statement::ParallelFor { span, .. } => span,
            Statement::Match { span, .. } => span,
            Statement::RegionBlock { span, .. } => span,
            Statement::AsmBlock { span, .. } => span,
            Statement::TargetBlock { span, .. } => span,
            Statement::Defer { span, .. } => span,
            Statement::Spawn { span, .. } => span,
            Statement::Skip { span, .. } => span,
            Statement::InlineC { span, .. } => span,
            Statement::LeaseBlock { span, .. } => span,
            Statement::LeaseCpu { span, .. } => span,
            Statement::LeaseEvent { span, .. } => span,
            Statement::LeaseLoop { span, .. } => span,
            Statement::QuantumUnwrap { span, .. } => span,
            Statement::AtomicOp { span, .. } => span,
            Statement::Intent { span, .. } => span,
            Statement::Prove { span, .. } => span,
            Statement::Assume { span, .. } => span,
            Statement::Guarantee { span, .. } => span,
            Statement::Invariant { span, .. } => span,
            Statement::Because { span, .. } => span,
            Statement::Why { span, .. } => span,
            Statement::IntentDiff { span, .. } => span,
            Statement::ProtectBlock { span, .. } => span,
            Statement::Frozen { span, .. } => span,
            Statement::MutableBy { span, .. } => span,
            Statement::Owned { span, .. } => span,
            Statement::Handoff { span, .. } => span,
            Statement::ReturnTo { span, .. } => span,
            Statement::ComputeBlock { span, .. } => span,
            Statement::RaceFreeBlock { span, .. } => span,
            Statement::Order { span, .. } => span,
            Statement::DeterministicBlock { span, .. } => span,
            Statement::ReplayBlock { span, .. } => span,
            Statement::Checkpoint { span, .. } => span,
            Statement::Rollback { span, .. } => span,
            Statement::TransactionBlock { span, .. } => span,
            Statement::SpeculativeBlock { span, .. } => span,
            Statement::FallbackBlock { span, .. } => span,
            Statement::BudgetBlock { span, .. } => span,
            Statement::DeadlineBlock { span, .. } => span,
            Statement::PriorityBlock { span, .. } => span,
            Statement::QualityBlock { span, .. } => span,
            Statement::TradeoffBlock { span, .. } => span,
            Statement::AdaptBlock { span, .. } => span,
            Statement::Observe { span, .. } => span,
            Statement::WatchBlock { span, .. } => span,
            Statement::ReactBlock { span, .. } => span,
            Statement::StreamBlock { span, .. } => span,
            Statement::FlowBlock { span, .. } => span,
            Statement::ParallelChoose { span, .. } => span,
            Statement::RaceBlock { span, .. } => span,
            Statement::HedgeBlock { span, .. } => span,
            Statement::CancelSafeBlock { span, .. } => span,
            Statement::AgentContract { span, .. } => span,
            Statement::TaskDecl { span, .. } => span,
            Statement::AcceptBlock { span, .. } => span,
            Statement::RejectBlock { span, .. } => span,
            Statement::BaselineBlock { span, .. } => span,
            Statement::RegressionCheck { span, .. } => span,
            Statement::ExplainBlock { span, .. } => span,
            Statement::ContextBlock { span, .. } => span,
            Statement::SliceDecl { span, .. } => span,
            Statement::PatchDecl { span, .. } => span,
            Statement::EvolveBlock { span, .. } => span,
            Statement::VerifyBlock { span, .. } => span,
            Statement::BoundaryDecl { span, .. } => span,
            Statement::ResponsibilityDecl { span, .. } => span,
            Statement::OwnsDecl { span, .. } => span,
            Statement::ExposesDecl { span, .. } => span,
            Statement::DependsDecl { span, .. } => span,
            Statement::ForbidDecl { span, .. } => span,
            Statement::LayerDecl { span, .. } => span,
            Statement::DirectionDecl { span, .. } => span,
            Statement::SplitDecl { span, .. } => span,
            Statement::PartitionDecl { span, .. } => span,
            Statement::ExtractDecl { span, .. } => span,
            Statement::ClusterDecl { span, .. } => span,
            Statement::SeparateDecl { span, .. } => span,
            Statement::ModuleContractDecl { span, .. } => span,
            Statement::PortDecl { span, .. } => span,
            Statement::AdapterDecl { span, .. } => span,
            Statement::FacadeDecl { span, .. } => span,
            Statement::GatewayDecl { span, .. } => span,
            Statement::ArchInvariantDecl { span, .. } => span,
            Statement::PreserveRefactorDecl { span, .. } => span,
            Statement::CompatDecl { span, .. } => span,
            Statement::StableDecl { span, .. } => span,
            Statement::SealedDecl { span, .. } => span,
            Statement::FriendDecl { span, .. } => span,
            Statement::PrivateToDecl { span, .. } => span,
            Statement::SurfaceDecl { span, .. } => span,
            Statement::LeakCheckDecl { span, .. } => span,
            Statement::PurityDecl { span, .. } => span,
            Statement::ViewDecl { span, .. } => span,
            Statement::LensDecl { span, .. } => span,
            Statement::AgentScopeDecl { span, .. } => span,
            Statement::BudgetContextDecl { span, .. } => span,
            Statement::MoveDecl { span, .. } => span,
            Statement::MigrateDecl { span, .. } => span,
            Statement::BridgeDecl { span, .. } => span,
            Statement::RedirectDecl { span, .. } => span,
            Statement::DeprecateDecl { span, .. } => span,
            Statement::CycleFreeDecl { span, .. } => span,
            Statement::FanoutDecl { span, .. } => span,
            Statement::FaninDecl { span, .. } => span,
            Statement::DepthDecl { span, .. } => span,
            Statement::CohesionDecl { span, .. } => span,
            Statement::ModularizeDecl { span, .. } => span,
            Statement::DecomposeDecl { span, .. } => span,
            Statement::ArchitectureDecl { span, .. } => span,
            Statement::RepairDecl { span, .. } => span,
            Statement::EvolveArchDecl { span, .. } => span,
            Statement::GravityDecl { span, .. } => span,
            Statement::OperationDecl(op) => &op.span,
            Statement::EventDecl(ev) => &ev.span,
            Statement::EventHubDecl(hub) => &hub.span,
            Statement::EmitEvent { span, .. } => span,
            Statement::ObserveOp { span, .. } => span,
            Statement::AnalyzeOp { span, .. } => span,
            Statement::ExtractOpDecl { span, .. } => span,
            Statement::InlineOpDecl { span, .. } => span,
            Statement::SplitOpDecl { span, .. } => span,
            Statement::MergeOpDecl { span, .. } => span,
            Statement::ExplainOpDecl { span, .. } => span,
            Statement::EvolveOpDecl { span, .. } => span,
            Statement::FeatureDecl { span, .. } => span,
            Statement::SkillDecl { span, .. } => span,
            Statement::SatisfiesDecl { span, .. } => span,
            Statement::ProjectSkillsDecl { span, .. } => span,
            Statement::AgentTaskContractDecl { span, .. } => span,
            Statement::ClaimTask { span, .. } => span,
            Statement::CompleteTask { span, .. } => span,
            Statement::VerifyTask { span, .. } => span,
            Statement::RequirementDecl { span, .. } => span,
            Statement::ImplementsDecl { span, .. } => span,
            Statement::VerifiesDecl { span, .. } => span,
            Statement::TodoDecl { span, .. } => span,
            Statement::AgentBoundaryDecl { span, .. } => span,
            Statement::AgentContextDecl { span, .. } => span,
            Statement::ContextFirewallDecl { span, .. } => span,
            Statement::AgentApiDecl { span, .. } => span,
            Statement::AgentabilityDecl { span, .. } => span,
            Statement::IntentDecl { span, .. } => span,
            Statement::SemanticCommitDecl { span, .. } => span,
            Statement::AgentReviewDecl { span, .. } => span,
            Statement::ApprovalDecl { span, .. } => span,
            Statement::AgentLeaseDecl { span, .. } => span,
            Statement::KnowledgeDecl { span, .. } => span,
            Statement::DecisionDecl { span, .. } => span,
            Statement::AgentCapabilityDecl { span, .. } => span,
            Statement::RegressionGuardDecl { span, .. } => span,

            // Layer 1
            Statement::PartialDecl { span, .. } => span,
            Statement::AugmentDecl(aug) => &aug.span,
            Statement::OverrideDecl { span, .. } => span,
            Statement::ExtensionPointDecl { span, .. } => span,
            Statement::LayerSealedDecl { span, .. } => span,
            Statement::LayerFriendDecl { span, .. } => span,

            // Layer 2
            Statement::ReplaceModuleDecl { span, .. } => span,
            Statement::ModuleMigrationDecl { span, .. } => span,
            Statement::ModuleFacadeDecl { span, .. } => span,
            Statement::ModuleOverlayDecl { span, .. } => span,
            Statement::ModuleComposeDecl { span, .. } => span,

            // Layer 3
            Statement::OpenClosedTypeDecl { span, .. } => span,
            Statement::ExtensionTraitDecl { span, .. } => span,
            Statement::ExtensionConflictDecl { span, .. } => span,

            // Layer 4
            Statement::SyntaxDecl { span, .. } => span,
            Statement::UseSyntaxDecl { span, .. } => span,

            // Layer 5
            Statement::CompilerPluginDecl { span, .. } => span,
            Statement::CustomLinterDecl { span, .. } => span,
            Statement::CustomAnalyzerDecl { span, .. } => span,
            Statement::CustomTypeRuleDecl { span, .. } => span,
            Statement::CustomOptimizerDecl { span, .. } => span,
            Statement::BuildPluginDecl { span, .. } => span,
            Statement::GeneratorDecl { span, .. } => span,
            Statement::ReflectDecl { span, .. } => span,

            // Layer 6
            Statement::ArchitectureContractDecl { span, .. } => span,
            Statement::ForbiddenDependencyDecl { span, .. } => span,
            Statement::AllowedDependencyDecl { span, .. } => span,
            Statement::ArchitectureBoundaryDecl { span, .. } => span,
            Statement::ArchitectureOwnerDecl { span, .. } => span,
            Statement::ArchitectureStabilityDecl { span, .. } => span,
            Statement::ArchitectureEvolutionDecl { span, .. } => span,
            Statement::ArchitectureTestDecl { span, .. } => span,

            // Layer 7
            Statement::ChangeBudgetDecl { span, .. } => span,
            Statement::DependencyLockDecl { span, .. } => span,
            Statement::SemanticImportDecl { span, .. } => span,

            // Layer 8
            Statement::ApiStabilityDecl { span, .. } => span,
            Statement::DeprecationDecl { span, .. } => span,
            Statement::ApiSnapshotDecl { span, .. } => span,
            Statement::VerifyCompatibilityDecl { span, .. } => span,

            // Layer 9
            Statement::AgentExtensionContractDecl { span, .. } => span,
            Statement::AgentChangeProposalDecl { span, .. } => span,
            Statement::AgentProofGateDecl { span, .. } => span,
            Statement::AgentTransactionDecl { span, .. } => span,

            // Layer 10
            Statement::WhyMetadataDecl { span, .. } => span,
            Statement::EvolvableDecl { span, .. } => span,

            // Feature-Oriented Paradigms
            Statement::FeatureStatement(f) => &f.span,
            Statement::ContractDefinition(c) => &c.span,
            Statement::ArchitectureTemplate(a) => &a.span,
            Statement::ArchitectureRuleStatement(r) => &r.span,
            Statement::FeatureMigrationStatement(m) => &m.span,
            Statement::ReplaceFeature { span, .. } => span,
            Statement::DecorateFeature { span, .. } => span,
            Statement::ComposeFeature { span, .. } => span,
            Statement::EvolveFeature { span, .. } => span,
            Statement::EvolveContract { span, .. } => span,
            Statement::ImpactQuery { span, .. } => span,
            Statement::UseFeature { span, .. } => span,

            // Capability & Surface Composition
            Statement::UseSurface { span, .. } => span,
            Statement::AccessCapability { span, .. } => span,
            Statement::GrantCapability { span, .. } => span,
            Statement::DenyCapability { span, .. } => span,
            Statement::SurfaceDefinition(s) => &s.span,
            Statement::AdoptContract { span, .. } => span,
            Statement::ImplementContract { span, .. } => span,
            Statement::AttachCapability { span, .. } => span,
            Statement::DetachCapability { span, .. } => span,
            Statement::ComposeCapability { span, .. } => span,
            Statement::MixinDecl(m) => &m.span,
            Statement::CapabilityDecl(c) => &c.span,
            Statement::ProvideCapability { span, .. } => span,
            Statement::RequireCapability { span, .. } => span,
            Statement::ResolveContract { span, .. } => span,
            Statement::SelectContract { span, .. } => span,
            Statement::ViewProjection { span, .. } => span,
            Statement::ProjectSurface { span, .. } => span,
            Statement::DelegateBehavior { span, .. } => span,
            Statement::ProxyCapability { span, .. } => span,
            Statement::DecorateEntity { span, .. } => span,
            Statement::InterceptMethod(i) => &i.span,
            Statement::HookEvent(h) => &h.span,
            Statement::EnableCapability { span, .. } => span,
            Statement::ScopeBoundary(s) => &s.span,
            Statement::ContextEnv(c) => &c.span,
            Statement::FeatureSwitchDecl { span, .. } => span,
            Statement::TraitifyCheck { span, .. } => span,
            Statement::EquipEntity { span, .. } => span,
            Statement::FuseFeatures { span, .. } => span,
            Statement::ShapeDefinition(s) => &s.span,
            Statement::DestructureAssign { span, .. } => span,
            Statement::ExtendDecl { span, .. } => span,
            Statement::LocalFunction(f) => &f.span,
            Statement::FeaturePolicyDecl { span, .. } => span,
            Statement::OnEventStmt(e) => &e.span,
            Statement::OnceEventStmt(e) => &e.span,
            Statement::EveryEventStmt(e) => &e.span,
            Statement::AfterEventStmt(e) => &e.span,
            Statement::BeforeEventStmt(e) => &e.span,
            Statement::ReactiveStateStmt(e) => &e.span,
            Statement::DeriveStmt(e) => &e.span,
            Statement::TopologyStmt(e) => &e.span,
            Statement::EventStreamOpStmt(e) => &e.span,
            Statement::EventTransactionStmt(e) => &e.span,
            Statement::EventFormalInvariantStmt(e) => &e.span,
            Statement::EventEvolveStmt(e) => &e.span,
            Statement::EventControlStmt(e) => &e.span,
            Statement::ClassDecl(c) => &c.span,
            Statement::TraitDecl(t) => &t.span,
            Statement::InheritStmt(i) => &i.span,
            Statement::SuperCallStmt(s) => &s.span,
            Statement::ConflictStmt(c) => &c.span,
            Statement::ResolveConflictStmt(r) => &r.span,
            Statement::InspectInheritanceStmt(i) => &i.span,
            Statement::ImpactInheritanceStmt(i) => &i.span,
        }
    }
}

