use serde::{Deserialize, Serialize};
use crate::ast::span::Span;
use crate::ast::types::Type;
use crate::ast::operators::BinaryOp;
use crate::ast::pattern::{Block, MatchArm};
use crate::ast::expr::Expression;
use crate::ast::decl::architecture::{ArchitectureRuleDef, ArchitectureTemplateDef, ContractDef, FeatureMigrationDef};
use crate::ast::decl::capabilities::*;
use crate::ast::decl::events::{EventDef, EventHubDef, ExtensionBlock, OperationDef};
use crate::ast::decl::features::FeatureDef;
use crate::ast::decl::functions_traits::{FunctionDef, FunctionParam, TraitMethodDef};
use crate::ast::decl::modules::ModuleDef;
use crate::ast::decl::structs_enums::StructDef;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Statement {
    VarDecl {
        name: String,
        var_type: Option<Type>,
        is_mut: bool,
        is_lease: bool,
        initializer: Option<Expression>,
        span: Span,
    },
    Assignment { target: Expression, value: Expression, span: Span, },
    Return { value: Option<Expression>, span: Span, },
    Expression(Expression),
    If { condition: Expression, then_block: Block, else_block: Option<Block>, span: Span, },
    While { condition: Expression, body: Block, span: Span, },
    ForIn { item_name: String, iterable: Expression, body: Block, span: Span, },
    ParallelFor { item_name: String, iterable: Expression, body: Block, span: Span, },
    Match { expr: Expression, arms: Vec<MatchArm>, span: Span, },
    RegionBlock { name: String, body: Block, span: Span, },
    AsmBlock { arch: String, code: String, span: Span, },
    TargetBlock { target: String, body: Block, span: Span, },
    Defer { expr: Expression, span: Span, },
    Spawn { call: Expression, span: Span, },
    Skip { span: Span, },
    InlineC { code: String, span: Span, },
    LeaseBlock {
        name: String,
        var_type: Option<Type>,
        initializer: Expression,
        condition: Option<Expression>,
        body: Block,
        span: Span,
    },
    LeaseCpu { cores: Expression, priority: Option<Expression>, body: Block, span: Span, },
    LeaseEvent { event_expr: Expression, condition: Option<Expression>, body: Block, span: Span, },
    LeaseLoop { budget: Option<Expression>, item_name: String, iterable: Expression, body: Block, span: Span, },
    QuantumUnwrap { name: String, var_type: Option<Type>, expr: Expression, fallback: Expression, span: Span, },
    AtomicOp { target: String, op: BinaryOp, value: Expression, span: Span, },
    // ── 50 Next-Gen & AI-Native Semantics AST Variants ──
    Intent { name: Option<String>, goal: String, preserve: Vec<String>, body: Option<Block>, span: Span, },
    Prove { condition: Expression, span: Span, },
    Assume { condition: Expression, span: Span, },
    Guarantee { condition: Expression, span: Span, },
    Invariant { condition: Expression, span: Span, },
    Because { rationale: String, span: Span, },
    Why { target: String, rationale: String, span: Span, },
    IntentDiff { preserve: Vec<String>, change: Vec<String>, span: Span, },
    ProtectBlock { body: Block, span: Span, },
    Frozen { symbol: String, span: Span, },
    MutableBy { roles: Vec<String>, span: Span, },
    Owned { name: String, var_type: Option<Type>, initializer: Expression, span: Span, },
    Handoff { resource: String, target_domain: String, span: Span, },
    ReturnTo { source_domain: String, resource: String, span: Span, },
    ComputeBlock { target: String, body: Block, fallback: Option<Block>, span: Span, },
    RaceFreeBlock { body: Block, span: Span, },
    Order { mode: String, span: Span, },
    DeterministicBlock { body: Block, span: Span, },
    ReplayBlock { body: Block, span: Span, },
    Checkpoint { state_name: String, span: Span, },
    Rollback { checkpoint_name: String, span: Span, },
    TransactionBlock { body: Block, span: Span, },
    SpeculativeBlock { body: Block, span: Span, },
    FallbackBlock { target: String, body: Block, span: Span, },
    BudgetBlock { specs: Vec<(String, String)>, body: Option<Block>, span: Span, },
    DeadlineBlock { duration: String, body: Block, span: Span, },
    PriorityBlock { level: String, body: Block, span: Span, },
    QualityBlock { min_metric: String, max_latency: String, body: Block, span: Span, },
    TradeoffBlock { prefer: String, sacrifice: String, body: Block, span: Span, },
    AdaptBlock { branches: Vec<(Expression, Block)>, span: Span, },
    Observe { metrics: Vec<String>, span: Span, },
    WatchBlock { target: String, event: String, handler: Block, span: Span, },
    ReactBlock { event: Expression, handler: Block, span: Span, },
    StreamBlock { source: Expression, operations: Vec<Expression>, span: Span, },
    FlowBlock { steps: Vec<Expression>, span: Span, },
    ParallelChoose { branches: Vec<(String, Block)>, span: Span, },
    RaceBlock { branches: Vec<Block>, span: Span, },
    HedgeBlock { delay_ms: Expression, primary: Block, fallback: Block, span: Span, },
    CancelSafeBlock { body: Block, span: Span, },
    AgentContract {
        name: String,
        scope: String,
        goal: String,
        constraints: Vec<String>,
        body: Option<Block>,
        span: Span,
    },
    TaskDecl { name: String, body: Block, span: Span, },
    AcceptBlock { conditions: Vec<String>, span: Span, },
    RejectBlock { conditions: Vec<String>, span: Span, },
    BaselineBlock { metrics: Vec<(String, String)>, span: Span, },
    RegressionCheck { condition: String, span: Span, },
    ExplainBlock { topic: String, rationale: String, span: Span, },
    ContextBlock { name: String, includes: Vec<String>, excludes: Vec<String>, body: Option<Block>, span: Span, },
    SliceDecl { name: String, from_target: String, includes: Vec<String>, excludes: Vec<String>, span: Span, },
    PatchDecl { target: String, body: Block, span: Span, },
    EvolveBlock {
        target: String,
        intent: String,
        preserve: Vec<String>,
        budget: Option<String>,
        allow: Vec<String>,
        reject: Vec<String>,
        verify: Vec<String>,
        accept: Vec<String>,
        body: Option<Block>,
        span: Span,
    },
    VerifyBlock { invariants: Vec<Expression>, span: Span, },
    // Family 1 & 2: Architectural Units & Boundaries & Dependencies
    BoundaryDecl { name: String, allows: Vec<String>, denies: Vec<String>, is_sealed: bool, span: Span, },
    ResponsibilityDecl { module_name: String, description: String, span: Span, },
    OwnsDecl { module_name: String, symbols: Vec<String>, span: Span, },
    ExposesDecl { module_name: String, symbols: Vec<String>, span: Span, },
    DependsDecl { from_module: String, target_module: String, is_only: bool, span: Span, },
    ForbidDecl { from: String, to: String, span: Span, },
    LayerDecl { name: String, forbid_depends: Vec<String>, span: Span, },
    DirectionDecl { from: String, to: String, span: Span, },
    // Family 3: Agent-Native Decomposition
    SplitDecl { entity: String, parts: Vec<String>, span: Span, },
    PartitionDecl { entity: String, by: String, parts: Vec<String>, span: Span, },
    ExtractDecl { symbols: Vec<String>, into_module: String, span: Span, },
    ClusterDecl { by: String, predicate: String, span: Span, },
    SeparateDecl { left: String, right: String, span: Span, },
    // Family 4: Dependency Intelligence & Contracts
    ModuleContractDecl {
        module_name: String,
        accepts: Vec<String>,
        returns: Vec<String>,
        guarantees: Vec<String>,
        span: Span,
    },
    PortDecl { name: String, methods: Vec<String>, span: Span, },
    AdapterDecl { name: String, port: String, body: Block, span: Span, },
    FacadeDecl { name: String, exposes: Vec<String>, span: Span, },
    GatewayDecl { from_mod: String, to_mod: String, allowed_calls: Vec<String>, span: Span, },
    // Family 5: Architectural Invariants & Stability
    ArchInvariantDecl { rule: String, span: Span, },
    PreserveRefactorDecl { preserves: Vec<String>, body: Block, span: Span, },
    CompatDecl { module_name: String, version: String, body: Block, span: Span, },
    StableDecl { api_name: String, span: Span, },
    SealedDecl { boundary_name: String, span: Span, },
    // Family 6: Dependency Firewall & Visibility
    FriendDecl { module_name: String, friend_module: String, span: Span, },
    PrivateToDecl { symbol: String, module_name: String, span: Span, },
    SurfaceDecl { name: String, exposes: Vec<String>, hides: Vec<String>, span: Span, },
    LeakCheckDecl { module_name: String, symbol: String, through: String, span: Span, },
    PurityDecl { module_name: String, level: String, span: Span, },
    // Family 7: Agent Context Architecture
    ViewDecl { name: String, includes: Vec<String>, span: Span, },
    LensDecl { name: String, focus: String, hide: String, span: Span, },
    AgentScopeDecl { name: String, modules: Vec<String>, forbid: Vec<String>, span: Span, },
    BudgetContextDecl { name: String, token_budget: usize, priority: Vec<String>, span: Span, },
    // Family 8: Safe Refactoring
    MoveDecl { symbol: String, from_mod: String, to_mod: String, span: Span, },
    MigrateDecl { entity: String, from_mod: String, to_mod: String, span: Span, },
    BridgeDecl { from_mod: String, to_mod: String, via: String, span: Span, },
    RedirectDecl { from_api: String, to_api: String, span: Span, },
    DeprecateDecl { target_api: String, after_cond: String, remove_cond: String, span: Span, },
    // Family 9: Anti-Spaghetti Metrics
    CycleFreeDecl { scope: String, span: Span, },
    FanoutDecl { module_name: String, limit: usize, span: Span, },
    FaninDecl { module_name: String, limit: usize, span: Span, },
    DepthDecl { limit: usize, span: Span, },
    CohesionDecl { module_name: String, min_threshold: f64, span: Span, },
    // Family 10: Automated Modularization & Self-Evolution
    ModularizeDecl {
        target: String,
        target_files_min: usize,
        target_files_max: usize,
        preserve: Vec<String>,
        span: Span,
    },
    DecomposeDecl {
        target: String,
        target_modules: Option<usize>,
        optimize: Vec<String>,
        preserve: Vec<String>,
        gravity: Option<String>,
        span: Span,
    },
    ArchitectureDecl {
        name: String,
        layers: Vec<String>,
        rules: Vec<String>,
        directions: Vec<(String, String)>,
        invariants: Vec<String>,
        cycle_free: bool,
        max_depth: Option<usize>,
        span: Span,
    },
    RepairDecl { target: String, span: Span, },
    EvolveArchDecl {
        from: String,
        toward: String,
        target_modules: usize,
        preserve: Vec<String>,
        optimize: Vec<String>,
        reject_if: Vec<String>,
        verify: Vec<String>,
        span: Span,
    },
    GravityDecl { weights: Vec<(String, f64)>, span: Span, },
    // Operation Values, Event-Native Architecture & Algebra Statements
    OperationDecl(OperationDef),
    EventDecl(EventDef),
    EventHubDecl(EventHubDef),
    EmitEvent { event_name: String, args: Vec<Expression>, span: Span, },
    ObserveOp { op_expr: Expression, alias: String, span: Span, },
    AnalyzeOp { op_expr: Expression, span: Span, },
    ExtractOpDecl { op_name: String, from_mod: String, condition: String, span: Span, },
    InlineOpDecl { op_name: String, span: Span, },
    SplitOpDecl { op_name: String, sub_ops: Vec<String>, span: Span, },
    MergeOpDecl { source_ops: Vec<String>, as_name: String, span: Span, },
    ExplainOpDecl { op_name: String, span: Span, },
    EvolveOpDecl {
        op_name: String,
        preserve: Vec<String>,
        optimize: Vec<String>,
        allow: Vec<String>,
        reject: Vec<String>,
        span: Span,
    },
    // Agent Contract System (Intent → Task → Skill → Evidence → Verify) Statements
    FeatureDecl { name: String, requirement: Option<String>, skills: Vec<String>, tasks: Vec<String>, span: Span, },
    SkillDecl {
        name: String,
        rules: Vec<String>,
        constraints: Vec<String>,
        structural: Vec<String>,
        semantic: Vec<String>,
        behavioral: Vec<String>,
        architectural: Vec<String>,
        performance: Vec<String>,
        security: Vec<String>,
        testing: Vec<String>,
        agent: Vec<String>,
        requires: Vec<String>,
        hard: Vec<String>,
        soft: Vec<String>,
        for_scope: Option<String>,
        span: Span,
    },
    SatisfiesDecl { entity: String, skills: Vec<String>, span: Span, },
    ProjectSkillsDecl { profile: std::collections::HashMap<String, String>, span: Span, },
    AgentTaskContractDecl {
        name: String,
        owner: Option<String>,
        status: Option<String>,
        requirement: Option<String>,
        implementation: Option<String>,
        skills: Vec<String>,
        change_budget: Vec<String>,
        evidence: Vec<(String, String)>,
        span: Span,
    },
    ClaimTask { task_name: String, span: Span, },
    CompleteTask {
        task_name: String,
        result: String,
        confidence: Option<f64>,
        summary: Option<String>,
        evidence: Vec<String>,
        risks: Option<String>,
        recommendation: Option<String>,
        notes: Option<String>,
        span: Span,
    },
    VerifyTask { target: String, is_adversarial: bool, skill: Option<String>, span: Span, },
    RequirementDecl { req_id: String, description: String, span: Span, },
    ImplementsDecl { req_id: String, entities: Vec<String>, span: Span, },
    VerifiesDecl { req_id: String, entities: Vec<String>, span: Span, },
    TodoDecl {
        id: String,
        implement: String,
        requires: Vec<String>,
        verify: Vec<String>,
        status: String,
        span: Span,
    },
    AgentBoundaryDecl { module_name: String, span: Span, },
    AgentContextDecl { module_name: String, expose: Vec<String>, hide: Vec<String>, span: Span, },
    ContextFirewallDecl { module_name: String, deny: Vec<String>, expose: Vec<String>, span: Span, },
    AgentApiDecl { module_name: String, expose: Vec<String>, hide: Vec<String>, span: Span, },
    AgentabilityDecl {
        max_context_tokens: usize,
        max_operation_complexity: String,
        max_dependency_fanout: usize,
        span: Span,
    },
    IntentDecl { goal: String, preserve: Vec<String>, optimize: Vec<String>, span: Span, },
    SemanticCommitDecl { task: String, intent: String, satisfies: Vec<String>, evidence: Vec<String>, span: Span, },
    AgentReviewDecl {
        task_id: String,
        summary: String,
        completed: usize,
        unresolved: usize,
        risks: usize,
        confidence: f64,
        span: Span,
    },
    ApprovalDecl { required_items: Vec<String>, span: Span, },
    AgentLeaseDecl { module_name: String, owner: String, duration: String, span: Span, },
    KnowledgeDecl { name: String, decisions: Vec<String>, constraints: Vec<String>, span: Span, },
    DecisionDecl { id: String, choose: String, because: String, reject: String, span: Span, },
    AgentCapabilityDecl { capabilities: Vec<String>, cannot: Vec<String>, span: Span, },
    RegressionGuardDecl { items: Vec<String>, span: Span, },
    // Layer 1 Extensibility DNA Statements
    PartialDecl {
        kind: String,
        name: String,
        body_struct: Option<StructDef>,
        body_module: Option<ModuleDef>,
        span: Span,
    },
    AugmentDecl(ExtensionBlock),
    OverrideDecl { target: String, method: FunctionDef, span: Span, },
    ExtensionPointDecl { target: String, points: Vec<String>, span: Span, },
    LayerSealedDecl { target_kind: String, target_name: String, span: Span, },
    LayerFriendDecl { target_kind: String, target_name: String, friend_name: String, span: Span, },
    // Layer 2 Super Module System
    ReplaceModuleDecl { target: String, replacement: String, span: Span, },
    ModuleMigrationDecl {
        module_name: String,
        from_version: usize,
        to_version: usize,
        renames: Vec<(String, String)>,
        span: Span,
    },
    ModuleFacadeDecl { name: String, methods: Vec<String>, span: Span, },
    ModuleOverlayDecl { name: String, target_env: String, body: Block, span: Span, },
    ModuleComposeDecl { modules: Vec<String>, span: Span, },
    // Layer 3 Type System for Extensibility
    OpenClosedTypeDecl { is_open: bool, name: String, span: Span, },
    ExtensionTraitDecl { trait_name: String, target_type: String, methods: Vec<FunctionDef>, span: Span, },
    ExtensionConflictDecl { target_type: String, resolutions: Vec<(String, String)>, span: Span, },
    // Layer 4 Syntax Extensibility
    SyntaxDecl {
        name: String,
        pattern: Option<String>,
        namespace: Option<String>,
        version: Option<usize>,
        params: Vec<FunctionParam>,
        return_type: Option<Type>,
        body: Option<Block>,
        span: Span,
    },
    UseSyntaxDecl { namespace: String, version: Option<usize>, span: Span, },
    // Layer 5 Compile-time Extensibility
    CompilerPluginDecl { name: String, kind: String, span: Span, },
    CustomLinterDecl { name: String, rules: Vec<String>, span: Span, },
    CustomAnalyzerDecl { name: String, checks: Vec<String>, span: Span, },
    CustomTypeRuleDecl { target_type: String, rules: Vec<String>, span: Span, },
    CustomOptimizerDecl { name: String, pass: String, span: Span, },
    BuildPluginDecl { name: String, hooks: Vec<String>, span: Span, },
    GeneratorDecl { name: String, target_format: String, span: Span, },
    ReflectDecl { target_type: String, queries: Vec<String>, span: Span, },
    // Layer 6 Architecture as Code
    ArchitectureContractDecl { name: String, rules: Vec<String>, span: Span, },
    ForbiddenDependencyDecl { from: String, to: String, span: Span, },
    AllowedDependencyDecl { from: String, to: String, span: Span, },
    ArchitectureBoundaryDecl { name: String, components: Vec<String>, span: Span, },
    ArchitectureOwnerDecl { target: String, owner: String, span: Span, },
    ArchitectureStabilityDecl { target: String, level: String, span: Span, },
    ArchitectureEvolutionDecl { module_name: String, from_v: String, to_v: String, span: Span, },
    ArchitectureTestDecl { assertions: Vec<String>, span: Span, },
    // Layer 7 Dependency Intelligence
    ChangeBudgetDecl { max_files: Option<usize>, max_modules: Option<usize>, public_api_allowed: Option<bool>, span: Span, },
    DependencyLockDecl { locked: bool, span: Span, },
    SemanticImportDecl { feature_intent: String, alias: Option<String>, span: Span, },
    // Layer 8 API Evolution
    ApiStabilityDecl { target: String, level: String, span: Span, },
    DeprecationDecl { target: String, replace_with: Option<String>, span: Span, },
    ApiSnapshotDecl { module_name: String, span: Span, },
    VerifyCompatibilityDecl { target1: String, target2: String, span: Span, },
    // Layer 9 Agent-Native Extensibility
    AgentExtensionContractDecl {
        name: String,
        purpose: String,
        inputs: Vec<String>,
        outputs: Vec<String>,
        constraints: Vec<String>,
        tests: Vec<String>,
        permissions: Vec<String>,
        span: Span,
    },
    AgentChangeProposalDecl {
        title: String,
        files: Vec<String>,
        symbols: Vec<String>,
        dependencies: Vec<String>,
        risks: Vec<String>,
        migration: Option<String>,
        span: Span,
    },
    AgentProofGateDecl { checks: Vec<String>, span: Span, },
    AgentTransactionDecl { action: String, body: Option<Block>, span: Span, },
    // Layer 10 Code Evolution Engine & @evolvable
    WhyMetadataDecl { why: String, reason: Option<String>, span: Span, },
    EvolvableDecl { module_name: String, metrics_target: Option<String>, span: Span, },
    // ── 50 Super Revolutionary Feature-Oriented Paradigm Statements ──
    FeatureStatement(FeatureDef),
    ContractDefinition(ContractDef),
    ArchitectureTemplate(ArchitectureTemplateDef),
    ArchitectureRuleStatement(ArchitectureRuleDef),
    FeatureMigrationStatement(FeatureMigrationDef),
    ReplaceFeature { target: String, with_provider: String, span: Span, },
    DecorateFeature { target: String, decorators: Vec<String>, span: Span, },
    ComposeFeature { target: String, components: Vec<String>, span: Span, },
    EvolveFeature {
        target: String,
        adds: Vec<String>,
        replaces: Vec<(String, String)>,
        body: Option<Block>,
        span: Span,
    },
    EvolveContract { target: String, adds: Vec<TraitMethodDef>, clauses: Vec<String>, span: Span, },
    ImpactQuery { target: String, span: Span, },
    UseFeature { feature: String, implementation: Option<String>, span: Span, },
    // ── 50 Capability-Oriented & Surface Composition Statements ──
    UseSurface { target: String, section: Option<String>, symbols: Vec<String>, alias: Option<String>, shape_fields: Vec<String>, is_borrow: bool, is_mut: bool, is_generic: Option<String>, span: Span, },
    AccessCapability { entity: String, capability: String, span: Span, },
    GrantCapability { target: String, capabilities: Vec<String>, span: Span, },
    DenyCapability { target: String, capabilities: Vec<String>, span: Span, },
    SurfaceDefinition(SurfaceDef),
    AdoptContract { target: String, alias: Option<String>, span: Span, },
    ImplementContract { contract: String, target: Option<String>, methods: Vec<FunctionDef>, span: Span, },
    AttachCapability { capabilities: Vec<String>, target: String, when_cond: Option<String>, if_pred: Option<String>, span: Span, },
    DetachCapability { capability: String, target: String, span: Span, },
    ComposeCapability { name: String, capabilities: Vec<String>, span: Span, },
    MixinDecl(MixinDef),
    CapabilityDecl(CapabilityDef),
    ProvideCapability { capability: String, span: Span, },
    RequireCapability { contract: String, alias: Option<String>, span: Span, },
    ResolveContract { contract: String, implementation: String, condition: Option<String>, span: Span, },
    SelectContract { contract: String, candidates: Vec<String>, span: Span, },
    ViewProjection { entity: String, view_shape: String, span: Span, },
    ProjectSurface { entity: String, fields: Vec<String>, span: Span, },
    DelegateBehavior { entity: String, method: String, target: String, span: Span, },
    ProxyCapability { target: String, interceptor: String, span: Span, },
    DecorateEntity { target: String, method: Option<String>, with_caps: Vec<String>, span: Span, },
    InterceptMethod(InterceptDef),
    HookEvent(HookDef),
    EnableCapability { capability: String, entity: String, enabled: bool, span: Span, },
    ScopeBoundary(ScopeDef),
    ContextEnv(ContextDef),
    FeatureSwitchDecl { name: String, enabled_env: String, span: Span, },
    TraitifyCheck { entity: String, trait_name: String, span: Span, },
    EquipEntity { entity: String, capabilities: Vec<String>, condition: Option<String>, span: Span, },
    FuseFeatures { features: Vec<String>, alias: String, span: Span, },
    ShapeDefinition(ShapeDef),
    DestructureAssign { pattern: crate::ast::pattern::Pattern, value: Expression, span: Span, },
    ExtendDecl { target: String, methods: Vec<FunctionDef>, properties: Vec<(String, Expression)>, span: Span, },
    LocalFunction(FunctionDef),
    FeaturePolicyDecl { name: String, rules: Vec<String>, span: Span, },
}
