PackageIdentifier: EndLanguage.End
PackageVersion: 1.0.0
PackageName: End Programming Language
Publisher: EndLanguage
License: MIT
ShortDescription: The AI-First Zero-GC Systems Programming Language
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/IrMaho/End/releases/download/v1.0.0/end-v1.0.0-windows-x64.zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: bin\endc.exe
        PortableCommandAlias: endc
      - RelativeFilePath: bin\end.exe
        PortableCommandAlias: end
ManifestType: singleton
ManifestVersion: 1.6.0
