PackageIdentifier: EndLanguage.End
PackageVersion: 0.4.0-alpha
PackageName: End Programming Language
Publisher: EndLanguage
License: MIT
ShortDescription: The AI-First Zero-GC Systems Programming Language
Installers:
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/IrMaho/End/releases/download/v0.4.0-alpha/end-v0.4.0-alpha-windows-x64.zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: bin\endc.exe
        PortableCommandAlias: endc
      - RelativeFilePath: bin\end.exe
        PortableCommandAlias: end
ManifestType: singleton
ManifestVersion: 1.6.0
