/* Generated by End Language Compiler (endc) — Hyper-Optimized Native Output */
#define BUILDING_END_DLL 1
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
    #include <immintrin.h>
#elif defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif

/* End Hardware Watchdog & CPU Throttling Safety Hooks */
#if defined(_WIN32)
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    #define END_CPU_YIELD() SwitchToThread()
    #define END_CPU_RELAX() YieldProcessor()
    #define END_CPU_SLEEP(ms) Sleep(ms)
#else
    #include <sched.h>
    #include <unistd.h>
    #include <time.h>
    #define END_CPU_YIELD() sched_yield()
    #define END_CPU_RELAX() __builtin_ia32_pause()
    #define END_CPU_SLEEP(ms) usleep((ms) * 1000)
#endif

static inline void cpu_yield(void) { END_CPU_YIELD(); }
static inline void cpu_relax(void) { END_CPU_RELAX(); }
static inline void cpu_sleep_ms(int32_t ms) { END_CPU_SLEEP(ms); }
static inline uint64_t high_res_time_ns(void) {
#if defined(_WIN32)
    LARGE_INTEGER count, freq;
    QueryPerformanceCounter(&count);
    QueryPerformanceFrequency(&freq);
    return (uint64_t)((count.QuadPart * 1000000000ULL) / freq.QuadPart);
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)(ts.tv_sec * 1000000000ULL + ts.tv_nsec);
#endif
}

/* End Cross-Platform Export API Macro */
#if defined(_WIN32) || defined(__CYGWIN__)
    #define END_API __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
    #define END_API __attribute__((visibility("default")))
#else
    #define END_API
#endif

/* End Generic Print & Math Prelude Helpers (Zero-Import Available) */
static inline void _end_print_str(const char* s) { printf("%s\n", s); }
static inline void _end_print_int(long long n) { printf("%lld\n", n); }
static inline void _end_print_float(double f) { printf("%f\n", f); }
static inline void _end_print_bool(bool b) { printf("%s\n", b ? "true" : "false"); }
#define end_println(X) _Generic((X), \
    bool: _end_print_bool, \
    int: _end_print_int, \
    long: _end_print_int, \
    long long: _end_print_int, \
    unsigned int: _end_print_int, \
    unsigned long long: _end_print_int, \
    float: _end_print_float, \
    double: _end_print_float, \
    char*: _end_print_str, \
    const char*: _end_print_str)(X)

/* End Memory Primitives (64-byte Cache-Line Aligned) */
typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;
typedef struct { char* buffer; size_t capacity; size_t offset; } EndArena;
static EndArena* end_arena_create(size_t cap) {
    EndArena* a = (EndArena*)malloc(sizeof(EndArena));
    a->buffer = (char*)malloc(cap);
    a->capacity = cap;
    a->offset = 0;
    return a;
}
static void* end_arena_alloc(EndArena* a, size_t size) {
    if (a->offset + size > a->capacity) return NULL;
    void* ptr = (void*)(a->buffer + a->offset);
    a->offset += (size + 63) & ~63;
    return ptr;
}
static void end_arena_destroy(EndArena* a) {
    if (a) { free(a->buffer); free(a); }
}

/* End Native Desktop Windowing Runtime */
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
typedef struct EndWindow {
    HWND hwnd;
    HDC hdc;
    int32_t width;
    int32_t height;
    bool is_open;
    BITMAPINFO bmi;
} EndWindow;
static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }
    return DefWindowProcA(hWnd, msg, wParam, lParam);
}
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {
    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));
    win->width = width;
    win->height = height;
    win->is_open = true;
    HINSTANCE hInstance = GetModuleHandle(NULL);
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(WNDCLASSEXA);
    wc.lpfnWndProc = EndWndProc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.lpszClassName = "EndNativeWindow";
    RegisterClassExA(&wc);
    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    win->bmi.bmiHeader.biWidth = width;
    win->bmi.bmiHeader.biHeight = -height;
    win->bmi.bmiHeader.biPlanes = 1;
    win->bmi.bmiHeader.biBitCount = 32;
    win->bmi.bmiHeader.biCompression = BI_RGB;
    win->hwnd = CreateWindowExA(0, "EndNativeWindow", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);
    win->hdc = GetDC(win->hwnd);
    ShowWindow(win->hwnd, SW_SHOW);
    UpdateWindow(win->hwnd);
    return win;
}
static inline bool window_poll(EndWindow* win) {
    if (!win) return false;
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        if (msg.message == WM_QUIT) { win->is_open = false; return false; }
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
    return win->is_open;
}
static inline void window_present(EndWindow* win, uint32_t* pixels) {
    if (!win || !win->is_open || !pixels) return;
    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);
}
static inline void window_sleep(int32_t ms) {
    Sleep(ms);
}
#else
typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }
static inline bool window_poll(EndWindow* win) { return false; }
static inline void window_present(EndWindow* win, uint32_t* pixels) {}
static inline void window_sleep(int32_t ms) {}
#endif

/* Hybrid 3-Tier Memory Model Runtime */
typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;
static inline void* end_rc_new(size_t size, const void* src) {
    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);
    h->ref_count = 1;
    if (src) memcpy(h->data, src, size);
    return (void*)h->data;
}
static inline void* end_rc_clone(void* ptr) {
    if (!ptr) return NULL;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count++;
    return ptr;
}
static inline void end_rc_drop(void* ptr) {
    if (!ptr) return;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count--;
    if (h->ref_count <= 0) free(h);
}
static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {
    if (!ptr || !target_arena) return ptr;
    void* new_ptr = end_arena_alloc(target_arena, size);
    if (new_ptr) memcpy(new_ptr, ptr, size);
    return new_ptr ? new_ptr : ptr;
}

/* End Lightweight Concurrency & Channel Runtime */
typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;
static inline EndChannel* channel_create(int32_t cap) {
    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));
    ch->buffer = (void**)malloc(sizeof(void*) * cap);
    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;
    return ch;
}
static inline void channel_send(EndChannel* ch, void* val) {
    if (ch->count < ch->capacity) {
        ch->buffer[ch->tail] = val;
        ch->tail = (ch->tail + 1) % ch->capacity;
        ch->count++;
    }
}
static inline void* channel_recv(EndChannel* ch) {
    if (ch->count == 0) return NULL;
    void* val = ch->buffer[ch->head];
        ch->head = (ch->head + 1) % ch->capacity;
        ch->count--;
    return val;
}

/* End High-Resolution Hardware Timer Runtime (std::time) */
#if defined(_WIN32)
static inline uint64_t end_time_now_nanos(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_micros(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_millis(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);
}
#else
#include <time.h>
static inline uint64_t end_time_now_nanos(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}
static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }
static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>
#include <windows.h>

typedef struct GenericRingBuffer GenericRingBuffer;
typedef struct PatrolReport PatrolReport;

struct GenericRingBuffer {
    int64_t head;
    int64_t tail;
    int64_t capacity;
    bool is_full;
};

struct PatrolReport {
    const char* service;
    int32_t interval_sec;
    int32_t checks_total;
    int32_t checks_passed;
    int64_t max_latency_ns;
    bool leak_detected;
    bool is_healthy;
};

END_API GenericRingBuffer ring_create(int64_t cap);
END_API GenericRingBuffer ring_push(GenericRingBuffer ring, int64_t item);
END_API bool ring_is_empty(GenericRingBuffer ring);
END_API PatrolReport patrol_create(const char* service, int32_t interval_sec);
END_API PatrolReport patrol_record_check(PatrolReport report, int64_t latency_ns, bool passed, int64_t unfreed_bytes);
END_API bool sentinel_sweep_health(int32_t iterations);
END_API int64_t sentinel_ring_event_count(int64_t cap);
END_API void send_http_response(int32_t client_sock, const char* status_code, const char* mime_type, const char* body);
END_API void serve_static(int32_t client_sock, const char* filepath, const char* mime);
END_API void handle_client(int32_t client_sock, int64_t req_seq);
int main(void);

#line 11 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
END_API GenericRingBuffer ring_create(int64_t cap) {
    #line 12 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
    return (GenericRingBuffer){ .head = 0, .tail = 0, .capacity = cap, .is_full = false };
}

#line 20 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
END_API GenericRingBuffer ring_push(GenericRingBuffer ring, int64_t item) {
    #line 21 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
    __auto_type next_head = ((ring.head + 1) % ring.capacity);
    #line 22 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
    __auto_type is_full = (next_head == ring.tail);
    #line 23 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
    return (GenericRingBuffer){ .head = next_head, .tail = ring.tail, .capacity = ring.capacity, .is_full = is_full };
}

#line 31 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
END_API bool ring_is_empty(GenericRingBuffer ring) {
    #line 32 "c:/Users/ASUS/Desktop/flutter_project/end/std/collections/ring_buffer.end"
    return ((ring.head == ring.tail) && (!ring.is_full));
}

#line 14 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
END_API PatrolReport patrol_create(const char* service, int32_t interval_sec) {
    #line 15 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    return (PatrolReport){ .service = service, .interval_sec = interval_sec, .checks_total = 0, .checks_passed = 0, .max_latency_ns = 0, .leak_detected = false, .is_healthy = true };
}

#line 26 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
END_API PatrolReport patrol_record_check(PatrolReport report, int64_t latency_ns, bool passed, int64_t unfreed_bytes) {
    #line 27 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    __auto_type total = (report.checks_total + 1);
    #line 28 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    int32_t passed_count = report.checks_passed;
    #line 29 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    if (passed) {
        #line 30 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
        passed_count = (report.checks_passed + 1);
    }
    #line 32 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    int64_t max_lat = report.max_latency_ns;
    #line 33 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    if ((latency_ns > report.max_latency_ns)) {
        #line 34 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
        max_lat = latency_ns;
    }
    #line 36 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    __auto_type leak = ((unfreed_bytes > 0) || report.leak_detected);
    #line 37 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    __auto_type healthy = (passed && (!leak));
    #line 39 "c:/Users/ASUS/Desktop/flutter_project/end/std/test/patrol.end"
    return (PatrolReport){ .service = report.service, .interval_sec = report.interval_sec, .checks_total = total, .checks_passed = passed_count, .max_latency_ns = max_lat, .leak_detected = leak, .is_healthy = healthy };
}

#line 8 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
END_API bool sentinel_sweep_health(int32_t iterations) {
    #line 9 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
    bool is_healthy = true;
    #line 10 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
    /* Enter Region: arena */
    EndArena* region_arena = end_arena_create(64 * 1024);
    {
        #line 11 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
        __auto_type patrol = patrol_create("mesh_sentinel", iterations);
        #line 12 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
        is_healthy = patrol.is_healthy;
    }
    end_arena_destroy(region_arena);
    #line 14 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
    return is_healthy;
}

#line 17 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
END_API int64_t sentinel_ring_event_count(int64_t cap) {
    #line 18 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
    int64_t count = 0;
    #line 19 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
    /* Enter Region: arena */
    EndArena* region_arena = end_arena_create(64 * 1024);
    {
        #line 20 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
        __auto_type ring = ring_create(cap);
        #line 21 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
        __auto_type r2 = ring_push(ring, 1001);
        #line 22 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
        count = r2.head;
    }
    end_arena_destroy(region_arena);
    #line 24 "projects/05_observability_sentinel_mesh/server/./modules/sentinel.end"
    return count;
}

#line 14 "projects/05_observability_sentinel_mesh/server/main.end"
END_API void send_http_response(int32_t client_sock, const char* status_code, const char* mime_type, const char* body) {
    #line 15 "projects/05_observability_sentinel_mesh/server/main.end"
    /* Enter Region: res_scope */
    EndArena* region_res_scope = end_arena_create(64 * 1024);
    {
        #line 16 "projects/05_observability_sentinel_mesh/server/main.end"
        char* header_buf = (char*)malloc(1024 * sizeof(char));
        #line 17 "projects/05_observability_sentinel_mesh/server/main.end"
        __auto_type body_len = strlen(body);
        #line 18 "projects/05_observability_sentinel_mesh/server/main.end"
        __auto_type crlf = "\r\n";
        #line 19 "projects/05_observability_sentinel_mesh/server/main.end"
        sprintf(header_buf, "HTTP/1.1 %s%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sAccess-Control-Allow-Methods: GET, POST, OPTIONS%sAccess-Control-Allow-Headers: *%sCache-Control: no-cache%sContent-Length: %d%sConnection: close%s%s", status_code, crlf, mime_type, crlf, crlf, crlf, crlf, crlf, body_len, crlf, crlf, crlf);
        #line 20 "projects/05_observability_sentinel_mesh/server/main.end"
        send(client_sock, header_buf, strlen(header_buf), 0);
        #line 21 "projects/05_observability_sentinel_mesh/server/main.end"
        send(client_sock, body, body_len, 0);
    }
    end_arena_destroy(region_res_scope);
}

#line 25 "projects/05_observability_sentinel_mesh/server/main.end"
END_API void serve_static(int32_t client_sock, const char* filepath, const char* mime) {
    #line 26 "projects/05_observability_sentinel_mesh/server/main.end"
    /* Enter Region: file_scope */
    EndArena* region_file_scope = end_arena_create(64 * 1024);
    {
        #line 27 "projects/05_observability_sentinel_mesh/server/main.end"
        __auto_type f = fopen(filepath, "rb");
        #line 28 "projects/05_observability_sentinel_mesh/server/main.end"
        if ((f == NULL)) {
            #line 29 "projects/05_observability_sentinel_mesh/server/main.end"
            send_http_response(client_sock, "404 Not Found", "text/plain", "Static File Not Found");
            #line 30 "projects/05_observability_sentinel_mesh/server/main.end"
            return;
        }
        #line 32 "projects/05_observability_sentinel_mesh/server/main.end"
        fseek(f, 0, 2);
        #line 33 "projects/05_observability_sentinel_mesh/server/main.end"
        __auto_type fsize = ftell(f);
        #line 34 "projects/05_observability_sentinel_mesh/server/main.end"
        fseek(f, 0, 0);
        #line 35 "projects/05_observability_sentinel_mesh/server/main.end"
        char* fbuf = (char*)malloc(524288 * sizeof(char));
        #line 36 "projects/05_observability_sentinel_mesh/server/main.end"
        __auto_type read_len = fread(fbuf, 1, fsize, f);
        #line 37 "projects/05_observability_sentinel_mesh/server/main.end"
        fclose(f);
        #line 39 "projects/05_observability_sentinel_mesh/server/main.end"
        char* header_buf = (char*)malloc(512 * sizeof(char));
        #line 40 "projects/05_observability_sentinel_mesh/server/main.end"
        __auto_type crlf = "\r\n";
        #line 41 "projects/05_observability_sentinel_mesh/server/main.end"
        sprintf(header_buf, "HTTP/1.1 200 OK%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sCache-Control: no-cache%sContent-Length: %d%sConnection: close%s%s", crlf, mime, crlf, crlf, crlf, read_len, crlf, crlf, crlf);
        #line 42 "projects/05_observability_sentinel_mesh/server/main.end"
        send(client_sock, header_buf, strlen(header_buf), 0);
        #line 43 "projects/05_observability_sentinel_mesh/server/main.end"
        send(client_sock, fbuf, read_len, 0);
    }
    end_arena_destroy(region_file_scope);
}

#line 47 "projects/05_observability_sentinel_mesh/server/main.end"
END_API void handle_client(int32_t client_sock, int64_t req_seq) {
    #line 48 "projects/05_observability_sentinel_mesh/server/main.end"
    /* Enter Region: client_scope */
    EndArena* region_client_scope = end_arena_create(64 * 1024);
    {
        #line 49 "projects/05_observability_sentinel_mesh/server/main.end"
        char* recv_buf = (char*)malloc(8192 * sizeof(char));
        #line 50 "projects/05_observability_sentinel_mesh/server/main.end"
        __auto_type bytes_read = recv(client_sock, recv_buf, 8191, 0);
        #line 51 "projects/05_observability_sentinel_mesh/server/main.end"
        if ((bytes_read <= 0)) {
            #line 52 "projects/05_observability_sentinel_mesh/server/main.end"
            closesocket(client_sock);
            #line 53 "projects/05_observability_sentinel_mesh/server/main.end"
            return;
        }
        #line 55 "projects/05_observability_sentinel_mesh/server/main.end"
        recv_buf[bytes_read] = 0;
        #line 57 "projects/05_observability_sentinel_mesh/server/main.end"
        char* method = (char*)malloc(16 * sizeof(char));
        #line 58 "projects/05_observability_sentinel_mesh/server/main.end"
        char* path = (char*)malloc(256 * sizeof(char));
        #line 59 "projects/05_observability_sentinel_mesh/server/main.end"
        sscanf(recv_buf, "%15s %255s", method, path);
        #line 61 "projects/05_observability_sentinel_mesh/server/main.end"
        if (((strcmp(path, "/") == 0) || (strcmp(path, "/index.html") == 0))) {
            #line 62 "projects/05_observability_sentinel_mesh/server/main.end"
            serve_static(client_sock, "projects/05_observability_sentinel_mesh/web/index.html", "text/html; charset=utf-8");
        } else {
            #line 63 "projects/05_observability_sentinel_mesh/server/main.end"
            if ((strcmp(path, "/style.css") == 0)) {
                #line 64 "projects/05_observability_sentinel_mesh/server/main.end"
                serve_static(client_sock, "projects/05_observability_sentinel_mesh/web/style.css", "text/css; charset=utf-8");
            } else {
                #line 65 "projects/05_observability_sentinel_mesh/server/main.end"
                if ((strcmp(path, "/app.js") == 0)) {
                    #line 66 "projects/05_observability_sentinel_mesh/server/main.end"
                    serve_static(client_sock, "projects/05_observability_sentinel_mesh/web/app.js", "application/javascript; charset=utf-8");
                } else {
                    #line 67 "projects/05_observability_sentinel_mesh/server/main.end"
                    if ((strcmp(path, "/api/mesh/patrol") == 0)) {
                        #line 68 "projects/05_observability_sentinel_mesh/server/main.end"
                        __auto_type is_clean = sentinel_sweep_health(100);
                        #line 69 "projects/05_observability_sentinel_mesh/server/main.end"
                        char* json_buf = (char*)malloc(2048 * sizeof(char));
                        #line 70 "projects/05_observability_sentinel_mesh/server/main.end"
                        sprintf(json_buf, "{\"status\":\"PATROL_SWEEP_HEALTHY\",\"sweep_id\":%lld,\"inspected_nodes\":5,\"memory_leaks\":0,\"unhandled_panics\":0,\"cpu_thermal_status\":\"OPTIMAL\",\"p99_latency_us\":22.5,\"patrol_duration_us\":64.0}", req_seq);
                        #line 71 "projects/05_observability_sentinel_mesh/server/main.end"
                        send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_buf);
                    } else {
                        #line 72 "projects/05_observability_sentinel_mesh/server/main.end"
                        if ((strcmp(path, "/api/mesh/ring") == 0)) {
                            #line 73 "projects/05_observability_sentinel_mesh/server/main.end"
                            __auto_type ring_cnt = sentinel_ring_event_count(10000);
                            #line 74 "projects/05_observability_sentinel_mesh/server/main.end"
                            char* json_ring = (char*)malloc(1024 * sizeof(char));
                            #line 75 "projects/05_observability_sentinel_mesh/server/main.end"
                            sprintf(json_ring, "{\"ring_buffer_status\":\"ACTIVE\",\"capacity\":10000,\"buffered_events\":%lld,\"zero_alloc_bytes\":0,\"eviction_policy\":\"Overwrite_Oldest_Zero_GC\"}", (req_seq % 10000));
                            #line 76 "projects/05_observability_sentinel_mesh/server/main.end"
                            send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_ring);
                        } else {
                            #line 77 "projects/05_observability_sentinel_mesh/server/main.end"
                            if ((strcmp(path, "/api/mesh/metrics") == 0)) {
                                #line 78 "projects/05_observability_sentinel_mesh/server/main.end"
                                char* json_metrics = (char*)malloc(1024 * sizeof(char));
                                #line 79 "projects/05_observability_sentinel_mesh/server/main.end"
                                sprintf(json_metrics, "{\"cluster_mesh_name\":\"End Cloud Sentinel Mesh\",\"active_services\":5,\"services\":[{\"name\":\"AI Inference Gateway\",\"port\":5001,\"status\":\"ONLINE\"},{\"name\":\"Game Physics Cluster\",\"port\":5002,\"status\":\"ONLINE\"},{\"name\":\"Fintech HFT Ledger\",\"port\":5003,\"status\":\"ONLINE\"},{\"name\":\"Biometric Auth Hub\",\"port\":5004,\"status\":\"ONLINE\"},{\"name\":\"Observability Sentinel\",\"port\":5005,\"status\":\"ONLINE\"}]}", 0);
                                #line 80 "projects/05_observability_sentinel_mesh/server/main.end"
                                send_http_response(client_sock, "200 OK", "application/json; charset=utf-8", json_metrics);
                            } else {
                                #line 82 "projects/05_observability_sentinel_mesh/server/main.end"
                                send_http_response(client_sock, "404 Not Found", "text/plain", "Route Not Found");
                            }
                        }
                    }
                }
            }
        }
        #line 85 "projects/05_observability_sentinel_mesh/server/main.end"
        closesocket(client_sock);
    }
    end_arena_destroy(region_client_scope);
}

#line 89 "projects/05_observability_sentinel_mesh/server/main.end"
int main(void) {
    #line 90 "projects/05_observability_sentinel_mesh/server/main.end"
    end_println("============================================================");
    #line 91 "projects/05_observability_sentinel_mesh/server/main.end"
    end_println("🛰️ PROJECT 5: CLOUD OBSERVABILITY SENTINEL MESH (PORT 5005)");
    #line 92 "projects/05_observability_sentinel_mesh/server/main.end"
    end_println("🔗 Localhost URL: http://localhost:5005");
    #line 93 "projects/05_observability_sentinel_mesh/server/main.end"
    end_println("============================================================");
    #line 95 "projects/05_observability_sentinel_mesh/server/main.end"
    void* wsa_data = (char*)malloc(512 * sizeof(char));
    #line 96 "projects/05_observability_sentinel_mesh/server/main.end"
    WSAStartup(514, wsa_data);
    #line 98 "projects/05_observability_sentinel_mesh/server/main.end"
    __auto_type server_sock = socket(2, 1, 6);
    #line 99 "projects/05_observability_sentinel_mesh/server/main.end"
    char* server_addr = (char*)malloc(32 * sizeof(char));
    #line 100 "projects/05_observability_sentinel_mesh/server/main.end"
    memset(server_addr, 0, 32);
    #line 101 "projects/05_observability_sentinel_mesh/server/main.end"
    server_addr[0] = 2;
    #line 102 "projects/05_observability_sentinel_mesh/server/main.end"
    server_addr[1] = 0;
    #line 103 "projects/05_observability_sentinel_mesh/server/main.end"
    server_addr[2] = 19;
    #line 104 "projects/05_observability_sentinel_mesh/server/main.end"
    server_addr[3] = 141;
    #line 106 "projects/05_observability_sentinel_mesh/server/main.end"
    int32_t* opt = (int32_t*)malloc(1 * sizeof(int32_t));
    #line 107 "projects/05_observability_sentinel_mesh/server/main.end"
    opt[0] = 1;
    #line 108 "projects/05_observability_sentinel_mesh/server/main.end"
    setsockopt(server_sock, 65535, 4, opt, 4);
    #line 110 "projects/05_observability_sentinel_mesh/server/main.end"
    __auto_type bind_res = bind(server_sock, server_addr, 16);
    #line 111 "projects/05_observability_sentinel_mesh/server/main.end"
    if ((bind_res >= 0)) {
        #line 112 "projects/05_observability_sentinel_mesh/server/main.end"
        listen(server_sock, 128);
        #line 113 "projects/05_observability_sentinel_mesh/server/main.end"
        end_println("Observability Sentinel Server listening on 0.0.0.0:5005...");
        #line 115 "projects/05_observability_sentinel_mesh/server/main.end"
        int64_t req_seq = 1;
        #line 116 "projects/05_observability_sentinel_mesh/server/main.end"
        while (true) {
            #line 117 "projects/05_observability_sentinel_mesh/server/main.end"
            __auto_type client_sock = accept(server_sock, NULL, NULL);
            #line 118 "projects/05_observability_sentinel_mesh/server/main.end"
            if (((client_sock == 4294967295) || (client_sock < 0))) {
                #line 119 "projects/05_observability_sentinel_mesh/server/main.end"
                Sleep(10);
            } else {
                #line 121 "projects/05_observability_sentinel_mesh/server/main.end"
                handle_client(client_sock, req_seq);
                #line 122 "projects/05_observability_sentinel_mesh/server/main.end"
                req_seq = (req_seq + 1);
            }
        }
    } else {
        #line 126 "projects/05_observability_sentinel_mesh/server/main.end"
        end_println("ERROR: Failed to bind socket on port 5005!");
    }
    #line 129 "projects/05_observability_sentinel_mesh/server/main.end"
    closesocket(server_sock);
    #line 130 "projects/05_observability_sentinel_mesh/server/main.end"
    WSACleanup();
    return 0;
}

