/* Generated by End Language Compiler (endc) — Hyper-Optimized Native Output */
#define BUILDING_END_DLL 1
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
    #include <immintrin.h>
#elif defined(__aarch64__) || defined(_M_ARM64)
    #include <arm_neon.h>
#endif

/* End Cross-Platform Export API Macro */
#if defined(_WIN32) || defined(__CYGWIN__)
    #define END_API __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
    #define END_API __attribute__((visibility("default")))
#else
    #define END_API
#endif

/* End Generic Print & Math Prelude Helpers (Zero-Import Available) */
static inline void _end_print_str(const char* s) { printf("%s\n", s); }
static inline void _end_print_int(long long n) { printf("%lld\n", n); }
static inline void _end_print_float(double f) { printf("%f\n", f); }
static inline void _end_print_bool(bool b) { printf("%s\n", b ? "true" : "false"); }
#define end_println(X) _Generic((X), \
    bool: _end_print_bool, \
    int: _end_print_int, \
    long: _end_print_int, \
    long long: _end_print_int, \
    unsigned int: _end_print_int, \
    unsigned long long: _end_print_int, \
    float: _end_print_float, \
    double: _end_print_float, \
    char*: _end_print_str, \
    const char*: _end_print_str)(X)

/* End Memory Primitives (64-byte Cache-Line Aligned) */
typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;
typedef struct { char* buffer; size_t capacity; size_t offset; } EndArena;
static inline __attribute__((always_inline)) EndArena* end_arena_create(size_t cap) {
    EndArena* a = (EndArena*)malloc(sizeof(EndArena));
    a->buffer = (char*)malloc(cap);
    a->capacity = cap;
    a->offset = 0;
    return a;
}
static inline __attribute__((always_inline)) void* end_arena_alloc(EndArena* a, size_t size) {
    if (a->offset + size > a->capacity) return NULL;
    void* ptr = (void*)(a->buffer + a->offset);
    a->offset += (size + 63) & ~63;
    return ptr;
}
static inline __attribute__((always_inline)) void end_arena_destroy(EndArena* a) {
    if (a) { free(a->buffer); free(a); }
}

/* End Native Desktop Windowing Runtime */
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
typedef struct EndWindow {
    HWND hwnd;
    HDC hdc;
    int32_t width;
    int32_t height;
    bool is_open;
    BITMAPINFO bmi;
} EndWindow;
static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }
    return DefWindowProcA(hWnd, msg, wParam, lParam);
}
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {
    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));
    win->width = width;
    win->height = height;
    win->is_open = true;
    HINSTANCE hInstance = GetModuleHandle(NULL);
    WNDCLASSEXA wc = {0};
    wc.cbSize = sizeof(WNDCLASSEXA);
    wc.lpfnWndProc = EndWndProc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.lpszClassName = "EndNativeWindow";
    RegisterClassExA(&wc);
    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    win->bmi.bmiHeader.biWidth = width;
    win->bmi.bmiHeader.biHeight = -height;
    win->bmi.bmiHeader.biPlanes = 1;
    win->bmi.bmiHeader.biBitCount = 32;
    win->bmi.bmiHeader.biCompression = BI_RGB;
    win->hwnd = CreateWindowExA(0, "EndNativeWindow", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);
    win->hdc = GetDC(win->hwnd);
    ShowWindow(win->hwnd, SW_SHOW);
    UpdateWindow(win->hwnd);
    return win;
}
static inline bool window_poll(EndWindow* win) {
    if (!win) return false;
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        if (msg.message == WM_QUIT) { win->is_open = false; return false; }
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
    return win->is_open;
}
static inline void window_present(EndWindow* win, uint32_t* pixels) {
    if (!win || !win->is_open || !pixels) return;
    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);
}
static inline void window_sleep(int32_t ms) {
    Sleep(ms);
}
#else
typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;
static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }
static inline bool window_poll(EndWindow* win) { return false; }
static inline void window_present(EndWindow* win, uint32_t* pixels) {}
static inline void window_sleep(int32_t ms) {}
#endif

/* Hybrid 3-Tier Memory Model Runtime */
typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;
static inline void* end_rc_new(size_t size, const void* src) {
    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);
    h->ref_count = 1;
    if (src) memcpy(h->data, src, size);
    return (void*)h->data;
}
static inline void* end_rc_clone(void* ptr) {
    if (!ptr) return NULL;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count++;
    return ptr;
}
static inline void end_rc_drop(void* ptr) {
    if (!ptr) return;
    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));
    h->ref_count--;
    if (h->ref_count <= 0) free(h);
}
static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {
    if (!ptr || !target_arena) return ptr;
    void* new_ptr = end_arena_alloc(target_arena, size);
    if (new_ptr) memcpy(new_ptr, ptr, size);
    return new_ptr ? new_ptr : ptr;
}

/* End Lightweight Concurrency & Channel Runtime */
typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;
static inline EndChannel* channel_create(int32_t cap) {
    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));
    ch->buffer = (void**)malloc(sizeof(void*) * cap);
    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;
    return ch;
}
static inline void channel_send(EndChannel* ch, void* val) {
    if (ch->count < ch->capacity) {
        ch->buffer[ch->tail] = val;
        ch->tail = (ch->tail + 1) % ch->capacity;
        ch->count++;
    }
}
static inline void* channel_recv(EndChannel* ch) {
    if (ch->count == 0) return NULL;
    void* val = ch->buffer[ch->head];
        ch->head = (ch->head + 1) % ch->capacity;
        ch->count--;
    return val;
}

/* End High-Resolution Hardware Timer Runtime (std::time) */
#if defined(_WIN32)
static inline uint64_t end_time_now_nanos(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_micros(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);
}
static inline uint64_t end_time_now_millis(void) {
    LARGE_INTEGER freq, counter;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&counter);
    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);
}
#else
#include <time.h>
static inline uint64_t end_time_now_nanos(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}
static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }
static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>


END_API void nexus_send_response(int32_t sock, const char* status_code, const char* content_type, const char* body);
END_API void nexus_serve_static(int32_t sock, const char* filepath, const char* mime);
END_API int64_t nexus_integrate_physics(int32_t x, int32_t y, int32_t vx, int32_t vy, int32_t bound_w, int32_t bound_h);
END_API int64_t nexus_calculate_distance(int32_t x1, int32_t y1, int32_t x2, int32_t y2);
END_API int32_t nexus_ring_buffer_push(int32_t head, int32_t max_cap);
END_API int64_t nexus_compute_checksum(int64_t data_seed, int64_t tick);
END_API int64_t nexus_sign_session(int64_t player_id, int64_t secret_seed);
END_API bool nexus_rate_check(int32_t tokens, int32_t cost);
END_API const char* nexus_framework_version(void);
END_API int64_t simulate_particle_field(int32_t particle_count, int32_t center_x, int32_t center_y, int64_t tick);
END_API int64_t calculate_collision_pairs(int32_t entities);
END_API int64_t allocate_game_room(int64_t player_id, int32_t skill_rating);
END_API int64_t calculate_lobby_ping(int32_t region_code);
END_API int32_t compute_player_rank(int64_t score);
END_API int32_t calculate_xp_multiplier(int32_t streak);
static inline __attribute__((always_inline)) void handle_game_client(int32_t client_sock, int64_t req_seq);
int main(void);

END_API void nexus_send_response(int32_t sock, const char* status_code, const char* content_type, const char* body) {
    /* Enter Region: r */
    EndArena* region_r = end_arena_create(64 * 1024);
    {
        char* header_buf = (char*)malloc(1024 * sizeof(char));
        __auto_type body_len = strlen(body);
        __auto_type crlf = "\r\n";
        sprintf(header_buf, "HTTP/1.1 %s%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sAccess-Control-Allow-Methods: GET, POST, OPTIONS%sAccess-Control-Allow-Headers: *%sCache-Control: no-store, no-cache%sContent-Length: %d%sConnection: close%s%s", status_code, crlf, content_type, crlf, crlf, crlf, crlf, crlf, body_len, crlf, crlf, crlf);
        send(sock, header_buf, strlen(header_buf), 0);
        send(sock, body, body_len, 0);
    }
    end_arena_destroy(region_r);
}

END_API void nexus_serve_static(int32_t sock, const char* filepath, const char* mime) {
    /* Enter Region: r */
    EndArena* region_r = end_arena_create(64 * 1024);
    {
        __auto_type f = fopen(filepath, "rb");
        if ((f == NULL)) {
            nexus_send_response(sock, "404 Not Found", "text/plain", "404 Not Found");
            return;
        }
        fseek(f, 0, 2);
        __auto_type size = ftell(f);
        fseek(f, 0, 0);
        char* buf = (char*)malloc(524288 * sizeof(char));
        __auto_type read_len = fread(buf, 1, size, f);
        fclose(f);
        char* header_buf = (char*)malloc(512 * sizeof(char));
        __auto_type crlf = "\r\n";
        sprintf(header_buf, "HTTP/1.1 200 OK%sContent-Type: %s%sAccess-Control-Allow-Origin: *%sCache-Control: no-cache%sContent-Length: %d%sConnection: close%s%s", crlf, mime, crlf, crlf, crlf, read_len, crlf, crlf, crlf);
        send(sock, header_buf, strlen(header_buf), 0);
        send(sock, buf, read_len, 0);
    }
    end_arena_destroy(region_r);
}

END_API int64_t nexus_integrate_physics(int32_t x, int32_t y, int32_t vx, int32_t vy, int32_t bound_w, int32_t bound_h) {
    __auto_type nx = (x + vx);
    __auto_type ny = (y + vy);
    if ((nx < 0)) {
        nx = 0;
    } else {
        if ((nx > bound_w)) {
            nx = bound_w;
        }
    }
    if ((ny < 0)) {
        ny = 0;
    } else {
        if ((ny > bound_h)) {
            ny = bound_h;
        }
    }
    int64_t packed_pos = ((nx * 10000) + ny);
    return packed_pos;
}

END_API int64_t nexus_calculate_distance(int32_t x1, int32_t y1, int32_t x2, int32_t y2) {
    __auto_type dx = (x1 - x2);
    __auto_type dy = (y1 - y2);
    return ((dx * dx) + (dy * dy));
}

END_API int32_t nexus_ring_buffer_push(int32_t head, int32_t max_cap) {
    return ((head + 1) % max_cap);
}

END_API int64_t nexus_compute_checksum(int64_t data_seed, int64_t tick) {
    int64_t magic = 1597463007;
    return ((((uint64_t)(data_seed)) ^ ((uint64_t)((tick * 31)))) + magic);
}

END_API int64_t nexus_sign_session(int64_t player_id, int64_t secret_seed) {
    int64_t h = 2654435769;
    return ((((uint64_t)(player_id)) ^ ((uint64_t)(secret_seed))) + h);
}

END_API bool nexus_rate_check(int32_t tokens, int32_t cost) {
    if ((tokens >= cost)) {
        return true;
    }
    return false;
}

END_API const char* nexus_framework_version(void) {
    return "EndNexus-v1.0.0-Ultra120FPS";
}

END_API int64_t simulate_particle_field(int32_t particle_count, int32_t center_x, int32_t center_y, int64_t tick) {
    int64_t energy = 0;
    /* Enter Region: r */
    EndArena* region_r = end_arena_create(64 * 1024);
    {
        #pragma clang loop vectorize(enable) unroll(enable)
        for (int32_t i = 0; i < particle_count; i++) {
            __auto_type angle = (((tick * 7) + (i * 13)) % 360);
            __auto_type dist = (50 + ((i * 17) % 200));
            energy = (energy + (dist * angle));
        }
    }
    end_arena_destroy(region_r);
    return energy;
}

END_API int64_t calculate_collision_pairs(int32_t entities) {
    return ((entities * (entities - 1)) / 2);
}

END_API int64_t allocate_game_room(int64_t player_id, int32_t skill_rating) {
    __auto_type room_seed = (((uint64_t)((player_id * 31))) ^ ((uint64_t)((skill_rating * 97))));
    __auto_type room_id = (1000 + (room_seed % 50));
    return room_id;
}

END_API int64_t calculate_lobby_ping(int32_t region_code) {
    return (15 + (region_code * 8));
}

END_API int32_t compute_player_rank(int64_t score) {
    if ((score > 100000)) {
        return 1;
    } else {
        if ((score > 75000)) {
            return 2;
        } else {
            if ((score > 50000)) {
                return 3;
            } else {
                if ((score > 25000)) {
                    return 4;
                }
            }
        }
    }
    return 5;
}

END_API int32_t calculate_xp_multiplier(int32_t streak) {
    return (100 + (streak * 15));
}

static inline __attribute__((always_inline)) void handle_game_client(int32_t client_sock, int64_t req_seq) {
    /* Enter Region: r */
    EndArena* region_r = end_arena_create(64 * 1024);
    {
        char* recv_buf = (char*)malloc(8192 * sizeof(char));
        __auto_type bytes_read = recv(client_sock, recv_buf, 8191, 0);
        if ((bytes_read <= 0)) {
            closesocket(client_sock);
            return;
        }
        recv_buf[bytes_read] = 0;
        char* method = (char*)malloc(16 * sizeof(char));
        char* path = (char*)malloc(256 * sizeof(char));
        sscanf(recv_buf, "%15s %255s", method, path);
        if (((strcmp(path, "/") == 0) || (strcmp(path, "/index.html") == 0))) {
            nexus_serve_static(client_sock, "projects/02_nexus_game_studio/web/index.html", "text/html; charset=utf-8");
        } else {
            if ((strcmp(path, "/style.css") == 0)) {
                nexus_serve_static(client_sock, "projects/02_nexus_game_studio/web/style.css", "text/css; charset=utf-8");
            } else {
                if ((strcmp(path, "/app.js") == 0)) {
                    nexus_serve_static(client_sock, "projects/02_nexus_game_studio/web/app.js", "application/javascript; charset=utf-8");
                } else {
                    if ((strcmp(path, "/api/game/state") == 0)) {
                        __auto_type p_energy = simulate_particle_field(64, 400, 300, req_seq);
                        __auto_type packed_player = nexus_integrate_physics((100 + ((req_seq * 4) % 600)), (100 + ((req_seq * 3) % 400)), 2, 3, 800, 600);
                        __auto_type px = (packed_player / 10000);
                        __auto_type py = (packed_player % 10000);
                        __auto_type active_room = allocate_game_room((8800 + req_seq), 1850);
                        __auto_type rank = compute_player_rank((50000 + ((req_seq * 731) % 60000)));
                        __auto_type sig = nexus_sign_session(99001, req_seq);
                        char* json_buf = (char*)malloc(2048 * sizeof(char));
                        sprintf(json_buf, "{\"framework\":\"%s\",\"tick\":%lld,\"fps\":120,\"player\":{\"id\":99001,\"x\":%lld,\"y\":%lld,\"rank\":%d,\"score\":%lld},\"physics\":{\"energy\":%lld,\"active_particles\":64,\"collisions\":2016},\"matchmaker\":{\"room_id\":%lld,\"ping_ms\":18,\"status\":\"InGame\"},\"session_signature\":%lld}", nexus_framework_version(), req_seq, px, py, rank, (50000 + ((req_seq * 731) % 60000)), p_energy, active_room, sig);
                        nexus_send_response(client_sock, "200 OK", "application/json; charset=utf-8", json_buf);
                    } else {
                        if ((strcmp(path, "/api/game/spawn") == 0)) {
                            char* json_spawn = (char*)malloc(512 * sizeof(char));
                            sprintf(json_spawn, "{\"status\":\"SPAWNED\",\"particle_id\":%lld,\"velocity_vector\":{\"vx\":4,\"vy\":-2},\"arena_sync_ms\":0.04}", req_seq);
                            nexus_send_response(client_sock, "200 OK", "application/json; charset=utf-8", json_spawn);
                        } else {
                            nexus_send_response(client_sock, "404 Not Found", "text/plain", "Route Not Found");
                        }
                    }
                }
            }
        }
        closesocket(client_sock);
    }
    end_arena_destroy(region_r);
}

int main(void) {
    end_println("============================================================");
    end_println("🎮 NEXUS 120 FPS GAME & REALTIME PHYSICS STUDIO (PORT 5050)");
    end_println("⚡ Powered by Custom Exclusive Framework: 'end_nexus'");
    end_println("🔗 Localhost URL: http://localhost:5050");
    end_println("============================================================");
    void* wsa_data = (char*)malloc(512 * sizeof(char));
    WSAStartup(514, wsa_data);
    __auto_type server_sock = socket(2, 1, 6);
    char* server_addr = (char*)malloc(32 * sizeof(char));
    memset(server_addr, 0, 32);
    server_addr[0] = 2;
    server_addr[1] = 0;
    server_addr[2] = 19;
    server_addr[3] = 186;
    int32_t* opt = (int32_t*)malloc(1 * sizeof(int32_t));
    opt[0] = 1;
    setsockopt(server_sock, 65535, 4, opt, 4);
    __auto_type bind_res = bind(server_sock, server_addr, 16);
    if ((bind_res >= 0)) {
        listen(server_sock, 128);
        end_println("Game Server listening on 0.0.0.0:5050...");
        int64_t req_seq = 1;
        while (true) {
            __auto_type client_sock = accept(server_sock, NULL, NULL);
            if (((client_sock == 4294967295) || (client_sock < 0))) {
                Sleep(10);
            } else {
                handle_game_client(client_sock, req_seq);
                req_seq = (req_seq + 1);
            }
        }
    } else {
        end_println("ERROR: Failed to bind socket on port 5050!");
    }
    closesocket(server_sock);
    WSACleanup();
    return 0;
}

