use crate::ast::*;

pub struct CBackend {
    output: String,
    indent_level: usize,
    enums: Vec<EnumDef>,
}

impl CBackend {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            enums: Vec::new(),
        }
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    fn find_enum_for_variant(&self, variant_name: &str) -> String {
        for e in &self.enums {
            if e.variants.iter().any(|v| v.name == variant_name) {
                return e.name.clone();
            }
        }
        "Enum".to_string()
    }

    pub fn generate(&mut self, module: &Module) -> String {
        self.output.clear();
        self.enums = module.enums.clone();

        // Standard includes
        self.output.push_str("/* Generated by End Language Compiler (endc) */\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <stdlib.h>\n");
        self.output.push_str("#include <stdint.h>\n");
        self.output.push_str("#include <stdbool.h>\n");
        self.output.push_str("#include <string.h>\n\n");

        // Native smart print helpers using C11 _Generic
        self.output.push_str("/* End Generic Print Helpers */\n");
        self.output.push_str("static inline void _end_print_str(const char* s) { printf(\"%s\\n\", s); }\n");
        self.output.push_str("static inline void _end_print_int(long long n) { printf(\"%lld\\n\", n); }\n");
        self.output.push_str("static inline void _end_print_float(double f) { printf(\"%f\\n\", f); }\n");
        self.output.push_str("#define end_println(X) _Generic((X), \\\n");
        self.output.push_str("    int: _end_print_int, \\\n");
        self.output.push_str("    long: _end_print_int, \\\n");
        self.output.push_str("    long long: _end_print_int, \\\n");
        self.output.push_str("    unsigned int: _end_print_int, \\\n");
        self.output.push_str("    unsigned long long: _end_print_int, \\\n");
        self.output.push_str("    float: _end_print_float, \\\n");
        self.output.push_str("    double: _end_print_float, \\\n");
        self.output.push_str("    char*: _end_print_str, \\\n");
        self.output.push_str("    const char*: _end_print_str)(X)\n\n");

        // Runtime memory primitives (Region & Allocator support)
        self.output.push_str("/* End Memory Primitives */\n");
        self.output.push_str("typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;\n");
        self.output.push_str("typedef struct { char* buffer; size_t capacity; size_t offset; } EndArena;\n");
        self.output.push_str("static EndArena* end_arena_create(size_t cap) {\n");
        self.output.push_str("    EndArena* a = (EndArena*)malloc(sizeof(EndArena));\n");
        self.output.push_str("    a->buffer = (char*)malloc(cap);\n");
        self.output.push_str("    a->capacity = cap;\n");
        self.output.push_str("    a->offset = 0;\n");
        self.output.push_str("    return a;\n");
        self.output.push_str("}\n");
        self.output.push_str("static void* end_arena_alloc(EndArena* a, size_t size) {\n");
        self.output.push_str("    if (a->offset + size > a->capacity) return NULL;\n");
        self.output.push_str("    void* ptr = (void*)(a->buffer + a->offset);\n");
        self.output.push_str("    a->offset += (size + 7) & ~7;\n");
        self.output.push_str("    return ptr;\n");
        self.output.push_str("}\n");
        self.output.push_str("static void end_arena_destroy(EndArena* a) {\n");
        self.output.push_str("    if (a) { free(a->buffer); free(a); }\n");
        self.output.push_str("}\n\n");

        // Process Imports
        for imp in &module.imports {
            match &imp.kind {
                ImportKind::C(path) => {
                    self.output.push_str(&format!("#include \"{}\"\n", path));
                }
                ImportKind::Zig(path) => {
                    self.output.push_str(&format!("/* Zig module: {} */\n", path));
                }
                ImportKind::Rust(path) => {
                    self.output.push_str(&format!("/* Rust crate: {} */\n", path));
                }
                _ => {}
            }
        }
        self.output.push('\n');

        // Forward declarations of Enums and Structs
        for e in &module.enums {
            self.output.push_str(&format!("typedef struct {} {};\n", e.name, e.name));
        }
        for s in &module.structs {
            self.output.push_str(&format!("typedef struct {} {};\n", s.name, s.name));
        }
        self.output.push('\n');

        // Enum Definitions (Tagged Unions)
        for e in &module.enums {
            self.output.push_str(&format!("typedef enum {{\n"));
            for v in &e.variants {
                self.output.push_str(&format!("    {}_{},\n", e.name, v.name));
            }
            self.output.push_str(&format!("}} {}_Tag;\n\n", e.name));

            self.output.push_str(&format!("struct {} {{\n", e.name));
            self.output.push_str(&format!("    {}_Tag tag;\n", e.name));
            let has_payload = e.variants.iter().any(|v| v.payload.is_some());
            if has_payload {
                self.output.push_str("    union {\n");
                for v in &e.variants {
                    if let Some(pty) = &v.payload {
                        self.output.push_str(&format!("        {} {};\n", self.map_type(pty), v.name));
                    }
                }
                self.output.push_str("    } data;\n");
            }
            self.output.push_str("};\n\n");
        }

        // Struct Definitions
        for s in &module.structs {
            self.output.push_str(&format!("struct {} {{\n", s.name));
            for f in &s.fields {
                let c_type = self.map_type(&f.field_type);
                self.output.push_str(&format!("    {} {};\n", c_type, f.name));
            }
            self.output.push_str("};\n\n");
        }

        // Forward declarations of functions
        for f in &module.functions {
            let ret_type = if f.name == "main" {
                "int".to_string()
            } else {
                self.map_type(&f.return_type)
            };
            let mut params_str = Vec::new();
            for p in &f.params {
                params_str.push(format!("{} {}", self.map_type(&p.param_type), p.name));
            }
            if params_str.is_empty() {
                params_str.push("void".to_string());
            }
            self.output.push_str(&format!("{} {}({});\n", ret_type, f.name, params_str.join(", ")));
        }
        self.output.push('\n');

        // Function Bodies
        for f in &module.functions {
            self.gen_function(f);
        }

        self.output.clone()
    }

    fn map_type(&self, ty: &Type) -> String {
        match ty {
            Type::Void => "void".to_string(),
            Type::Bool => "bool".to_string(),
            Type::I8 => "int8_t".to_string(),
            Type::I16 => "int16_t".to_string(),
            Type::I32 => "int32_t".to_string(),
            Type::I64 => "int64_t".to_string(),
            Type::U8 => "uint8_t".to_string(),
            Type::U16 => "uint16_t".to_string(),
            Type::U32 => "uint32_t".to_string(),
            Type::U64 => "uint64_t".to_string(),
            Type::F32 => "float".to_string(),
            Type::F64 => "double".to_string(),
            Type::Simd(inner, lanes) => format!("{}_vec{}", self.map_type(inner), lanes),
            Type::Str => "const char*".to_string(),
            Type::Custom(name) => name.clone(),
            Type::Pointer(inner) => format!("{}*", self.map_type(inner)),
            Type::Slice(inner) => format!("{}*", self.map_type(inner)),
            Type::Array(inner, size) => format!("{}[{}]", self.map_type(inner), size),
            Type::Tuple(_) => "void*".to_string(),
            Type::Generic(name, _) => name.clone(),
            Type::Result(inner, _) => self.map_type(inner),
            Type::Region(_) => "EndArena*".to_string(),
            Type::Allocator => "EndAllocator*".to_string(),
        }
    }

    fn gen_function(&mut self, func: &FunctionDef) {
        let ret_type = if func.name == "main" {
            "int".to_string()
        } else {
            self.map_type(&func.return_type)
        };

        let mut params_str = Vec::new();
        for p in &func.params {
            params_str.push(format!("{} {}", self.map_type(&p.param_type), p.name));
        }
        if params_str.is_empty() {
            params_str.push("void".to_string());
        }

        let fn_name = if func.name == "main" {
            "main".to_string()
        } else {
            func.name.clone()
        };

        self.output.push_str(&format!(
            "{} {}({}) {{\n",
            ret_type,
            fn_name,
            params_str.join(", ")
        ));

        self.indent_level += 1;
        for stmt in &func.body.statements {
            self.gen_statement(stmt);
        }
        if func.name == "main" {
            self.output.push_str(&format!("{}return 0;\n", self.indent()));
        }
        self.indent_level -= 1;
        self.output.push_str("}\n\n");
    }

    fn gen_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::VarDecl {
                name,
                var_type,
                initializer,
                ..
            } => {
                let ty_str = if let Some(t) = var_type {
                    self.map_type(t)
                } else {
                    "__auto_type".to_string()
                };

                if let Some(init) = initializer {
                    let init_str = self.gen_expression(init);
                    self.output.push_str(&format!(
                        "{}{} {} = {};\n",
                        self.indent(),
                        ty_str,
                        name,
                        init_str
                    ));
                } else {
                    self.output.push_str(&format!(
                        "{}{} {};\n",
                        self.indent(),
                        ty_str,
                        name
                    ));
                }
            }
            Statement::Assignment { target, value, .. } => {
                let target_str = self.gen_expression(target);
                let value_str = self.gen_expression(value);
                self.output.push_str(&format!(
                    "{}{} = {};\n",
                    self.indent(),
                    target_str,
                    value_str
                ));
            }
            Statement::Return { value, .. } => {
                if let Some(v) = value {
                    let val_str = self.gen_expression(v);
                    self.output.push_str(&format!("{}return {};\n", self.indent(), val_str));
                } else {
                    self.output.push_str(&format!("{}return;\n", self.indent()));
                }
            }
            Statement::Expression(expr) => {
                let expr_str = self.gen_expression(expr);
                self.output.push_str(&format!("{}{};\n", self.indent(), expr_str));
            }
            Statement::If {
                condition,
                then_block,
                else_block,
                ..
            } => {
                let cond_str = self.gen_expression(condition);
                self.output.push_str(&format!("{}if ({}) {{\n", self.indent(), cond_str));
                self.indent_level += 1;
                for s in &then_block.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                if let Some(eb) = else_block {
                    self.output.push_str(&format!("{}}} else {{\n", self.indent()));
                    self.indent_level += 1;
                    for s in &eb.statements {
                        self.gen_statement(s);
                    }
                    self.indent_level -= 1;
                }
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::While { condition, body, .. } => {
                let cond_str = self.gen_expression(condition);
                self.output.push_str(&format!("{}while ({}) {{\n", self.indent(), cond_str));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::ParallelFor {
                item_name,
                iterable,
                body,
                ..
            } => {
                let iter_str = self.gen_expression(iterable);
                self.output.push_str(&format!(
                    "{}#pragma omp parallel for\n",
                    self.indent()
                ));
                self.output.push_str(&format!(
                    "{}for (int32_t {} = 0; {} < {}; {}++) {{\n",
                    self.indent(),
                    item_name,
                    item_name,
                    iter_str,
                    item_name
                ));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::ForIn {
                item_name,
                iterable,
                body,
                ..
            } => {
                let iter_str = self.gen_expression(iterable);
                self.output.push_str(&format!(
                    "{}for (int32_t {} = 0; {} < {}; {}++) {{\n",
                    self.indent(),
                    item_name,
                    item_name,
                    iter_str,
                    item_name
                ));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::Match { expr, arms, .. } => {
                let expr_str = self.gen_expression(expr);
                self.output.push_str(&format!("{}switch (({}).tag) {{\n", self.indent(), expr_str));
                self.indent_level += 1;
                for arm in arms {
                    match &arm.pattern {
                        Pattern::Variant { variant_name, enum_name, binding } => {
                            let en = enum_name.clone().unwrap_or_else(|| self.find_enum_for_variant(variant_name));
                            self.output.push_str(&format!("{}case {}_{}: {{\n", self.indent(), en, variant_name));
                            self.indent_level += 1;
                            if let Some(b) = binding {
                                self.output.push_str(&format!("{}__auto_type {} = ({}).data.{};\n", self.indent(), b, expr_str, variant_name));
                            }
                            for s in &arm.body.statements {
                                self.gen_statement(s);
                            }
                            self.output.push_str(&format!("{}break;\n", self.indent()));
                            self.indent_level -= 1;
                            self.output.push_str(&format!("{}}}\n", self.indent()));
                        }
                        Pattern::Wildcard => {
                            self.output.push_str(&format!("{}default: {{\n", self.indent()));
                            self.indent_level += 1;
                            for s in &arm.body.statements {
                                self.gen_statement(s);
                            }
                            self.output.push_str(&format!("{}break;\n", self.indent()));
                            self.indent_level -= 1;
                            self.output.push_str(&format!("{}}}\n", self.indent()));
                        }
                        _ => {}
                    }
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::RegionBlock { name, body, .. } => {
                self.output.push_str(&format!(
                    "{}/* Enter Region: {} */\n",
                    self.indent(),
                    name
                ));
                self.output.push_str(&format!(
                    "{}EndArena* region_{} = end_arena_create(64 * 1024);\n",
                    self.indent(),
                    name
                ));
                self.output.push_str(&format!("{}{{\n", self.indent()));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
                self.output.push_str(&format!(
                    "{}end_arena_destroy(region_{});\n",
                    self.indent(),
                    name
                ));
            }
            Statement::AsmBlock { arch, code, .. } => {
                self.output.push_str(&format!(
                    "{}/* Inline Assembly: {} */\n",
                    self.indent(),
                    arch
                ));
                for line in code.lines() {
                    self.output.push_str(&format!(
                        "{}__asm__ volatile(\"{}\\n\\t\");\n",
                        self.indent(),
                        line.trim().replace('"', "\\\"")
                    ));
                }
            }
            Statement::TargetBlock { target, body, .. } => {
                self.output.push_str(&format!("{}#ifdef TARGET_{}\n", self.indent(), target.to_uppercase()));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}#endif\n", self.indent()));
            }
            Statement::Defer { expr, .. } => {
                let expr_str = self.gen_expression(expr);
                self.output.push_str(&format!("{}/* defer */ {};\n", self.indent(), expr_str));
            }
        }
    }

    fn gen_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::Lit(lit, _) => match lit {
                Literal::Int(n) => n.to_string(),
                Literal::Float(f) => format!("{:.6}f", f),
                Literal::String(s) => format!("\"{}\"", s.replace('\n', "\\n")),
                Literal::Bool(b) => if *b { "true".to_string() } else { "false".to_string() },
                Literal::Null => "NULL".to_string(),
            },
            Expression::Ident(name, _) => name.clone(),
            Expression::Binary { left, op, right, .. } => {
                let l = self.gen_expression(left);
                let r = self.gen_expression(right);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Equal => "==",
                    BinaryOp::NotEqual => "!=",
                    BinaryOp::LessThan => "<",
                    BinaryOp::LessEqual => "<=",
                    BinaryOp::GreaterThan => ">",
                    BinaryOp::GreaterEqual => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expression::Unary { op, expr, .. } => {
                let e = self.gen_expression(expr);
                match op {
                    UnaryOp::Negate => format!("(-{})", e),
                    UnaryOp::Not => format!("(!{})", e),
                    UnaryOp::AddressOf => format!("(&{})", e),
                    UnaryOp::Deref => format!("(*{})", e),
                }
            }
            Expression::Call { callee, args, .. } => {
                let callee_str = self.gen_expression(callee);
                if callee_str == "println" {
                    if let Some(first_arg) = args.first() {
                        let arg_str = self.gen_expression(first_arg);
                        return format!("end_println({})", arg_str);
                    }
                }

                let mut args_str = Vec::new();
                for a in args {
                    args_str.push(self.gen_expression(a));
                }
                format!("{}({})", callee_str, args_str.join(", "))
            }
            Expression::FieldAccess { object, field, .. } => {
                let obj_str = self.gen_expression(object);
                format!("{}.{}", obj_str, field)
            }
            Expression::StructInit { name, fields, .. } => {
                let mut field_inits = Vec::new();
                for (fname, fval) in fields {
                    field_inits.push(format!(".{} = {}", fname, self.gen_expression(fval)));
                }
                format!("({}){{ {} }}", name, field_inits.join(", "))
            }
            Expression::EnumInit { enum_name, variant_name, payload, .. } => {
                let en = enum_name.clone().unwrap_or_else(|| self.find_enum_for_variant(variant_name));
                if let Some(p) = payload {
                    format!("({}){{ .tag = {}_{}, .data.{} = {} }}", en, en, variant_name, variant_name, self.gen_expression(p))
                } else {
                    format!("({}){{ .tag = {}_{} }}", en, en, variant_name)
                }
            }
            Expression::Alloc { target_type, .. } => {
                format!("({}*)malloc(sizeof({}))", self.map_type(target_type), self.map_type(target_type))
            }
            Expression::Catch { expr, .. } => {
                self.gen_expression(expr)
            }
            Expression::Match { .. } => "0".to_string(),
            Expression::Block(_) => "0".to_string(),
        }
    }
}
