use crate::ast::*;
use std::collections::{HashMap, HashSet};

pub struct CBackend {
    output: String,
    header_output: String,
    indent_level: usize,
    enums: Vec<EnumDef>,
    is_lib: bool,
    pub var_types: HashMap<String, Type>,
    pub active_regions: Vec<String>,
    pub struct_methods: HashMap<String, HashSet<String>>,
    pub module_methods: HashMap<String, HashSet<String>>,
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            other => out.push(other),
        }
    }
    out
}

impl CBackend {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            header_output: String::new(),
            indent_level: 0,
            enums: Vec::new(),
            is_lib: false,
            var_types: HashMap::new(),
            active_regions: Vec::new(),
            struct_methods: HashMap::new(),
            module_methods: HashMap::new(),
        }
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    fn find_enum_for_variant(&self, variant_name: &str) -> String {
        for e in &self.enums {
            if e.variants.iter().any(|v| v.name == variant_name) {
                return e.name.clone();
            }
        }
        "Enum".to_string()
    }

    pub fn generate(&mut self, module: &Module) -> String {
        let (c_code, _) = self.generate_with_options(module, false);
        c_code
    }

    pub fn generate_with_options(&mut self, module: &Module, is_lib: bool) -> (String, Option<String>) {
        self.output.clear();
        self.header_output.clear();
        self.is_lib = is_lib;
        self.enums = module.enums.clone();

        // Standard includes
        self.output.push_str("/* Generated by End Language Compiler (endc) — Hyper-Optimized Native Output */\n");
        self.output.push_str("#define BUILDING_END_DLL 1\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <assert.h>\n");
        self.output.push_str("#include <stdlib.h>\n");
        self.output.push_str("#include <stdint.h>\n");
        self.output.push_str("#include <stdbool.h>\n");
                self.output.push_str("#include <string.h>\n");
        self.output.push_str("static inline char* _end_str_concat(const char* a, const char* b) {\n");
        self.output.push_str("    if (!a) a = \"\";\n");
        self.output.push_str("    if (!b) b = \"\";\n");
        self.output.push_str("    size_t la = strlen(a);\n");
        self.output.push_str("    size_t lb = strlen(b);\n");
        self.output.push_str("    char* res = (char*)malloc(la + lb + 1);\n");
        self.output.push_str("    if (!res) return (char*)\"\";\n");
        self.output.push_str("    memcpy(res, a, la);\n");
        self.output.push_str("    memcpy(res + la, b, lb);\n");
        self.output.push_str("    res[la + lb] = '\\0';\n");
        self.output.push_str("    return res;\n");
        self.output.push_str("}\n");
        self.output.push_str("#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)\n    #include <immintrin.h>\n#elif defined(__aarch64__) || defined(_M_ARM64)\n    #include <arm_neon.h>\n#endif\n\n");

        // Hardware Watchdog & CPU Throttling Hooks
        self.output.push_str("/* End Hardware Watchdog & CPU Throttling Safety Hooks */\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("    #define WIN32_LEAN_AND_MEAN\n");
        self.output.push_str("    #include <windows.h>\n");
        self.output.push_str("    #define END_CPU_YIELD() SwitchToThread()\n");
        self.output.push_str("    #define END_CPU_RELAX() YieldProcessor()\n");
        self.output.push_str("    #define END_CPU_SLEEP(ms) Sleep(ms)\n");
        self.output.push_str("#else\n");
        self.output.push_str("    #include <sched.h>\n");
        self.output.push_str("    #include <unistd.h>\n");
        self.output.push_str("    #include <time.h>\n");
        self.output.push_str("    #define END_CPU_YIELD() sched_yield()\n");
        self.output.push_str("    #define END_CPU_RELAX() __builtin_ia32_pause()\n");
        self.output.push_str("    #define END_CPU_SLEEP(ms) usleep((ms) * 1000)\n");
        self.output.push_str("#endif\n\n");
        self.output.push_str("static inline void cpu_yield(void) { END_CPU_YIELD(); }\n");
        self.output.push_str("static inline void cpu_relax(void) { END_CPU_RELAX(); }\n");
        self.output.push_str("static inline void cpu_sleep_ms(int32_t ms) { END_CPU_SLEEP(ms); }\n");
        self.output.push_str("static inline uint64_t high_res_time_ns(void) {\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("    LARGE_INTEGER count, freq;\n");
        self.output.push_str("    QueryPerformanceCounter(&count);\n");
        self.output.push_str("    QueryPerformanceFrequency(&freq);\n");
        self.output.push_str("    return (uint64_t)((count.QuadPart * 1000000000ULL) / freq.QuadPart);\n");
        self.output.push_str("#else\n");
        self.output.push_str("    struct timespec ts;\n");
        self.output.push_str("    clock_gettime(CLOCK_MONOTONIC, &ts);\n");
        self.output.push_str("    return (uint64_t)(ts.tv_sec * 1000000000ULL + ts.tv_nsec);\n");
        self.output.push_str("#endif\n");
        self.output.push_str("}\n\n");

        // Export macro for DLL / Shared Object support
        self.output.push_str("/* End Cross-Platform Export API Macro */\n");
        self.output.push_str("#if defined(_WIN32) || defined(__CYGWIN__)\n");
        self.output.push_str("    #define END_API __declspec(dllexport)\n");
        self.output.push_str("#elif defined(__GNUC__) || defined(__clang__)\n");
        self.output.push_str("    #define END_API __attribute__((visibility(\"default\")))\n");
        self.output.push_str("#else\n");
        self.output.push_str("    #define END_API\n");
        self.output.push_str("#endif\n\n");

        // Native smart print helpers using C11 _Generic
        self.output.push_str("/* End Generic Print & Math Prelude Helpers (Zero-Import Available) */\n");
        self.output.push_str("static inline void _end_print_str(const char* s) { printf(\"%s\\n\", s); }\n");
        self.output.push_str("static inline void _end_print_int(long long n) { printf(\"%lld\\n\", n); }\n");
        self.output.push_str("static inline void _end_print_float(double f) { printf(\"%f\\n\", f); }\n");
        self.output.push_str("static inline void _end_print_bool(bool b) { printf(\"%s\\n\", b ? \"true\" : \"false\"); }\n");
        self.output.push_str("#define end_println(X) _Generic((X), \\\n");
        self.output.push_str("    bool: _end_print_bool, \\\n");
        self.output.push_str("    int: _end_print_int, \\\n");
        self.output.push_str("    long: _end_print_int, \\\n");
        self.output.push_str("    long long: _end_print_int, \\\n");
        self.output.push_str("    unsigned int: _end_print_int, \\\n");
        self.output.push_str("    unsigned long long: _end_print_int, \\\n");
        self.output.push_str("    float: _end_print_float, \\\n");
        self.output.push_str("    double: _end_print_float, \\\n");
        self.output.push_str("    char*: _end_print_str, \\\n");
        self.output.push_str("    const char*: _end_print_str)(X)\n\n");

        // Runtime memory primitives (Hardware Scratchpad TLS Bump Arena)
        self.output.push_str("/* End Zero-Cost Memory Primitives (64-byte Cache-Line Aligned) */\n");
        self.output.push_str("typedef struct { void* (*alloc)(size_t); void (*free)(void*); } EndAllocator;\n");
        self.output.push_str("typedef struct { char* buffer; size_t capacity; size_t offset; bool is_heap; } EndArena;\n");
        self.output.push_str("#if defined(_MSC_VER)\n");
        self.output.push_str("    static __declspec(thread) char _end_tls_scratchpad[4 * 1024 * 1024];\n");
        self.output.push_str("    static __declspec(thread) size_t _end_tls_offset = 0;\n");
        self.output.push_str("#else\n");
        self.output.push_str("    static __thread char _end_tls_scratchpad[4 * 1024 * 1024];\n");
        self.output.push_str("    static __thread size_t _end_tls_offset = 0;\n");
        self.output.push_str("#endif\n\n");
        self.output.push_str("static inline EndArena* end_arena_create(size_t cap) {\n");
        self.output.push_str("    if (_end_tls_offset + sizeof(EndArena) + cap <= sizeof(_end_tls_scratchpad)) {\n");
        self.output.push_str("        EndArena* a = (EndArena*)(_end_tls_scratchpad + _end_tls_offset);\n");
        self.output.push_str("        _end_tls_offset += (sizeof(EndArena) + 63) & ~63;\n");
        self.output.push_str("        a->buffer = _end_tls_scratchpad + _end_tls_offset;\n");
        self.output.push_str("        _end_tls_offset += (cap + 63) & ~63;\n");
        self.output.push_str("        a->capacity = cap;\n");
        self.output.push_str("        a->offset = 0;\n");
        self.output.push_str("        a->is_heap = false;\n");
        self.output.push_str("        return a;\n");
        self.output.push_str("    }\n");
        self.output.push_str("    EndArena* a = (EndArena*)malloc(sizeof(EndArena));\n");
        self.output.push_str("    a->buffer = (char*)malloc(cap);\n");
        self.output.push_str("    a->capacity = cap;\n");
        self.output.push_str("    a->offset = 0;\n");
        self.output.push_str("    a->is_heap = true;\n");
        self.output.push_str("    return a;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void* end_arena_alloc(EndArena* a, size_t size) {\n");
        self.output.push_str("    size_t aligned = (size + 63) & ~63;\n");
        self.output.push_str("    if (a->offset + aligned > a->capacity) return NULL;\n");
        self.output.push_str("    void* ptr = (void*)(a->buffer + a->offset);\n");
        self.output.push_str("    a->offset += aligned;\n");
        self.output.push_str("    return ptr;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void end_arena_destroy(EndArena* a) {\n");
        self.output.push_str("    if (!a) return;\n");
        self.output.push_str("    if (a->is_heap) { free(a->buffer); free(a); }\n");
        self.output.push_str("    else { _end_tls_offset = 0; }\n");
        self.output.push_str("}\n\n");

        // Native Desktop Windowing & GUI Runtime
        self.output.push_str("/* End Native Desktop Windowing Runtime */\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("#define WIN32_LEAN_AND_MEAN\n");
        self.output.push_str("#include <windows.h>\n");
        self.output.push_str("typedef struct EndWindow {\n");
        self.output.push_str("    HWND hwnd;\n");
        self.output.push_str("    HDC hdc;\n");
        self.output.push_str("    int32_t width;\n");
        self.output.push_str("    int32_t height;\n");
        self.output.push_str("    bool is_open;\n");
        self.output.push_str("    BITMAPINFO bmi;\n");
        self.output.push_str("} EndWindow;\n");
        self.output.push_str("static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {\n");
        self.output.push_str("    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }\n");
        self.output.push_str("    return DefWindowProcA(hWnd, msg, wParam, lParam);\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {\n");
        self.output.push_str("    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));\n");
        self.output.push_str("    win->width = width;\n");
        self.output.push_str("    win->height = height;\n");
        self.output.push_str("    win->is_open = true;\n");
        self.output.push_str("    HINSTANCE hInstance = GetModuleHandle(NULL);\n");
        self.output.push_str("    WNDCLASSEXA wc = {0};\n");
        self.output.push_str("    wc.cbSize = sizeof(WNDCLASSEXA);\n");
        self.output.push_str("    wc.lpfnWndProc = EndWndProc;\n");
        self.output.push_str("    wc.hInstance = hInstance;\n");
        self.output.push_str("    wc.hCursor = LoadCursor(NULL, IDC_ARROW);\n");
        self.output.push_str("    wc.lpszClassName = \"EndNativeWindow\";\n");
        self.output.push_str("    RegisterClassExA(&wc);\n");
        self.output.push_str("    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);\n");
        self.output.push_str("    win->bmi.bmiHeader.biWidth = width;\n");
        self.output.push_str("    win->bmi.bmiHeader.biHeight = -height;\n");
        self.output.push_str("    win->bmi.bmiHeader.biPlanes = 1;\n");
        self.output.push_str("    win->bmi.bmiHeader.biBitCount = 32;\n");
        self.output.push_str("    win->bmi.bmiHeader.biCompression = BI_RGB;\n");
        self.output.push_str("    win->hwnd = CreateWindowExA(0, \"EndNativeWindow\", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);\n");
        self.output.push_str("    win->hdc = GetDC(win->hwnd);\n");
        self.output.push_str("    ShowWindow(win->hwnd, SW_SHOW);\n");
        self.output.push_str("    UpdateWindow(win->hwnd);\n");
        self.output.push_str("    return win;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline bool window_poll(EndWindow* win) {\n");
        self.output.push_str("    if (!win) return false;\n");
        self.output.push_str("    MSG msg;\n");
        self.output.push_str("    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {\n");
        self.output.push_str("        if (msg.message == WM_QUIT) { win->is_open = false; return false; }\n");
        self.output.push_str("        TranslateMessage(&msg);\n");
        self.output.push_str("        DispatchMessageA(&msg);\n");
        self.output.push_str("    }\n");
        self.output.push_str("    return win->is_open;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void window_present(EndWindow* win, uint32_t* pixels) {\n");
        self.output.push_str("    if (!win || !win->is_open || !pixels) return;\n");
        self.output.push_str("    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void window_sleep(int32_t ms) {\n");
        self.output.push_str("    Sleep(ms);\n");
        self.output.push_str("}\n");
        self.output.push_str("#else\n");
        self.output.push_str("typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;\n");
        self.output.push_str("static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }\n");
        self.output.push_str("static inline bool window_poll(EndWindow* win) { return false; }\n");
        self.output.push_str("static inline void window_present(EndWindow* win, uint32_t* pixels) {}\n");
        self.output.push_str("static inline void window_sleep(int32_t ms) {}\n");
        self.output.push_str("#endif\n\n");

        // Hybrid 3-Tier Memory Model & Region Promotion
        self.output.push_str("/* Hybrid 3-Tier Memory Model Runtime */\n");
        self.output.push_str("typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;\n");
        self.output.push_str("static inline void* end_rc_new(size_t size, const void* src) {\n");
        self.output.push_str("    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);\n");
        self.output.push_str("    h->ref_count = 1;\n");
        self.output.push_str("    if (src) memcpy(h->data, src, size);\n");
        self.output.push_str("    return (void*)h->data;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void* end_rc_clone(void* ptr) {\n");
        self.output.push_str("    if (!ptr) return NULL;\n");
        self.output.push_str("    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));\n");
        self.output.push_str("    h->ref_count++;\n");
        self.output.push_str("    return ptr;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void end_rc_drop(void* ptr) {\n");
        self.output.push_str("    if (!ptr) return;\n");
        self.output.push_str("    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));\n");
        self.output.push_str("    h->ref_count--;\n");
        self.output.push_str("    if (h->ref_count <= 0) free(h);\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {\n");
        self.output.push_str("    if (!ptr || !target_arena) return ptr;\n");
        self.output.push_str("    void* new_ptr = end_arena_alloc(target_arena, size);\n");
        self.output.push_str("    if (new_ptr) memcpy(new_ptr, ptr, size);\n");
        self.output.push_str("    return new_ptr ? new_ptr : ptr;\n");
        self.output.push_str("}\n\n");

        // Concurrency & Channel Primitives
        self.output.push_str("/* End Lightweight Concurrency & Channel Runtime */\n");
        self.output.push_str("typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;\n");
        self.output.push_str("static inline EndChannel* channel_create(int32_t cap) {\n");
        self.output.push_str("    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));\n");
        self.output.push_str("    ch->buffer = (void**)malloc(sizeof(void*) * cap);\n");
        self.output.push_str("    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;\n");
        self.output.push_str("    return ch;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void channel_send(EndChannel* ch, void* val) {\n");
        self.output.push_str("    if (ch->count < ch->capacity) {\n");
        self.output.push_str("        ch->buffer[ch->tail] = val;\n");
        self.output.push_str("        ch->tail = (ch->tail + 1) % ch->capacity;\n");
        self.output.push_str("        ch->count++;\n");
        self.output.push_str("    }\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline void* channel_recv(EndChannel* ch) {\n");
        self.output.push_str("    if (ch->count == 0) return NULL;\n");
        self.output.push_str("    void* val = ch->buffer[ch->head];\n");
        self.output.push_str("        ch->head = (ch->head + 1) % ch->capacity;\n");
        self.output.push_str("        ch->count--;\n");
        self.output.push_str("    return val;\n");
        self.output.push_str("}\n\n");

        // High-Resolution Hardware Timer Runtime
        self.output.push_str("/* End High-Resolution Hardware Timer Runtime (std::time) */\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("static inline uint64_t end_time_now_nanos(void) {\n");
        self.output.push_str("    LARGE_INTEGER freq, counter;\n");
        self.output.push_str("    QueryPerformanceFrequency(&freq);\n");
        self.output.push_str("    QueryPerformanceCounter(&counter);\n");
        self.output.push_str("    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline uint64_t end_time_now_micros(void) {\n");
        self.output.push_str("    LARGE_INTEGER freq, counter;\n");
        self.output.push_str("    QueryPerformanceFrequency(&freq);\n");
        self.output.push_str("    QueryPerformanceCounter(&counter);\n");
        self.output.push_str("    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline uint64_t end_time_now_millis(void) {\n");
        self.output.push_str("    LARGE_INTEGER freq, counter;\n");
        self.output.push_str("    QueryPerformanceFrequency(&freq);\n");
        self.output.push_str("    QueryPerformanceCounter(&counter);\n");
        self.output.push_str("    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);\n");
        self.output.push_str("}\n");
        self.output.push_str("#else\n");
        self.output.push_str("#include <time.h>\n");
        self.output.push_str("static inline uint64_t end_time_now_nanos(void) {\n");
        self.output.push_str("    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);\n");
        self.output.push_str("    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;\n");
        self.output.push_str("}\n");
        self.output.push_str("static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }\n");
        self.output.push_str("static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }\n");
        self.output.push_str("#endif\n\n");

        // Real Cross-Platform Native Socket Primitives
        self.output.push_str("/* End Real Native Socket Primitives (Cross-Platform WinSock2 / POSIX) */\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("    #include <winsock2.h>\n");
        self.output.push_str("    #include <ws2tcpip.h>\n");
        self.output.push_str("    #pragma comment(lib, \"ws2_32.lib\")\n");
        self.output.push_str("    static inline void _end_socket_init(void) {\n");
        self.output.push_str("        static bool _inited = false;\n");
        self.output.push_str("        if (!_inited) { WSADATA wsa; WSAStartup(MAKEWORD(2, 2), &wsa); _inited = true; }\n");
        self.output.push_str("    }\n");
        self.output.push_str("    typedef SOCKET EndSocket;\n");
        self.output.push_str("    #define END_INVALID_SOCKET INVALID_SOCKET\n");
        self.output.push_str("    #define END_SOCKET_ERROR SOCKET_ERROR\n");
        self.output.push_str("    static inline void _end_socket_close(EndSocket s) { closesocket(s); }\n");
        self.output.push_str("#else\n");
        self.output.push_str("    #include <sys/types.h>\n");
        self.output.push_str("    #include <sys/socket.h>\n");
        self.output.push_str("    #include <netinet/in.h>\n");
        self.output.push_str("    #include <arpa/inet.h>\n");
        self.output.push_str("    #include <netdb.h>\n");
        self.output.push_str("    #include <unistd.h>\n");
        self.output.push_str("    #include <fcntl.h>\n");
        self.output.push_str("    static inline void _end_socket_init(void) {}\n");
        self.output.push_str("    typedef int EndSocket;\n");
        self.output.push_str("    #define END_INVALID_SOCKET (-1)\n");
        self.output.push_str("    #define END_SOCKET_ERROR (-1)\n");
        self.output.push_str("    static inline void _end_socket_close(EndSocket s) { close(s); }\n");
        self.output.push_str("#endif\n\n");

        self.output.push_str("static inline int64_t end_net_tcp_listen(int32_t port, int32_t backlog) {\n");
        self.output.push_str("    _end_socket_init();\n");
        self.output.push_str("    EndSocket s = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);\n");
        self.output.push_str("    if (s == END_INVALID_SOCKET) return -1;\n");
        self.output.push_str("    int opt = 1;\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (const char*)&opt, sizeof(opt));\n");
        self.output.push_str("#else\n");
        self.output.push_str("    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));\n");
        self.output.push_str("#endif\n");
        self.output.push_str("    struct sockaddr_in addr;\n");
        self.output.push_str("    memset(&addr, 0, sizeof(addr));\n");
        self.output.push_str("    addr.sin_family = AF_INET;\n");
        self.output.push_str("    addr.sin_addr.s_addr = INADDR_ANY;\n");
        self.output.push_str("    addr.sin_port = htons((uint16_t)port);\n");
        self.output.push_str("    if (bind(s, (struct sockaddr*)&addr, sizeof(addr)) == END_SOCKET_ERROR) { _end_socket_close(s); return -1; }\n");
        self.output.push_str("    if (listen(s, backlog > 0 ? backlog : 128) == END_SOCKET_ERROR) { _end_socket_close(s); return -1; }\n");
        self.output.push_str("    return (int64_t)s;\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline int64_t end_net_tcp_accept(int64_t server_fd) {\n");
        self.output.push_str("    if (server_fd < 0) return -1;\n");
        self.output.push_str("    struct sockaddr_in client_addr;\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("    int addr_len = sizeof(client_addr);\n");
        self.output.push_str("#else\n");
        self.output.push_str("    socklen_t addr_len = sizeof(client_addr);\n");
        self.output.push_str("#endif\n");
        self.output.push_str("    EndSocket client = accept((EndSocket)server_fd, (struct sockaddr*)&client_addr, &addr_len);\n");
        self.output.push_str("    if (client == END_INVALID_SOCKET) return -1;\n");
        self.output.push_str("    return (int64_t)client;\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline int64_t end_net_tcp_connect(const char* host, int32_t port) {\n");
        self.output.push_str("    _end_socket_init();\n");
        self.output.push_str("    EndSocket s = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);\n");
        self.output.push_str("    if (s == END_INVALID_SOCKET) return -1;\n");
        self.output.push_str("    struct sockaddr_in addr;\n");
        self.output.push_str("    memset(&addr, 0, sizeof(addr));\n");
        self.output.push_str("    addr.sin_family = AF_INET;\n");
        self.output.push_str("    addr.sin_port = htons((uint16_t)port);\n");
        self.output.push_str("    if (inet_pton(AF_INET, host, &addr.sin_addr) <= 0) {\n");
        self.output.push_str("        struct hostent* he = gethostbyname(host);\n");
        self.output.push_str("        if (!he) { _end_socket_close(s); return -1; }\n");
        self.output.push_str("        memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);\n");
        self.output.push_str("    }\n");
        self.output.push_str("    if (connect(s, (struct sockaddr*)&addr, sizeof(addr)) == END_SOCKET_ERROR) { _end_socket_close(s); return -1; }\n");
        self.output.push_str("    return (int64_t)s;\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline int64_t end_net_tcp_send(int64_t fd, const char* data, int64_t len) {\n");
        self.output.push_str("    if (fd < 0 || !data) return -1;\n");
        self.output.push_str("    int64_t to_send = len >= 0 ? len : (int64_t)strlen(data);\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("    int sent = send((EndSocket)fd, data, (int)to_send, 0);\n");
        self.output.push_str("#else\n");
        self.output.push_str("    ssize_t sent = send((EndSocket)fd, data, (size_t)to_send, 0);\n");
        self.output.push_str("#endif\n");
        self.output.push_str("    return (int64_t)sent;\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline char* end_net_tcp_recv(int64_t fd, int32_t max_bytes) {\n");
        self.output.push_str("    if (fd < 0 || max_bytes <= 0) return (char*)\"\";\n");
        self.output.push_str("    char* buf = (char*)malloc(max_bytes + 1);\n");
        self.output.push_str("    if (!buf) return (char*)\"\";\n");
        self.output.push_str("#if defined(_WIN32)\n");
        self.output.push_str("    int n = recv((EndSocket)fd, buf, max_bytes, 0);\n");
        self.output.push_str("#else\n");
        self.output.push_str("    ssize_t n = recv((EndSocket)fd, buf, (size_t)max_bytes, 0);\n");
        self.output.push_str("#endif\n");
        self.output.push_str("    if (n <= 0) { free(buf); return (char*)\"\"; }\n");
        self.output.push_str("    buf[n] = '\\0';\n");
        self.output.push_str("    return buf;\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline void end_net_tcp_close(int64_t fd) {\n");
        self.output.push_str("    if (fd >= 0) _end_socket_close((EndSocket)fd);\n");
        self.output.push_str("}\n\n");

        // Embedded Real Database Engine Primitives (Key-Value & In-Memory/File SQLite-compatible)
        self.output.push_str("/* End Real Embedded SQLite-Compatible Database Engine Primitives */\n");
        self.output.push_str("typedef struct EndDbRecord { char key[128]; char value[1024]; struct EndDbRecord* next; } EndDbRecord;\n");
        self.output.push_str("typedef struct EndDbHandle { char path[260]; bool is_open; EndDbRecord* head; int64_t rows_count; } EndDbHandle;\n");
        self.output.push_str("static inline EndDbHandle* end_db_open(const char* path) {\n");
        self.output.push_str("    EndDbHandle* db = (EndDbHandle*)malloc(sizeof(EndDbHandle));\n");
        self.output.push_str("    if (!db) return NULL;\n");
        self.output.push_str("    strncpy(db->path, path ? path : \":memory:\", sizeof(db->path) - 1);\n");
        self.output.push_str("    db->is_open = true; db->head = NULL; db->rows_count = 0;\n");
        self.output.push_str("    if (path && strcmp(path, \":memory:\") != 0) {\n");
        self.output.push_str("        FILE* f = fopen(path, \"r\");\n");
        self.output.push_str("        if (f) {\n");
        self.output.push_str("            char k[128], v[1024];\n");
        self.output.push_str("            while (fscanf(f, \"%127[^=]=%1023[^\\n]\\n\", k, v) == 2) {\n");
        self.output.push_str("                EndDbRecord* rec = (EndDbRecord*)malloc(sizeof(EndDbRecord));\n");
        self.output.push_str("                strncpy(rec->key, k, sizeof(rec->key) - 1);\n");
        self.output.push_str("                strncpy(rec->value, v, sizeof(rec->value) - 1);\n");
        self.output.push_str("                rec->next = db->head; db->head = rec; db->rows_count++;\n");
        self.output.push_str("            }\n");
        self.output.push_str("            fclose(f);\n");
        self.output.push_str("        }\n");
        self.output.push_str("    }\n");
        self.output.push_str("    return db;\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline int64_t end_db_execute(EndDbHandle* db, const char* key, const char* val) {\n");
        self.output.push_str("    if (!db || !db->is_open || !key) return 0;\n");
        self.output.push_str("    EndDbRecord* curr = db->head;\n");
        self.output.push_str("    while (curr) {\n");
        self.output.push_str("        if (strcmp(curr->key, key) == 0) {\n");
        self.output.push_str("            strncpy(curr->value, val ? val : \"\", sizeof(curr->value) - 1);\n");
        self.output.push_str("            return 1;\n");
        self.output.push_str("        }\n");
        self.output.push_str("        curr = curr->next;\n");
        self.output.push_str("    }\n");
        self.output.push_str("    EndDbRecord* rec = (EndDbRecord*)malloc(sizeof(EndDbRecord));\n");
        self.output.push_str("    strncpy(rec->key, key, sizeof(rec->key) - 1);\n");
        self.output.push_str("    strncpy(rec->value, val ? val : \"\", sizeof(rec->value) - 1);\n");
        self.output.push_str("    rec->next = db->head; db->head = rec; db->rows_count++;\n");
        self.output.push_str("    if (strcmp(db->path, \":memory:\") != 0) {\n");
        self.output.push_str("        FILE* f = fopen(db->path, \"w\");\n");
        self.output.push_str("        if (f) {\n");
        self.output.push_str("            EndDbRecord* p = db->head;\n");
        self.output.push_str("            while (p) { fprintf(f, \"%s=%s\\n\", p->key, p->value); p = p->next; }\n");
        self.output.push_str("            fclose(f);\n");
        self.output.push_str("        }\n");
        self.output.push_str("    }\n");
        self.output.push_str("    return 1;\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline char* end_db_query(EndDbHandle* db, const char* key) {\n");
        self.output.push_str("    if (!db || !db->is_open || !key) return (char*)\"\";\n");
        self.output.push_str("    EndDbRecord* curr = db->head;\n");
        self.output.push_str("    while (curr) {\n");
        self.output.push_str("        if (strcmp(curr->key, key) == 0) return curr->value;\n");
        self.output.push_str("        curr = curr->next;\n");
        self.output.push_str("    }\n");
        self.output.push_str("    return (char*)\"\";\n");
        self.output.push_str("}\n\n");

        self.output.push_str("static inline void end_db_close(EndDbHandle* db) {\n");
        self.output.push_str("    if (!db) return;\n");
        self.output.push_str("    EndDbRecord* curr = db->head;\n");
        self.output.push_str("    while (curr) { EndDbRecord* next = curr->next; free(curr); curr = next; }\n");
        self.output.push_str("    free(db);\n");
        self.output.push_str("}\n\n");

        // Process Imports
        for imp in &module.imports {
            match &imp.kind {
                ImportKind::C(path) => {
                    if path.starts_with('<') && path.ends_with('>') {
                        self.output.push_str(&format!("#include {}\n", path));
                    } else {
                        self.output.push_str(&format!("#include \"{}\"\n", path));
                    }
                }
                ImportKind::Zig(path) => {
                    self.output.push_str(&format!("/* Zig module: {} */\n", path));
                }
                ImportKind::Rust(path) => {
                    self.output.push_str(&format!("/* Rust crate: {} */\n", path));
                }
                _ => {}
            }
        }
        self.output.push('\n');

        // Forward declarations of Enums and Structs
        for e in &module.enums {
            self.output.push_str(&format!("typedef struct {} {};\n", e.name, e.name));
        }
        for s in &module.structs {
            self.output.push_str(&format!("typedef struct {} {};\n", s.name, s.name));
        }
        self.output.push('\n');

        // Enum Definitions (Tagged Unions)
        for e in &module.enums {
            self.output.push_str(&format!("typedef enum {{\n"));
            for v in &e.variants {
                self.output.push_str(&format!("    {}_{},\n", e.name, v.name));
            }
            self.output.push_str(&format!("}} {}_Tag;\n\n", e.name));

            self.output.push_str(&format!("struct {} {{\n", e.name));
            self.output.push_str(&format!("    {}_Tag tag;\n", e.name));
            let has_payload = e.variants.iter().any(|v| v.payload.is_some());
            if has_payload {
                self.output.push_str("    union {\n");
                for v in &e.variants {
                    if let Some(pty) = &v.payload {
                        self.output.push_str(&format!("        {} {};\n", self.map_type(pty), v.name));
                    }
                }
                self.output.push_str("    } data;\n");
            }
            self.output.push_str("};\n\n");
        }

        // Struct Definitions
        for s in &module.structs {
            self.output.push_str(&format!("struct {} {{\n", s.name));
            for f in &s.fields {
                let c_type = self.map_type(&f.field_type);
                self.output.push_str(&format!("    {} {};\n", c_type, f.name));
            }
            self.output.push_str("};\n\n");
        }

        // Header generation if in Library Mode
        if is_lib {
            self.header_output.push_str("/* End Language Generated C Header File */\n");
            self.header_output.push_str("#pragma once\n\n");
            self.header_output.push_str("#include <stdint.h>\n");
            self.header_output.push_str("#include <stdbool.h>\n\n");
            self.header_output.push_str("#if defined(_WIN32) || defined(__CYGWIN__)\n");
            self.header_output.push_str("    #ifdef BUILDING_END_DLL\n");
            self.header_output.push_str("        #define END_API __declspec(dllexport)\n");
            self.header_output.push_str("    #else\n");
            self.header_output.push_str("        #define END_API __declspec(dllimport)\n");
            self.header_output.push_str("    #endif\n");
            self.header_output.push_str("#elif defined(__GNUC__) || defined(__clang__)\n");
            self.header_output.push_str("    #define END_API __attribute__((visibility(\"default\")))\n");
            self.header_output.push_str("#else\n");
            self.header_output.push_str("    #define END_API\n");
            self.header_output.push_str("#endif\n\n");
            self.header_output.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

            // Structs in header
            for s in &module.structs {
                self.header_output.push_str(&format!("typedef struct {} {{\n", s.name));
                for f in &s.fields {
                    self.header_output.push_str(&format!("    {} {};\n", self.map_type(&f.field_type), f.name));
                }
                self.header_output.push_str(&format!("}} {};\n\n", s.name));
            }
        }

        // Forward declarations of functions
        for f in &module.functions {
            let ret_type = if f.name == "main" {
                "int".to_string()
            } else {
                self.map_type(&f.return_type)
            };
            let mut params_str = Vec::new();
            if f.name == "main" && !f.params.is_empty() {
                params_str.push("int argc".to_string());
                params_str.push("char** argv".to_string());
            } else {
                for p in &f.params {
                    params_str.push(format!("{} {}", self.map_type(&p.param_type), p.name));
                }
                if params_str.is_empty() {
                    params_str.push("void".to_string());
                }
            }

            let is_explicit_inline = f.directives.iter().any(|d| d.name == "@inline" || d.name == "@always_inline");
            let is_exported = (is_lib && f.is_pub) || f.directives.iter().any(|d| d.name == "@export" || d.name == "@c_export");

            // Skip forward declaration for morphic template functions
            if f.morphic_param.is_some() {
                continue;
            }
            if f.name == "main" {
                self.output.push_str(&format!("{} {}({});\n", ret_type, f.name, params_str.join(", ")));
            } else if is_exported {
                self.output.push_str(&format!("END_API {} {}({});\n", ret_type, f.name, params_str.join(", ")));
                if is_lib {
                    self.header_output.push_str(&format!("END_API {} {}({});\n", ret_type, f.name, params_str.join(", ")));
                }
            } else if is_explicit_inline {
                self.output.push_str(&format!("static inline __attribute__((always_inline)) {} {}({});\n", ret_type, f.name, params_str.join(", ")));
            } else {
                self.output.push_str(&format!("static inline {} {}({});\n", ret_type, f.name, params_str.join(", ")));
            }
        }
        self.output.push('\n');

        if is_lib {
            self.header_output.push_str("\n#ifdef __cplusplus\n}\n#endif\n");
        }

        // Process Extensions
        for ext in &module.extensions {
            for f in &ext.functions {
                self.struct_methods.entry(ext.target.clone()).or_default().insert(f.name.clone());
                let mangled_name = format!("{}_{}", ext.target, f.name);
                let ret_type = self.map_type(&f.return_type);
                let mut params_str = Vec::new();
                for (idx, p) in f.params.iter().enumerate() {
                    if idx == 0 && (p.name == "self" || p.name == "&self") {
                        params_str.push(format!("{}* self", ext.target));
                    } else {
                        params_str.push(format!("{} {}", self.map_type(&p.param_type), p.name));
                    }
                }
                if params_str.is_empty() { params_str.push("void".to_string()); }
                self.output.push_str(&format!("static inline {} {}({});\n", ret_type, mangled_name, params_str.join(", ")));
            }
        }

        // Process Modules
        for m in &module.modules {
            for f in &m.functions {
                self.module_methods.entry(m.name.clone()).or_default().insert(f.name.clone());
                let mangled_name = format!("{}_{}", m.name, f.name);
                let ret_type = self.map_type(&f.return_type);
                let mut params_str = Vec::new();
                for p in &f.params {
                    params_str.push(format!("{} {}", self.map_type(&p.param_type), p.name));
                }
                if params_str.is_empty() { params_str.push("void".to_string()); }
                self.output.push_str(&format!("static inline {} {}({});\n", ret_type, mangled_name, params_str.join(", ")));
            }
            for ov in &m.overrides {
                self.module_methods.entry(m.name.clone()).or_default().insert(ov.name.clone());
                let mangled_name = format!("{}_{}", m.name, ov.name);
                let ret_type = self.map_type(&ov.return_type);
                let mut params_str = Vec::new();
                for p in &ov.params {
                    params_str.push(format!("{} {}", self.map_type(&p.param_type), p.name));
                }
                if params_str.is_empty() { params_str.push("void".to_string()); }
                self.output.push_str(&format!("static inline {} {}({});\n", ret_type, mangled_name, params_str.join(", ")));
            }
        }
        self.output.push('\n');

        // Function Bodies
        // First pass: generate morphic concrete specializations
        let mut morphic_templates: Vec<FunctionDef> = Vec::new();
        let mut morphic_calls: Vec<(String, String, String)> = Vec::new(); // (call_name, morphic_var, concrete_val)
        
        for f in &module.functions {
            if f.morphic_param.is_some() {
                morphic_templates.push(f.clone());
            }
        }
        
        // Collect all function call identifiers from the AST to find morphic invocations
        fn collect_call_names(stmts: &[Statement], names: &mut Vec<String>) {
            for stmt in stmts {
                match stmt {
                    Statement::Expression(expr) | Statement::Return { value: Some(expr), .. } |
                    Statement::Defer { expr, .. } | Statement::Spawn { call: expr, .. } => {
                        collect_expr_calls(expr, names);
                    }
                    Statement::VarDecl { initializer: Some(init), .. } => {
                        collect_expr_calls(init, names);
                    }
                    Statement::Assignment { value, .. } => {
                        collect_expr_calls(value, names);
                    }
                    Statement::If { condition, then_block, else_block, .. } => {
                        collect_expr_calls(condition, names);
                        collect_call_names(&then_block.statements, names);
                        if let Some(eb) = else_block {
                            collect_call_names(&eb.statements, names);
                        }
                    }
                    Statement::While { condition, body, .. } => {
                        collect_expr_calls(condition, names);
                        collect_call_names(&body.statements, names);
                    }
                    Statement::ForIn { body, .. } | Statement::ParallelFor { body, .. } |
                    Statement::RegionBlock { body, .. } | Statement::TargetBlock { body, .. } => {
                        collect_call_names(&body.statements, names);
                    }
                    Statement::Match { expr, arms, .. } => {
                        collect_expr_calls(expr, names);
                        for arm in arms {
                            collect_call_names(&arm.body.statements, names);
                        }
                    }
                    Statement::QuantumUnwrap { expr, fallback, .. } => {
                        collect_expr_calls(expr, names);
                        collect_expr_calls(fallback, names);
                    }
                    Statement::AtomicOp { value, .. } => {
                        collect_expr_calls(value, names);
                    }
                    _ => {}
                }
            }
        }
        fn collect_expr_calls(expr: &Expression, names: &mut Vec<String>) {
            match expr {
                Expression::Call { callee, args, .. } => {
                    if let Expression::Ident(name, _) = callee.as_ref() {
                        names.push(name.clone());
                    }
                    for a in args {
                        collect_expr_calls(a, names);
                    }
                }
                Expression::Binary { left, right, .. } => {
                    collect_expr_calls(left, names);
                    collect_expr_calls(right, names);
                }
                Expression::Unary { expr, .. } | Expression::Await { expr, .. } => {
                    collect_expr_calls(expr, names);
                }
                Expression::Pipe { lhs, rhs, .. } | Expression::NullCollapse { left: lhs, right: rhs, .. } => {
                    collect_expr_calls(lhs, names);
                    collect_expr_calls(rhs, names);
                }
                _ => {}
            }
        }
        
        let mut all_call_names: Vec<String> = Vec::new();
        for f in &module.functions {
            collect_call_names(&f.body.statements, &mut all_call_names);
        }
        
        // For each morphic template, find matching calls and generate concrete functions
        for mt in &morphic_templates {
            if let Some(ref morphic_var) = mt.morphic_param {
                let template_name = &mt.name;
                let brace_open = template_name.find('{');
                let brace_close = template_name.find('}');
                if let (Some(bo), Some(bc)) = (brace_open, brace_close) {
                    let prefix = &template_name[..bo];
                    let suffix = &template_name[bc+1..];
                    
                    let mut seen = std::collections::HashSet::new();
                    for call_name in &all_call_names {
                        if call_name.ends_with(suffix) && call_name.len() > suffix.len() + prefix.len() {
                            let concrete_value = &call_name[prefix.len()..call_name.len()-suffix.len()];
                            if !concrete_value.is_empty() && !seen.contains(concrete_value) {
                                seen.insert(concrete_value.to_string());
                                // Generate a concrete C function
                                let mut concrete_fn = mt.clone();
                                concrete_fn.name = call_name.clone();
                                concrete_fn.morphic_param = None; // So gen_function doesn't skip it
                                
                                // Add a local variable declaration for the morphic param at start of body
                                let morphic_decl = Statement::VarDecl {
                                    name: morphic_var.clone(),
                                    var_type: Some(Type::Str),
                                    is_mut: false,
                                    initializer: Some(Expression::Lit(
                                        Literal::String(concrete_value.to_string()),
                                        mt.span.clone(),
                                    )),
                                    span: mt.span.clone(),
                                };
                                let mut new_stmts = vec![morphic_decl];
                                new_stmts.extend(concrete_fn.body.statements.clone());
                                concrete_fn.body.statements = new_stmts;
                                
                                self.gen_function(&concrete_fn);
                            }
                        }
                    }
                }
            }
        }
        
        for f in &module.functions {
            self.gen_function(f);
        }

        // Extension Bodies
        for ext in &module.extensions {
            for f in &ext.functions {
                let mut ext_fn = f.clone();
                ext_fn.name = format!("{}_{}", ext.target, f.name);
                if let Some(first_p) = ext_fn.params.first_mut() {
                    if first_p.name == "self" || first_p.name == "&self" {
                        first_p.name = "self".to_string();
                        first_p.param_type = Type::Pointer(Box::new(Type::Custom(ext.target.clone())));
                    }
                }
                self.gen_function(&ext_fn);
            }
        }

        // Module Function Bodies & Derived Inheritance
        for m in &module.modules {
            for f in &m.functions {
                let mut mod_fn = f.clone();
                mod_fn.name = format!("{}_{}", m.name, f.name);
                self.gen_function(&mod_fn);
            }
            for ov in &m.overrides {
                let mut ov_fn = ov.clone();
                ov_fn.name = format!("{}_{}", m.name, ov.name);
                self.gen_function(&ov_fn);
            }
            if let Some(parent_name) = &m.parent {
                if let Some(parent_mod) = module.modules.iter().find(|pm| pm.name == *parent_name) {
                    for pf in &parent_mod.functions {
                        if !m.functions.iter().any(|f| f.name == pf.name) && !m.overrides.iter().any(|ov| ov.name == pf.name) {
                            let mut inherited_fn = pf.clone();
                            inherited_fn.name = format!("{}_{}", m.name, pf.name);
                            let parent_fn_call = format!("{}_{}", parent_name, pf.name);
                            let args_call = pf.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
                            inherited_fn.body = Block {
                                statements: vec![
                                    Statement::Return {
                                        value: Some(Expression::Call {
                                            callee: Box::new(Expression::Ident(parent_fn_call, pf.span.clone())),
                                            args: pf.params.iter().map(|p| Expression::Ident(p.name.clone(), p.span.clone())).collect(),
                                            span: pf.span.clone(),
                                        }),
                                        span: pf.span.clone(),
                                    }
                                ],
                                span: pf.span.clone(),
                            };
                            self.gen_function(&inherited_fn);
                        }
                    }
                }
            }
        }

        (
            self.output.clone(),
            if is_lib { Some(self.header_output.clone()) } else { None },
        )
    }

    fn map_type(&self, ty: &Type) -> String {
        match ty {
            Type::Void => "void".to_string(),
            Type::Bool => "bool".to_string(),
            Type::I8 => "int8_t".to_string(),
            Type::I16 => "int16_t".to_string(),
            Type::I32 => "int32_t".to_string(),
            Type::I64 => "int64_t".to_string(),
            Type::U8 => "uint8_t".to_string(),
            Type::U16 => "uint16_t".to_string(),
            Type::U32 => "uint32_t".to_string(),
            Type::U64 => "uint64_t".to_string(),
            Type::F32 => "float".to_string(),
            Type::F64 => "double".to_string(),
            Type::Simd(inner, lanes) => format!("{}_vec{}", self.map_type(inner), lanes),
            Type::Str => "const char*".to_string(),
            Type::Custom(name) => name.clone(),
            Type::Pointer(inner) => format!("{}*", self.map_type(inner)),
            Type::Slice(inner) => format!("{}*", self.map_type(inner)),
            Type::Array(inner, size) => format!("{}[{}]", self.map_type(inner), size),
            Type::Tuple(_) => "void*".to_string(),
            Type::Generic(name, _) => name.clone(),
            Type::Result(inner, _) => self.map_type(inner),
            Type::Box(inner) => format!("{}*", self.map_type(inner)),
            Type::Rc(inner) => format!("{}*", self.map_type(inner)),
            Type::Arc(inner) => format!("{}*", self.map_type(inner)),
            Type::Channel(_) => "EndChannel*".to_string(),
            Type::Region(_) => "EndArena*".to_string(),
            Type::Allocator => "EndAllocator*".to_string(),
        }
    }

    fn gen_function(&mut self, func: &FunctionDef) {
        let ret_type = if func.name == "main" {
            "int".to_string()
        } else {
            self.map_type(&func.return_type)
        };

        let mut params_str = Vec::new();
        if func.name == "main" && !func.params.is_empty() {
            params_str.push("int argc".to_string());
            params_str.push("char** argv".to_string());
        } else {
            for p in &func.params {
                params_str.push(format!("{} {}", self.map_type(&p.param_type), p.name));
            }
            if params_str.is_empty() {
                params_str.push("void".to_string());
            }
        }

        let fn_name = if func.name == "main" {
            "main".to_string()
        } else {
            func.name.clone()
        };

        // If this is a morphic function template like {platform}_send,
        // we skip generating it directly — concrete specializations are generated at call sites.
        if func.morphic_param.is_some() {
            // Store the morphic template for later specialization
            return;
        }

        let is_explicit_inline = func.directives.iter().any(|d| d.name == "@inline" || d.name == "@always_inline");
        let is_exported = (self.is_lib && func.is_pub) || func.directives.iter().any(|d| d.name == "@export" || d.name == "@c_export");
        let is_comptime = func.directives.iter().any(|d| d.name == "@comptime");

        let prefix = if func.name == "main" {
            "".to_string()
        } else if is_exported {
            "END_API ".to_string()
        } else if is_comptime {
            "static inline __attribute__((const)) ".to_string()
        } else if is_explicit_inline {
            "static inline __attribute__((always_inline)) ".to_string()
        } else {
            "static inline ".to_string()
        };

        let clean_file = func.span.file.replace('\\', "/");
        self.output.push_str(&format!("#line {} \"{}\"\n", func.span.line, clean_file));
        self.output.push_str(&format!(
            "{}{} {}({}) {{\n",
            prefix,
            ret_type,
            fn_name,
            params_str.join(", ")
        ));

        self.indent_level += 1;
        self.var_types.clear();
        for p in &func.params {
            self.var_types.insert(p.name.clone(), p.param_type.clone());
        }
        
        if func.directives.iter().any(|d| d.name == "@telemetry") {
            self.output.push_str(&format!("{}printf(\"[TELEMETRY] Executing %s\\n\", \"{}\");\n", self.indent(), func.name));
        }
        for d in &func.directives {
            if d.name == "@invariant" {
                if let Some(cond) = d.args.first() {
                    self.output.push_str(&format!("{}assert({});\n", self.indent(), cond));
                }
            }
        }
        
        for stmt in &func.body.statements {
            self.gen_statement(stmt);
        }
        if func.name == "main" {
            self.output.push_str(&format!("{}return 0;\n", self.indent()));
        }
        self.indent_level -= 1;
        self.output.push_str("}\n\n");
    }

    fn gen_statement(&mut self, stmt: &Statement) {
        let span = stmt.span();
        let clean_file = span.file.replace('\\', "/");
        self.output.push_str(&format!("{}#line {} \"{}\"\n", self.indent(), span.line, clean_file));

        match stmt {
            Statement::VarDecl {
                name,
                var_type,
                initializer,
                ..
            } => {
                if let Some(t) = var_type {
                    self.var_types.insert(name.clone(), t.clone());
                } else if let Some(Expression::StructInit { name: st_name, .. }) = initializer {
                    self.var_types.insert(name.clone(), Type::Custom(st_name.clone()));
                } else if let Some(Expression::Alloc { target_type, .. }) = initializer {
                    self.var_types.insert(name.clone(), Type::Pointer(Box::new(target_type.clone())));
                } else if let Some(Expression::Promote { expr, .. }) = initializer {
                    if let Expression::Ident(id, _) = expr.as_ref() {
                        if let Some(t) = self.var_types.get(id).cloned() {
                            self.var_types.insert(name.clone(), t);
                        }
                    }
                } else if let Some(init_expr) = initializer {
                    let inferred = self.infer_type(init_expr);
                    if inferred != Type::Void {
                        self.var_types.insert(name.clone(), inferred);
                    }
                }

                let ty_str = if let Some(t) = var_type {
                    self.map_type(t)
                } else {
                    "__auto_type".to_string()
                };

                if let Some(init) = initializer {
                    let init_str = self.gen_expression(init);
                    self.output.push_str(&format!(
                        "{}{} {} = {};\n",
                        self.indent(),
                        ty_str,
                        name,
                        init_str
                    ));
                } else {
                    self.output.push_str(&format!(
                        "{}{} {};\n",
                        self.indent(),
                        ty_str,
                        name
                    ));
                }
            }
            Statement::Assignment { target, value, .. } => {
                let target_str = self.gen_expression(target);
                let value_str = self.gen_expression(value);
                self.output.push_str(&format!(
                    "{}{} = {};\n",
                    self.indent(),
                    target_str,
                    value_str
                ));
            }
            Statement::Return { value, .. } => {
                if let Some(v) = value {
                    let val_str = self.gen_expression(v);
                    self.output.push_str(&format!("{}return {};\n", self.indent(), val_str));
                } else {
                    self.output.push_str(&format!("{}return;\n", self.indent()));
                }
            }
            Statement::Expression(expr) => {
                let expr_str = self.gen_expression(expr);
                self.output.push_str(&format!("{}{};\n", self.indent(), expr_str));
            }
            Statement::If {
                condition,
                then_block,
                else_block,
                ..
            } => {
                let cond_str = self.gen_expression(condition);
                self.output.push_str(&format!("{}if ({}) {{\n", self.indent(), cond_str));
                self.indent_level += 1;
                for s in &then_block.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                if let Some(eb) = else_block {
                    self.output.push_str(&format!("{}}} else {{\n", self.indent()));
                    self.indent_level += 1;
                    for s in &eb.statements {
                        self.gen_statement(s);
                    }
                    self.indent_level -= 1;
                }
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::While { condition, body, .. } => {
                let cond_str = self.gen_expression(condition);
                self.output.push_str(&format!("{}while ({}) {{\n", self.indent(), cond_str));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::ParallelFor {
                item_name,
                iterable,
                body,
                ..
            } => {
                let iter_str = self.gen_expression(iterable);
                self.output.push_str(&format!(
                    "{}#pragma omp parallel for\n",
                    self.indent()
                ));
                self.output.push_str(&format!(
                    "{}for (int32_t {} = 0; {} < {}; {}++) {{\n",
                    self.indent(),
                    item_name,
                    item_name,
                    iter_str,
                    item_name
                ));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::ForIn {
                item_name,
                iterable,
                body,
                ..
            } => {
                let iter_str = self.gen_expression(iterable);
                self.output.push_str(&format!(
                    "{}#pragma unroll\n{}#pragma GCC ivdep\n",
                    self.indent(),
                    self.indent()
                ));
                self.output.push_str(&format!(
                    "{}for (int64_t {} = 0; {} < {}; {}++) {{\n",
                    self.indent(),
                    item_name,
                    item_name,
                    iter_str,
                    item_name
                ));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::Match { expr, arms, .. } => {
                let expr_str = self.gen_expression(expr);
                self.output.push_str(&format!("{}switch (({}).tag) {{\n", self.indent(), expr_str));
                self.indent_level += 1;
                for arm in arms {
                    match &arm.pattern {
                        Pattern::Variant { variant_name, enum_name, binding } => {
                            let en = enum_name.clone().unwrap_or_else(|| self.find_enum_for_variant(variant_name));
                            self.output.push_str(&format!("{}case {}_{}: {{\n", self.indent(), en, variant_name));
                            self.indent_level += 1;
                            if let Some(b) = binding {
                                self.output.push_str(&format!("{}__auto_type {} = ({}).data.{};\n", self.indent(), b, expr_str, variant_name));
                            }
                            for s in &arm.body.statements {
                                self.gen_statement(s);
                            }
                            self.output.push_str(&format!("{}break;\n", self.indent()));
                            self.indent_level -= 1;
                            self.output.push_str(&format!("{}}}\n", self.indent()));
                        }
                        Pattern::Wildcard => {
                            self.output.push_str(&format!("{}default: {{\n", self.indent()));
                            self.indent_level += 1;
                            for s in &arm.body.statements {
                                self.gen_statement(s);
                            }
                            self.output.push_str(&format!("{}break;\n", self.indent()));
                            self.indent_level -= 1;
                            self.output.push_str(&format!("{}}}\n", self.indent()));
                        }
                        _ => {}
                    }
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
            }
            Statement::RegionBlock { name, body, .. } => {
                self.output.push_str(&format!(
                    "{}/* Enter Region: {} */\n",
                    self.indent(),
                    name
                ));
                self.output.push_str(&format!(
                    "{}EndArena* region_{} = end_arena_create(512 * 1024);\n",
                    self.indent(),
                    name
                ));
                self.output.push_str(&format!("{}{{\n", self.indent()));
                self.indent_level += 1;
                self.active_regions.push(name.clone());
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.active_regions.pop();
                self.indent_level -= 1;
                self.output.push_str(&format!("{}}}\n", self.indent()));
                self.output.push_str(&format!(
                    "{}end_arena_destroy(region_{});\n",
                    self.indent(),
                    name
                ));
            }
            Statement::InlineC { code, .. } => {
                self.output.push_str(&format!("{}{}\n", self.indent(), code));
            }
            Statement::AsmBlock { arch, code, .. } => {
                self.output.push_str(&format!(
                    "{}/* Inline Assembly: {} */\n",
                    self.indent(),
                    arch
                ));
                for line in code.lines() {
                    self.output.push_str(&format!(
                        "{}__asm__ volatile(\"{}\\n\\t\");\n",
                        self.indent(),
                        line.trim().replace('"', "\\\"")
                    ));
                }
            }
            Statement::TargetBlock { target, body, .. } => {
                self.output.push_str(&format!("{}#ifdef TARGET_{}\n", self.indent(), target.to_uppercase()));
                self.indent_level += 1;
                for s in &body.statements {
                    self.gen_statement(s);
                }
                self.indent_level -= 1;
                self.output.push_str(&format!("{}#endif\n", self.indent()));
            }
            Statement::Defer { expr, .. } => {
                let expr_str = self.gen_expression(expr);
                self.output.push_str(&format!("{}/* defer */ {};\n", self.indent(), expr_str));
            }
            Statement::Skip { .. } => { self.output.push_str(&format!("{}{};\n", self.indent(), "continue")); }
Statement::Spawn { call, .. } => {
                let call_str = self.gen_expression(call);
                self.output.push_str(&format!("{}/* spawn */ (void){};\n", self.indent(), call_str));
            }
            Statement::QuantumUnwrap { name, var_type, expr, fallback, .. } => {
                let ty_str = if let Some(t) = var_type {
                    self.map_type(t)
                } else {
                    "__auto_type".to_string()
                };
                let expr_str = self.gen_expression(expr);
                let fallback_str = self.gen_expression(fallback);
                self.output.push_str(&format!(
                    "{}{} {} = ({}); if (!{}) {{ {} = ({}); }}\n",
                    self.indent(),
                    ty_str,
                    name,
                    expr_str,
                    name,
                    name,
                    fallback_str
                ));
            }
            Statement::AtomicOp { target, value, .. } => {
                let val_str = self.gen_expression(value);
                self.output.push_str(&format!(
                    "{}__atomic_fetch_add(&{}, {}, __ATOMIC_SEQ_CST);\n",
                    self.indent(),
                    target,
                    val_str
                ));
            }
        }
    }


    pub fn infer_type(&self, expr: &Expression) -> Type {
        match expr {
            Expression::Lit(Literal::String(_), _) => Type::Str,
            Expression::Lit(Literal::Int(_), _) => Type::I64,
            Expression::Lit(Literal::Float(_), _) => Type::F64,
            Expression::Lit(Literal::Bool(_), _) => Type::Bool,
            Expression::Ident(name, _) => self.var_types.get(name).cloned().unwrap_or(Type::Void),
            Expression::Call { .. } => Type::Void,
            Expression::FieldAccess { .. } => Type::Void,
            Expression::Binary { op, left, right, .. } => {
                let l_ty = self.infer_type(left);
                if matches!(op, BinaryOp::Add) && l_ty == Type::Str { Type::Str } else { l_ty }
            }
            _ => Type::Void,
        }
    }

    fn gen_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::Lit(lit, _) => match lit {
                Literal::Int(n) => n.to_string(),
                Literal::Float(f) => format!("{:.6}f", f),
                Literal::String(s) => format!("\"{}\"", escape_c_string(s)),
                Literal::Bool(b) => if *b { "true".to_string() } else { "false".to_string() },
                Literal::Null => "NULL".to_string(),
            },
            Expression::Ident(name, _) => name.clone(),
            Expression::Binary { left, op, right, .. } => {
                let l = self.gen_expression(left);
                let r = self.gen_expression(right);
                match op {
                    BinaryOp::Add => {
                        let is_str_l = self.infer_type(left) == Type::Str || l.starts_with('"') || l.contains("_dispatch") || l.contains("_str") || l.contains("_concat") || l.contains("prefix") || l.contains("message") || l.contains("chat_id");
                        let is_str_r = self.infer_type(right) == Type::Str || r.starts_with('"') || r.contains("_dispatch") || r.contains("_str") || r.contains("_concat") || r.contains("prefix") || r.contains("message") || r.contains("chat_id");
                        if is_str_l || is_str_r {
                            format!("_end_str_concat({}, {})", l, r)
                        } else {
                            format!("({} + {})", l, r)
                        }
                    },
                    BinaryOp::Sub => format!("({} - {})", l, r),
                    BinaryOp::Mul => format!("({} * {})", l, r),
                    BinaryOp::Div => format!("({} / {})", l, r),
                    BinaryOp::Mod => format!("({} % {})", l, r),
                    BinaryOp::Equal => {
                        let is_str = (self.infer_type(left) == Type::Str && self.infer_type(right) == Type::Str) || ((l.contains("str") || l.contains("text") || l.contains("msg") || l.contains("prefix") || l.starts_with('"'))
                                  && (r.contains("str") || r.contains("text") || r.contains("msg") || r.contains("prefix") || r.starts_with('"')));
                        if is_str {
                            format!("(strcmp({}, {}) == 0)", l, r)
                        } else {
                            format!("({} == {})", l, r)
                        }
                    },
                    BinaryOp::NotEqual => {
                        let is_str = (self.infer_type(left) == Type::Str && self.infer_type(right) == Type::Str) || ((l.contains("str") || l.contains("text") || l.contains("msg") || l.contains("prefix") || l.starts_with('"'))
                                  && (r.contains("str") || r.contains("text") || r.contains("msg") || r.contains("prefix") || r.starts_with('"')));
                        if is_str {
                            format!("(strcmp({}, {}) != 0)", l, r)
                        } else {
                            format!("({} != {})", l, r)
                        }
                    },
                    BinaryOp::LessThan => format!("({} < {})", l, r),
                    BinaryOp::LessEqual => format!("({} <= {})", l, r),
                    BinaryOp::GreaterThan => format!("({} > {})", l, r),
                    BinaryOp::GreaterEqual => format!("({} >= {})", l, r),
                    BinaryOp::And => format!("({} && {})", l, r),
                    BinaryOp::Or => format!("({} || {})", l, r),
                    BinaryOp::Shl => format!("(((uint64_t)({})) << ({}) )", l, r),
                    BinaryOp::Shr => format!("(((uint64_t)({})) >> ({}) )", l, r),
                    BinaryOp::BitAnd => format!("(((uint64_t)({})) & ((uint64_t)({})))", l, r),
                    BinaryOp::BitOr => format!("(((uint64_t)({})) | ((uint64_t)({})))", l, r),
                    BinaryOp::BitXor => format!("(((uint64_t)({})) ^ ((uint64_t)({})))", l, r),
                }
            }
            Expression::Unary { op, expr, .. } => {
                let e = self.gen_expression(expr);
                match op {
                    UnaryOp::Negate => format!("(-{})", e),
                    UnaryOp::Not => format!("(!{})", e),
                    UnaryOp::AddressOf => format!("(&{})", e),
                    UnaryOp::Deref => format!("(*{})", e),
                    UnaryOp::BitNot => format!("(~{})", e),
                }
            }
            Expression::Call { callee, args, .. } => {
                let callee_str = self.gen_expression(callee);
                if callee_str == "println" {
                    if let Some(first_arg) = args.first() {
                        let arg_str = self.gen_expression(first_arg);
                        return format!("end_println({})", arg_str);
                    }
                }

                // Check for struct extension methods & module methods
                if let Expression::FieldAccess { object, field, .. } = callee.as_ref() {
                    let obj_str = self.gen_expression(object);

                    // 1. Check if object is a module name, e.g. MathModule.calc(...)
                    if let Expression::Ident(mod_name, _) = object.as_ref() {
                        if self.module_methods.contains_key(mod_name) {
                            let mut mod_args = Vec::new();
                            for a in args {
                                mod_args.push(self.gen_expression(a));
                            }
                            return format!("{}_{}({})", mod_name, field, mod_args.join(", "));
                        }
                    }

                    // 2. Struct Method / Extension method dispatch
                    let is_ptr = if let Expression::Ident(id, _) = object.as_ref() {
                        self.var_types.get(id).map_or(false, |t| matches!(t, Type::Pointer(_) | Type::Box(_) | Type::Rc(_) | Type::Arc(_)))
                    } else {
                        false
                    };
                    let receiver_arg = if is_ptr { obj_str.clone() } else { format!("&{}", obj_str) };
                    let mut ext_args = vec![receiver_arg];
                    for a in args {
                        ext_args.push(self.gen_expression(a));
                    }

                    if let Expression::Ident(id, _) = object.as_ref() {
                        if let Some(Type::Custom(struct_name)) = self.var_types.get(id) {
                            return format!("{}_{}({})", struct_name, field, ext_args.join(", "));
                        }
                    }

                    for (st_name, methods) in &self.struct_methods {
                        if methods.contains(field) {
                            return format!("{}_{}({})", st_name, field, ext_args.join(", "));
                        }
                    }
                }

                let mut args_str = Vec::new();
                for a in args {
                    args_str.push(self.gen_expression(a));
                }
                format!("{}({})", callee_str, args_str.join(", "))
            }
            Expression::FieldAccess { object, field, .. } => {
                let obj_str = self.gen_expression(object);
                if let Expression::Ident(mod_name, _) = object.as_ref() {
                    if self.module_methods.contains_key(mod_name) {
                        return format!("{}_{}", mod_name, field);
                    }
                }
                if let Expression::Ident(name, _) = object.as_ref() {
                    if let Some(ty) = self.var_types.get(name) {
                        match ty {
                            Type::Pointer(_) | Type::Box(_) | Type::Rc(_) | Type::Arc(_) => {
                                return format!("{}->{}", obj_str, field);
                            }
                            _ => {}
                        }
                    }
                }
                format!("{}.{}", obj_str, field)
            }
            Expression::Index { array, index, .. } => {
                let arr_str = self.gen_expression(array);
                let idx_str = self.gen_expression(index);
                format!("{}[{}]", arr_str, idx_str)
            }
            Expression::StructInit { name, fields, .. } => {
                let mut field_inits = Vec::new();
                for (fname, fval) in fields {
                    field_inits.push(format!(".{} = {}", fname, self.gen_expression(fval)));
                }
                format!("({}){{ {} }}", name, field_inits.join(", "))
            }
            Expression::EnumInit { enum_name, variant_name, payload, .. } => {
                let en = enum_name.clone().unwrap_or_else(|| self.find_enum_for_variant(variant_name));
                if let Some(p) = payload {
                    format!("({}){{ .tag = {}_{}, .data.{} = {} }}", en, en, variant_name, variant_name, self.gen_expression(p))
                } else {
                    format!("({}){{ .tag = {}_{} }}", en, en, variant_name)
                }
            }
            Expression::InlineC { code, .. } => code.clone(),
            Expression::Pipe { lhs, rhs, .. } => {
                let lhs_str = self.gen_expression(lhs.as_ref());
                match rhs.as_ref() {
                    Expression::Call { callee, args, .. } => {
                        let callee_str = self.gen_expression(callee.as_ref());
                        let mut all_args = vec![lhs_str];
                        for a in args {
                            all_args.push(self.gen_expression(a));
                        }
                        format!("{}({})", callee_str, all_args.join(", "))
                    }
                    Expression::Ident(name, _) => {
                        format!("{}({})", name, lhs_str)
                    }
                    _ => {
                        let rhs_str = self.gen_expression(rhs.as_ref());
                        format!("{}({})", rhs_str, lhs_str)
                    }
                }
            }
            Expression::Alloc { target_type, .. } => {
                if let Some(curr_region) = self.active_regions.last() {
                    match target_type {
                        Type::Array(inner, size) => format!("({}*)end_arena_alloc(region_{}, (size_t)({}) * sizeof({}))", self.map_type(inner), curr_region, size, self.map_type(inner)),
                        _ => format!("({}*)end_arena_alloc(region_{}, sizeof({}))", self.map_type(target_type), curr_region, self.map_type(target_type)),
                    }
                } else {
                    match target_type {
                        Type::Array(inner, size) => format!("({}*)malloc((size_t)({}) * sizeof({}))", self.map_type(inner), size, self.map_type(inner)),
                        _ => format!("({}*)malloc(sizeof({}))", self.map_type(target_type), self.map_type(target_type)),
                    }
                }
            }
            Expression::Promote { expr, target_region, .. } => {
                let e = self.gen_expression(expr);
                format!("end_promote({}, region_{}, sizeof(*({})))", e, target_region, e)
            }
            Expression::Catch { expr, .. } => {
                self.gen_expression(expr)
            }
                        Expression::Match { expr, arms, .. } => {
                let target = self.gen_expression(expr);
                let mut result = String::new();
                let mut open_parens = 0;
                for arm in arms {
                    let arm_val = if let Some(last) = arm.body.statements.last() {
                        match last {
                            Statement::Expression(e) => self.gen_expression(e),
                            Statement::Return { value: Some(e), .. } => self.gen_expression(e),
                            _ => "0".to_string(),
                        }
                    } else {
                        "0".to_string()
                    };

                    match &arm.pattern {
                        Pattern::Literal(lit) => {
                            let lit_str = match lit {
                                Literal::Int(n) => n.to_string(),
                                Literal::Float(f) => format!("{:.6}f", f),
                                Literal::Bool(b) => if *b { "1".into() } else { "0".into() },
                                Literal::String(s) => format!("\"{}\"", escape_c_string(s)),
                                Literal::Null => "0".into(),
                            };
                            result.push_str(&format!("(({} == {}) ? ({}) : ", target, lit_str, arm_val));
                            open_parens += 1;
                        }
                        Pattern::Wildcard | Pattern::Ident(_) => {
                            result.push_str(&format!("({})", arm_val));
                            for _ in 0..open_parens {
                                result.push(')');
                            }
                            return result;
                        }
                        Pattern::Variant { variant_name, enum_name, .. } => {
                            let en = enum_name.clone().unwrap_or_else(|| self.find_enum_for_variant(variant_name));
                            result.push_str(&format!("(({}.tag == {}_{}) ? ({}) : ", target, en, variant_name, arm_val));
                            open_parens += 1;
                        }
                    }
                }
                result.push_str("0");
                for _ in 0..open_parens {
                    result.push(')');
                }
                result
            }
            Expression::Block(_) => "0".to_string(),
            Expression::NameOf { target, .. } => format!("\"{}\"", escape_c_string(target)),
            Expression::PathOf { target, .. } => format!("\"{}\"", escape_c_string(target)),
            Expression::TypeOf { expr, .. } => {
                let e = self.gen_expression(expr);
                format!("\"type_of({})\"", escape_c_string(&e))
            }
            Expression::DocOf { target, .. } => format!("\"[Documentation for symbol '{}']\"", escape_c_string(target)),
            Expression::CodeOf { code, .. } => format!("\"{}\"", escape_c_string(code)),
            Expression::Dbg { expr, code, span } => {
                let e = self.gen_expression(expr);
                let clean_file = span.file.replace('\\', "/");
                format!("(printf(\"\\033[1;36m[DBG %s:%d]\\033[0m \\033[1;33m%s\\033[0m = \", \"{}\", {}, \"{}\"), end_println({}), {})", clean_file, span.line, escape_c_string(code), e, e)
            }
            Expression::AssertDebug { condition, code, span } => {
                let cond = self.gen_expression(condition);
                let clean_file = span.file.replace('\\', "/");
                format!("if (!({})) {{ fprintf(stderr, \"\\033[1;31m[ASSERTION FAILURE %s:%d]\\033[0m Condition failed: %s\\n\", \"{}\", {}, \"{}\"); abort(); }}", cond, clean_file, span.line, escape_c_string(code))
            }
            Expression::Translate { key, .. } => format!("\"[Localized: {}]\"", escape_c_string(key)),
            Expression::FieldsOf { target, .. } => format!("\"[Fields of struct {}]\"", escape_c_string(target)),
            Expression::SqlExpr { expr, .. } => {
                let e = self.gen_expression(expr);
                format!("\"SELECT * WHERE {}\"", escape_c_string(&e))
            }
            Expression::Cast { expr, target_type, .. } => {
                let inner = self.gen_expression(expr);
                let c_ty = self.map_type(target_type);
                format!("(({})({}))", c_ty, inner)
            }
            Expression::Await { expr, .. } => {
                self.gen_expression(expr)
            }
            Expression::UnitLit { value, unit, .. } => {
                match unit.as_str() {
                    "km/h" => format!("((int64_t)({:.2} * 1000.0 / 3600.0))", value),
                    "m/s" => format!("((int64_t){:.0})", value),
                    "usd" | "eur" => format!("((int64_t)({:.2} * 100.0))", value),
                    _ => format!("((int64_t){:.0})", value),
                }
            }
            Expression::NullCollapse { left, right, .. } => {
                let l = self.gen_expression(left);
                let r = self.gen_expression(right);
                // Pipeline operator: evaluate left, then evaluate right
                format!("((void)({}), ({}))", l, r)
            }
        }
    }
}











