// Auto-generated by End Language Universal Bindgen for Flutter / Dart FFI
import 'dart:ffi' as ffi;
import 'dart:io' show Platform;

class MainNative {
  late ffi.DynamicLibrary _dylib;

  MainNative() {
    _dylib = Platform.isWindows ? ffi.DynamicLibrary.open('test_blindspots_v2.dll') : ffi.DynamicLibrary.open('libtest_blindspots_v2.so');
  }

  int fuzz_target_packet_parser(int data_len) {
    final func = _dylib.lookupFunction<ffi.Int64 Function(), int Function()>('fuzz_target_packet_parser');
    return func();
  }

}
