# Auto-generated by End Language Universal Bindgen
import ctypes
import os
from typing import Any

_lib_path = os.path.join(os.path.dirname(__file__), 'test_blindspots_v2.dll')
try:
    _lib = ctypes.CDLL(_lib_path)
except Exception:
    _lib = None

def fuzz_target_packet_parser(data_len):
    if _lib is None: return 0
    return _lib.fuzz_target_packet_parser(data_len)

