// 👑 End Language C Header Bindgen Parser
// Converts C/C++ Header Files (.h / .hpp) directly into typed End Language modules

use std::fs;
use std::path::Path;

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct CFunction {
    pub name: String,
    pub return_type: String,
    pub params: Vec<(String, String)>, // (name, type)
    pub doc: String,
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct CStruct {
    pub name: String,
    pub fields: Vec<(String, String)>, // (name, type)
    pub doc: String,
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct CEnum {
    pub name: String,
    pub variants: Vec<(String, Option<i64>)>, // (name, value)
    pub doc: String,
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct CMacroConstant {
    pub name: String,
    pub value: String,
    pub is_string: bool,
    pub is_numeric: bool,
}

pub struct CHeaderParser;

impl CHeaderParser {
    pub fn parse_header_file(header_path: &Path) -> Result<String, String> {
        let content = fs::read_to_string(header_path)
            .map_err(|e| format!("Failed to read C header file '{:?}': {}", header_path, e))?;
        
        let header_name = header_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("c_library");

        Ok(Self::parse_header_content(header_name, &content))
    }

    pub fn parse_header_content(module_name: &str, content: &str) -> String {
        let mut out = String::new();
        out.push_str(&format!("// 👑 Auto-Generated End Language Bindings for C Library: {}\n", module_name));
        out.push_str("// Generated by End Universal C-Bindgen Engine (Zero-Overhead FFI)\n\n");
        out.push_str(&format!("@link(\"{}\")\n\n", module_name));

        let lines: Vec<&str> = content.lines().collect();
        let mut i = 0;

        let mut functions: Vec<CFunction> = Vec::new();
        let mut structs: Vec<CStruct> = Vec::new();
        let mut enums: Vec<CEnum> = Vec::new();
        let mut constants: Vec<CMacroConstant> = Vec::new();

        while i < lines.len() {
            let raw_line = lines[i].trim();

            // Skip comments and empty lines
            if raw_line.is_empty() || raw_line.starts_with("//") || raw_line.starts_with("/*") || raw_line.starts_with('*') {
                i += 1;
                continue;
            }

            // 1. #define Macro Constants
            if raw_line.starts_with("#define ") {
                let parts: Vec<&str> = raw_line["#define ".len()..].split_whitespace().collect();
                if parts.len() >= 2 {
                    let name = parts[0];
                    let val_str = parts[1..].join(" ");
                    // Exclude function-like macros and include guards
                    if !name.contains('(') && !name.ends_with("_H") && !name.ends_with("_H_") && !val_str.is_empty() {
                        let is_str = val_str.starts_with('"') && val_str.ends_with('"');
                        let is_num = val_str.parse::<i64>().is_ok() || val_str.parse::<f64>().is_ok() || val_str.starts_with("0x");
                        constants.push(CMacroConstant {
                            name: name.to_string(),
                            value: val_str,
                            is_string: is_str,
                            is_numeric: is_num,
                        });
                    }
                }
                i += 1;
                continue;
            }

            // 2. Struct Definitions (typedef struct { ... } Name; or struct Name { ... };)
            if raw_line.contains("struct ") && raw_line.contains('{') {
                let mut struct_name = String::new();
                if raw_line.starts_with("typedef struct") {
                    let after = raw_line["typedef struct".len()..].trim();
                    if let Some(brace_pos) = after.find('{') {
                        struct_name = after[..brace_pos].trim().to_string();
                    }
                } else if raw_line.starts_with("struct ") {
                    let after = raw_line["struct ".len()..].trim();
                    if let Some(brace_pos) = after.find('{') {
                        struct_name = after[..brace_pos].trim().to_string();
                    }
                }

                let mut fields = Vec::new();
                i += 1;
                while i < lines.len() {
                    let fline = lines[i].trim();
                    if fline.starts_with('}') {
                        if struct_name.is_empty() {
                            let after_brace = fline.trim_start_matches('}').trim_end_matches(';').trim();
                            struct_name = after_brace.to_string();
                        }
                        break;
                    }
                    if !fline.is_empty() && fline.ends_with(';') {
                        let decl = fline.trim_end_matches(';').trim();
                        let parts: Vec<&str> = decl.split_whitespace().collect();
                        if parts.len() >= 2 {
                            let fname = parts[parts.len() - 1].trim_start_matches('*');
                            let ftype = parts[..parts.len() - 1].join(" ");
                            let end_type = Self::map_c_type_to_end(&ftype, parts[parts.len() - 1].starts_with('*'));
                            fields.push((fname.to_string(), end_type));
                        }
                    }
                    i += 1;
                }
                if !struct_name.is_empty() {
                    structs.push(CStruct {
                        name: struct_name,
                        fields,
                        doc: format!("C Native Struct {}", module_name),
                    });
                }
                i += 1;
                continue;
            }

            // 3. Enum Definitions (typedef enum { ... } Name; or enum Name { ... };)
            if raw_line.contains("enum ") && raw_line.contains('{') {
                let mut enum_name = String::new();
                if raw_line.starts_with("typedef enum") {
                    let after = raw_line["typedef enum".len()..].trim();
                    if let Some(brace_pos) = after.find('{') {
                        enum_name = after[..brace_pos].trim().to_string();
                    }
                } else if raw_line.starts_with("enum ") {
                    let after = raw_line["enum ".len()..].trim();
                    if let Some(brace_pos) = after.find('{') {
                        enum_name = after[..brace_pos].trim().to_string();
                    }
                }

                let mut variants = Vec::new();
                let mut current_val: i64 = 0;
                i += 1;
                while i < lines.len() {
                    let eline = lines[i].trim();
                    if eline.starts_with('}') {
                        if enum_name.is_empty() {
                            let after_brace = eline.trim_start_matches('}').trim_end_matches(';').trim();
                            enum_name = after_brace.to_string();
                        }
                        break;
                    }
                    let cleaned = eline.trim_end_matches(',').trim();
                    if !cleaned.is_empty() && !cleaned.starts_with("//") {
                        if cleaned.contains('=') {
                            let eq_parts: Vec<&str> = cleaned.split('=').collect();
                            let vname = eq_parts[0].trim();
                            let vval = eq_parts[1].trim().parse::<i64>().unwrap_or(current_val);
                            current_val = vval + 1;
                            variants.push((vname.to_string(), Some(vval)));
                        } else {
                            variants.push((cleaned.to_string(), Some(current_val)));
                            current_val += 1;
                        }
                    }
                    i += 1;
                }
                if !enum_name.is_empty() {
                    enums.push(CEnum {
                        name: enum_name,
                        variants,
                        doc: format!("C Native Enum {}", module_name),
                    });
                }
                i += 1;
                continue;
            }

            // 4. Function Prototypes (e.g. `int sqlite3_open(const char *filename, sqlite3 **ppDb);`)
            if raw_line.contains('(') && raw_line.ends_with(';') && !raw_line.starts_with('#') && !raw_line.starts_with("typedef") {
                let cleaned = raw_line.trim_end_matches(';').trim();
                let cleaned = cleaned.trim_start_matches("extern ").trim_start_matches("END_API ").trim();
                if let Some(paren_pos) = cleaned.find('(') {
                    let before_paren = cleaned[..paren_pos].trim();
                    let inside_paren = &cleaned[paren_pos + 1..cleaned.len() - 1];

                    let before_parts: Vec<&str> = before_paren.split_whitespace().collect();
                    if before_parts.len() >= 2 {
                        let fn_name = before_parts[before_parts.len() - 1].trim_start_matches('*');
                        let ret_type_raw = before_parts[..before_parts.len() - 1].join(" ");
                        let ret_type = Self::map_c_type_to_end(&ret_type_raw, before_parts[before_parts.len() - 1].starts_with('*'));

                        let mut params = Vec::new();
                        if !inside_paren.is_empty() && inside_paren != "void" {
                            for param_str in inside_paren.split(',') {
                                let p_parts: Vec<&str> = param_str.trim().split_whitespace().collect();
                                if !p_parts.is_empty() {
                                    let is_ptr = p_parts.last().unwrap().starts_with('*') || p_parts.iter().any(|p| p.contains('*'));
                                    let pname = p_parts.last().unwrap().trim_start_matches('*');
                                    let ptype_raw = if p_parts.len() > 1 { p_parts[..p_parts.len() - 1].join(" ") } else { "void".to_string() };
                                    let ptype = Self::map_c_type_to_end(&ptype_raw, is_ptr);
                                    let safe_pname = if pname.is_empty() || pname == "..." { format!("arg{}", params.len() + 1) } else { pname.to_string() };
                                    params.push((safe_pname, ptype));
                                }
                            }
                        }

                        functions.push(CFunction {
                            name: fn_name.to_string(),
                            return_type: ret_type,
                            params,
                            doc: format!("Native C Function {}", fn_name),
                        });
                    }
                }
            }

            i += 1;
        }

        // Render Generated End Code
        // Constants
        if !constants.is_empty() {
            out.push_str("// --- Constants & Defines ---\n");
            for c in &constants {
                if c.is_string {
                    out.push_str(&format!("pub fn {}() str {{\n    ret {}\n}}\n\n", c.name, c.value));
                } else if c.is_numeric {
                    out.push_str(&format!("pub fn {}() i64 {{\n    ret {}\n}}\n\n", c.name, c.value));
                }
            }
        }

        // Enums
        if !enums.is_empty() {
            out.push_str("// --- Native Enums ---\n");
            for e in &enums {
                out.push_str(&format!("pub enum {} {{\n", e.name));
                for (v, val_opt) in &e.variants {
                    if let Some(val) = val_opt {
                        out.push_str(&format!("    {} = {},\n", v, val));
                    } else {
                        out.push_str(&format!("    {},\n", v));
                    }
                }
                out.push_str("}\n\n");
            }
        }

        // Structs
        if !structs.is_empty() {
            out.push_str("// --- Native Structs ---\n");
            for s in &structs {
                out.push_str(&format!("pub st {} {{\n", s.name));
                for (fname, ftype) in &s.fields {
                    out.push_str(&format!("    {}: {},\n", fname, ftype));
                }
                out.push_str("}\n\n");
            }
        }

        // Functions (extern fn)
        if !functions.is_empty() {
            out.push_str("// --- Foreign Function Interface (FFI) Declarations ---\n");
            for f in &functions {
                let params_str = f.params.iter().map(|(name, ty)| format!("{}: {}", name, ty)).collect::<Vec<_>>().join(", ");
                out.push_str(&format!("pub extern fn {}({}) {}\n", f.name, params_str, f.return_type));
            }
            out.push('\n');
        }

        out
    }

    pub fn map_c_type_to_end(c_type: &str, is_pointer: bool) -> String {
        let cleaned = c_type
            .replace("const", "")
            .replace("unsigned", "u_")
            .replace("signed", "")
            .replace("struct", "")
            .trim()
            .to_string();

        if is_pointer {
            if cleaned == "char" || cleaned == "u_ char" || cleaned == "i8" || cleaned == "u8" {
                return "str".to_string();
            }
            return "rawptr".to_string();
        }

        match cleaned.as_str() {
            "void" => "void".to_string(),
            "bool" | "_Bool" => "bool".to_string(),
            "char" | "i8" => "i8".to_string(),
            "u_ char" | "uint8_t" | "u8" | "unsigned char" => "u8".to_string(),
            "short" | "int16_t" | "i16" => "i16".to_string(),
            "u_ short" | "uint16_t" | "u16" => "u16".to_string(),
            "int" | "int32_t" | "i32" | "long" if cfg!(windows) => "i32".to_string(),
            "u_ int" | "uint32_t" | "u32" | "u_ long" if cfg!(windows) => "u32".to_string(),
            "long long" | "int64_t" | "i64" | "ssize_t" | "intptr_t" => "i64".to_string(),
            "u_ long long" | "uint64_t" | "u64" | "size_t" | "uintptr_t" => "u64".to_string(),
            "float" | "f32" => "f32".to_string(),
            "double" | "f64" => "f64".to_string(),
            other if !other.is_empty() => other.to_string(),
            _ => "rawptr".to_string(),
        }
    }
}
