use crate::ast::*;
use std::fs;
use std::path::{Path, PathBuf};

pub struct UniversalBindgen;

impl UniversalBindgen {
    pub fn generate_all(
        module: &Module,
        output_dir: &Path,
        lib_name: &str,
        targets: &[String],
    ) -> Result<Vec<PathBuf>, String> {
        let mut generated_files = Vec::new();
        fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir: {}", e))?;

        let should_gen = |t: &str| targets.is_empty() || targets.iter().any(|target| target.eq_ignore_ascii_case(t));

        if should_gen("python") {
            let py_file = output_dir.join(format!("{}.py", module.name));
            let pyi_file = output_dir.join(format!("{}.pyi", module.name));
            let (py_code, pyi_code) = Self::generate_python(module, lib_name);
            fs::write(&py_file, py_code).map_err(|e| e.to_string())?;
            fs::write(&pyi_file, pyi_code).map_err(|e| e.to_string())?;
            generated_files.push(py_file);
            generated_files.push(pyi_file);
        }

        if should_gen("typescript") || should_gen("ts") || should_gen("node") {
            let ts_file = output_dir.join(format!("{}.ts", module.name));
            let dts_file = output_dir.join(format!("{}.d.ts", module.name));
            let (ts_code, dts_code) = Self::generate_typescript(module, lib_name);
            fs::write(&ts_file, ts_code).map_err(|e| e.to_string())?;
            fs::write(&dts_file, dts_code).map_err(|e| e.to_string())?;
            generated_files.push(ts_file);
            generated_files.push(dts_file);
        }

        if should_gen("dart") || should_gen("flutter") {
            let dart_file = output_dir.join(format!("{}_bindings.dart", module.name));
            let dart_code = Self::generate_dart(module, lib_name);
            fs::write(&dart_file, dart_code).map_err(|e| e.to_string())?;
            generated_files.push(dart_file);
        }

        if should_gen("csharp") || should_gen("cs") || should_gen("unity") {
            let cs_file = output_dir.join(format!("{}Native.cs", capitalize(&module.name)));
            let cs_code = Self::generate_csharp(module, lib_name);
            fs::write(&cs_file, cs_code).map_err(|e| e.to_string())?;
            generated_files.push(cs_file);
        }

        Ok(generated_files)
    }

    fn generate_python(module: &Module, lib_name: &str) -> (String, String) {
        let mut py = String::new();
        let mut pyi = String::new();

        py.push_str("# Auto-generated by End Language Universal Bindgen\n");
        py.push_str("import ctypes\nimport os\nfrom typing import Any\n\n");
        py.push_str(&format!("_lib_path = os.path.join(os.path.dirname(__file__), '{}.dll')\n", lib_name));
        py.push_str("try:\n    _lib = ctypes.CDLL(_lib_path)\nexcept Exception:\n    _lib = None\n\n");

        pyi.push_str("# Type stubs for End Native Module\nfrom typing import Any\n\n");

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let params = func.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
            let params_typed = func.params.iter().map(|p| format!("{}: int", p.name)).collect::<Vec<_>>().join(", ");

            py.push_str(&format!("def {}({}):\n", func.name, params));
            py.push_str(&format!("    if _lib is None: return 0\n"));
            py.push_str(&format!("    return _lib.{}({})\n\n", func.name, params));

            pyi.push_str(&format!("def {}({}) -> int: ...\n", func.name, params_typed));
        }

        (py, pyi)
    }

    fn generate_typescript(module: &Module, lib_name: &str) -> (String, String) {
        let mut ts = String::new();
        let mut dts = String::new();

        ts.push_str("// Auto-generated by End Language Universal Bindgen for TypeScript/Node.js\n");
        ts.push_str("import * as path from 'path';\n\n");
        ts.push_str(&format!("export const LIB_NAME = '{}';\n\n", lib_name));

        dts.push_str("// TypeScript Definitions for End Native Module\n\n");

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let params_ts = func.params.iter().map(|p| format!("{}: number", p.name)).collect::<Vec<_>>().join(", ");
            ts.push_str(&format!("export function {}({}): number {{\n", func.name, params_ts));
            ts.push_str(&format!("    // Native FFI bridge for {}\n", func.name));
            ts.push_str("    return 0;\n}\n\n");

            dts.push_str(&format!("export function {}({}): number;\n", func.name, params_ts));
        }

        (ts, dts)
    }

    fn generate_dart(module: &Module, lib_name: &str) -> String {
        let mut dart = String::new();
        dart.push_str("// Auto-generated by End Language Universal Bindgen for Flutter / Dart FFI\n");
        dart.push_str("import 'dart:ffi' as ffi;\nimport 'dart:io' show Platform;\n\n");
        dart.push_str(&format!("class {}Native {{\n", capitalize(&module.name)));
        dart.push_str("  late ffi.DynamicLibrary _dylib;\n\n");
        dart.push_str(&format!("  {}Native() {{\n", capitalize(&module.name)));
        dart.push_str(&format!("    _dylib = Platform.isWindows ? ffi.DynamicLibrary.open('{}.dll') : ffi.DynamicLibrary.open('lib{}.so');\n", lib_name, lib_name));
        dart.push_str("  }\n\n");

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let params = func.params.iter().map(|p| format!("int {}", p.name)).collect::<Vec<_>>().join(", ");
            dart.push_str(&format!("  int {}({}) {{\n", func.name, params));
            dart.push_str(&format!("    final func = _dylib.lookupFunction<ffi.Int64 Function(), int Function()>('{}');\n", func.name));
            dart.push_str("    return func();\n");
            dart.push_str("  }\n\n");
        }

        dart.push_str("}\n");
        dart
    }

    fn generate_csharp(module: &Module, lib_name: &str) -> String {
        let mut cs = String::new();
        cs.push_str("// Auto-generated by End Language Universal Bindgen for C# / Unity / .NET\n");
        cs.push_str("using System;\nusing System.Runtime.InteropServices;\n\n");
        cs.push_str(&format!("public static class {}Native\n{{\n", capitalize(&module.name)));
        cs.push_str(&format!("    private const string LibName = \"{}\";\n\n", lib_name));

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let params = func.params.iter().map(|p| format!("long {}", p.name)).collect::<Vec<_>>().join(", ");
            cs.push_str(&format!("    [DllImport(LibName, EntryPoint = \"{}\")]\n", func.name));
            cs.push_str(&format!("    public static extern long {}({});\n\n", func.name, params));
        }

        cs.push_str("}\n");
        cs
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
