use crate::ast::*;
use std::fs;
use std::path::{Path, PathBuf};

pub struct UniversalBindgen;

impl UniversalBindgen {
    pub fn generate_all(
        module: &Module,
        output_dir: &Path,
        lib_name: &str,
        targets: &[String],
    ) -> Result<Vec<PathBuf>, String> {
        let mut generated_files = Vec::new();
        fs::create_dir_all(output_dir).map_err(|e| format!("Failed to create output dir: {}", e))?;

        let should_gen = |t: &str| targets.is_empty() || targets.iter().any(|target| target.eq_ignore_ascii_case(t));

        if should_gen("python") {
            let py_file = output_dir.join(format!("{}.py", module.name));
            let pyi_file = output_dir.join(format!("{}.pyi", module.name));
            let (py_code, pyi_code) = Self::generate_python(module, lib_name);
            fs::write(&py_file, py_code).map_err(|e| e.to_string())?;
            fs::write(&pyi_file, pyi_code).map_err(|e| e.to_string())?;
            generated_files.push(py_file);
            generated_files.push(pyi_file);
        }

        if should_gen("typescript") || should_gen("ts") || should_gen("node") {
            let ts_file = output_dir.join(format!("{}.ts", module.name));
            let dts_file = output_dir.join(format!("{}.d.ts", module.name));
            let (ts_code, dts_code) = Self::generate_typescript(module, lib_name);
            fs::write(&ts_file, ts_code).map_err(|e| e.to_string())?;
            fs::write(&dts_file, dts_code).map_err(|e| e.to_string())?;
            generated_files.push(ts_file);
            generated_files.push(dts_file);
        }

        if should_gen("dart") || should_gen("flutter") {
            let dart_file = output_dir.join(format!("{}_bindings.dart", module.name));
            let dart_code = Self::generate_dart(module, lib_name);
            fs::write(&dart_file, dart_code).map_err(|e| e.to_string())?;
            generated_files.push(dart_file);
        }

        if should_gen("csharp") || should_gen("cs") || should_gen("unity") {
            let cs_file = output_dir.join(format!("{}Native.cs", capitalize(&module.name)));
            let cs_code = Self::generate_csharp(module, lib_name);
            fs::write(&cs_file, cs_code).map_err(|e| e.to_string())?;
            generated_files.push(cs_file);
        }

        Ok(generated_files)
    }

    fn generate_python(module: &Module, lib_name: &str) -> (String, String) {
        let mut py = String::new();
        let mut pyi = String::new();

        py.push_str("# Auto-generated by End Language Universal Bindgen\n");
        py.push_str("import ctypes\nimport os\nfrom typing import Any, Tuple, Optional\n\n");
        py.push_str(&format!("_lib_path = os.path.join(os.path.dirname(__file__), '{}.dll')\n", lib_name));
        py.push_str("if not os.path.exists(_lib_path):\n");
        py.push_str(&format!("    _lib_path = os.path.join(os.path.dirname(__file__), 'lib{}.so')\n", lib_name));
        py.push_str("try:\n    _lib = ctypes.CDLL(_lib_path)\nexcept Exception:\n    _lib = None\n\n");

        pyi.push_str("# Type stubs for End Native Module\nfrom typing import Any, Tuple, Optional\n\n");

        // Struct definitions
        for st in &module.structs {
            py.push_str(&format!("class {}(ctypes.Structure):\n    _fields_ = [\n", st.name));
            pyi.push_str(&format!("class {}:\n", st.name));
            for f in &st.fields {
                py.push_str(&format!("        ('{}', {}),\n", f.name, map_type_to_ctypes(&f.field_type)));
                pyi.push_str(&format!("    {}: {}\n", f.name, map_type_to_py_hint(&f.field_type)));
            }
            if st.fields.is_empty() {
                py.push_str("        ('_dummy', ctypes.c_int32)\n");
                pyi.push_str("    pass\n");
            }
            py.push_str("    ]\n\n");
            pyi.push_str("\n");
        }

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let params = func.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
            let params_typed = func.params.iter().map(|p| format!("{}: {}", p.name, map_type_to_py_hint(&p.param_type))).collect::<Vec<_>>().join(", ");
            let ret_hint = map_type_to_py_hint(&func.return_type);

            py.push_str(&format!("if _lib and hasattr(_lib, '{}'):\n", func.name));
            let arg_types = func.params.iter().map(|p| map_type_to_ctypes(&p.param_type)).collect::<Vec<_>>().join(", ");
            py.push_str(&format!("    _lib.{}.argtypes = [{}]\n", func.name, arg_types));
            py.push_str(&format!("    _lib.{}.restype = {}\n\n", func.name, map_type_to_ctypes(&func.return_type)));

            py.push_str(&format!("def {}({}):\n", func.name, params));
            py.push_str(&format!("    if _lib is None:\n        return None\n"));
            py.push_str(&format!("    return _lib.{}({})\n\n", func.name, params));

            pyi.push_str(&format!("def {}({}) -> {}: ...\n", func.name, params_typed, ret_hint));
        }

        (py, pyi)
    }

    fn generate_typescript(module: &Module, lib_name: &str) -> (String, String) {
        let mut ts = String::new();
        let mut dts = String::new();

        ts.push_str("// Auto-generated by End Language Universal Bindgen for TypeScript / Koffi / Bun FFI\n");
        ts.push_str("import * as path from 'path';\n");
        ts.push_str("let koffi: any;\ntry { koffi = require('koffi'); } catch (e) { koffi = null; }\n\n");
        ts.push_str(&format!("export const LIB_NAME = '{}';\n", lib_name));
        ts.push_str("const libPath = process.platform === 'win32' ? path.join(__dirname, `${LIB_NAME}.dll`) : path.join(__dirname, `lib${LIB_NAME}.so`);\n");
        ts.push_str("export const lib = koffi ? koffi.load(libPath) : null;\n\n");

        dts.push_str("// TypeScript Definitions for End Native Module\n\n");

        for st in &module.structs {
            dts.push_str(&format!("export interface {} {{\n", st.name));
            for f in &st.fields {
                dts.push_str(&format!("    {}: {};\n", f.name, map_type_to_ts(&f.field_type)));
            }
            dts.push_str("}\n\n");
        }

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let params_ts = func.params.iter().map(|p| format!("{}: {}", p.name, map_type_to_ts(&p.param_type))).collect::<Vec<_>>().join(", ");
            let params_names = func.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
            let ret_ts = map_type_to_ts(&func.return_type);

            let k_ret = map_type_to_koffi(&func.return_type);
            let k_args = func.params.iter().map(|p| format!("'{}'", map_type_to_koffi(&p.param_type))).collect::<Vec<_>>().join(", ");

            ts.push_str(&format!("const _raw_{} = lib ? lib.func('{}', '{}', [{}]) : null;\n", func.name, func.name, k_ret, k_args));
            ts.push_str(&format!("export function {}({}): {} {{\n", func.name, params_ts, ret_ts));
            ts.push_str(&format!("    if (!_raw_{}) throw new Error('Native library {} not loaded');\n", func.name, lib_name));
            ts.push_str(&format!("    return _raw_{}({});\n}}\n\n", func.name, params_names));

            dts.push_str(&format!("export function {}({}): {};\n", func.name, params_ts, ret_ts));
        }

        (ts, dts)
    }

    fn generate_dart(module: &Module, lib_name: &str) -> String {
        let mut dart = String::new();
        dart.push_str("// Auto-generated by End Language Universal Bindgen for Flutter / Dart FFI\n");
        dart.push_str("import 'dart:ffi' as ffi;\nimport 'dart:io' show Platform;\nimport 'package:ffi/ffi.dart' as pkg_ffi;\n\n");

        for st in &module.structs {
            dart.push_str(&format!("final class {}Native extends ffi.Struct {{\n", st.name));
            for f in &st.fields {
                let ffi_type = map_type_to_dart_ffi(&f.field_type);
                if ffi_type.starts_with("ffi.") {
                    dart.push_str(&format!("  @{}()\n", ffi_type));
                }
                dart.push_str(&format!("  external {} {};\n", map_type_to_dart(&f.field_type), f.name));
            }
            dart.push_str("}\n\n");
        }

        dart.push_str(&format!("class {}NativeBridge {{\n", capitalize(&module.name)));
        dart.push_str("  late ffi.DynamicLibrary _dylib;\n\n");
        dart.push_str(&format!("  {}NativeBridge() {{\n", capitalize(&module.name)));
        dart.push_str(&format!("    _dylib = Platform.isWindows ? ffi.DynamicLibrary.open('{}.dll') : (Platform.isIOS || Platform.isMacOS ? ffi.DynamicLibrary.process() : ffi.DynamicLibrary.open('lib{}.so'));\n", lib_name, lib_name));
        dart.push_str("  }\n\n");

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let native_args = func.params.iter().map(|p| map_type_to_dart_ffi(&p.param_type)).collect::<Vec<_>>().join(", ");
            let native_ret = map_type_to_dart_ffi(&func.return_type);
            let dart_args = func.params.iter().map(|p| map_type_to_dart(&p.param_type)).collect::<Vec<_>>().join(", ");
            let dart_ret = map_type_to_dart(&func.return_type);

            let params_typed = func.params.iter().map(|p| format!("{} {}", map_type_to_dart(&p.param_type), p.name)).collect::<Vec<_>>().join(", ");
            let param_names = func.params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");

            dart.push_str(&format!("  {} {}({}) {{\n", dart_ret, func.name, params_typed));
            dart.push_str(&format!("    final func = _dylib.lookupFunction<{} Function({}), {} Function({})>('{}');\n", native_ret, native_args, dart_ret, dart_args, func.name));
            dart.push_str(&format!("    return func({});\n", param_names));
            dart.push_str("  }\n\n");
        }

        dart.push_str("}\n");
        dart
    }

    fn generate_csharp(module: &Module, lib_name: &str) -> String {
        let mut cs = String::new();
        cs.push_str("// Auto-generated by End Language Universal Bindgen for C# / Unity / .NET\n");
        cs.push_str("using System;\nusing System.Runtime.InteropServices;\n\n");

        for st in &module.structs {
            cs.push_str("    [StructLayout(LayoutKind.Sequential)]\n");
            cs.push_str(&format!("    public struct {}\n    {{\n", st.name));
            for f in &st.fields {
                cs.push_str(&format!("        public {} {};\n", map_type_to_csharp(&f.field_type), f.name));
            }
            cs.push_str("    }\n\n");
        }

        cs.push_str(&format!("public static class {}Native\n{{\n", capitalize(&module.name)));
        cs.push_str(&format!("    private const string LibName = \"{}\";\n\n", lib_name));

        for func in &module.functions {
            if !func.is_pub {
                continue;
            }
            let params = func.params.iter().map(|p| format!("{} {}", map_type_to_csharp(&p.param_type), p.name)).collect::<Vec<_>>().join(", ");
            let ret = map_type_to_csharp(&func.return_type);
            cs.push_str(&format!("    [DllImport(LibName, EntryPoint = \"{}\", CallingConvention = CallingConvention.Cdecl)]\n", func.name));
            cs.push_str(&format!("    public static extern {} {}({});\n\n", ret, func.name, params));
        }

        cs.push_str("}\n");
        cs
    }
}

fn map_type_to_ctypes(ty: &Type) -> String {
    match ty {
        Type::Void => "None".to_string(),
        Type::Bool => "ctypes.c_bool".to_string(),
        Type::I8 => "ctypes.c_int8".to_string(),
        Type::I16 => "ctypes.c_int16".to_string(),
        Type::I32 => "ctypes.c_int32".to_string(),
        Type::I64 => "ctypes.c_int64".to_string(),
        Type::U8 => "ctypes.c_uint8".to_string(),
        Type::U16 => "ctypes.c_uint16".to_string(),
        Type::U32 => "ctypes.c_uint32".to_string(),
        Type::U64 => "ctypes.c_uint64".to_string(),
        Type::F32 => "ctypes.c_float".to_string(),
        Type::F64 => "ctypes.c_double".to_string(),
        Type::Str => "ctypes.c_char_p".to_string(),
        Type::Pointer(_) => "ctypes.c_void_p".to_string(),
        Type::Custom(name) => name.clone(),
        _ => "ctypes.c_int64".to_string(),
    }
}

fn map_type_to_py_hint(ty: &Type) -> String {
    match ty {
        Type::Void => "None".to_string(),
        Type::Bool => "bool".to_string(),
        Type::I8 | Type::I16 | Type::I32 | Type::I64 | Type::U8 | Type::U16 | Type::U32 | Type::U64 => "int".to_string(),
        Type::F32 | Type::F64 => "float".to_string(),
        Type::Str => "str".to_string(),
        Type::Custom(name) => name.clone(),
        _ => "Any".to_string(),
    }
}

fn map_type_to_ts(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Bool => "boolean".to_string(),
        Type::I8 | Type::I16 | Type::I32 | Type::I64 | Type::U8 | Type::U16 | Type::U32 | Type::U64 | Type::F32 | Type::F64 => "number".to_string(),
        Type::Str => "string".to_string(),
        Type::Custom(name) => name.clone(),
        _ => "any".to_string(),
    }
}

fn map_type_to_koffi(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Bool => "bool".to_string(),
        Type::I8 => "int8_t".to_string(),
        Type::I16 => "int16_t".to_string(),
        Type::I32 => "int32_t".to_string(),
        Type::I64 => "int64_t".to_string(),
        Type::U8 => "uint8_t".to_string(),
        Type::U16 => "uint16_t".to_string(),
        Type::U32 => "uint32_t".to_string(),
        Type::U64 => "uint64_t".to_string(),
        Type::F32 => "float".to_string(),
        Type::F64 => "double".to_string(),
        Type::Str => "str".to_string(),
        Type::Pointer(_) => "void*".to_string(),
        _ => "int64_t".to_string(),
    }
}

fn map_type_to_dart_ffi(ty: &Type) -> String {
    match ty {
        Type::Void => "ffi.Void".to_string(),
        Type::Bool => "ffi.Bool".to_string(),
        Type::I8 => "ffi.Int8".to_string(),
        Type::I16 => "ffi.Int16".to_string(),
        Type::I32 => "ffi.Int32".to_string(),
        Type::I64 => "ffi.Int64".to_string(),
        Type::U8 => "ffi.Uint8".to_string(),
        Type::U16 => "ffi.Uint16".to_string(),
        Type::U32 => "ffi.Uint32".to_string(),
        Type::U64 => "ffi.Uint64".to_string(),
        Type::F32 => "ffi.Float".to_string(),
        Type::F64 => "ffi.Double".to_string(),
        Type::Str => "ffi.Pointer<pkg_ffi.Utf8>".to_string(),
        Type::Pointer(_) => "ffi.Pointer<ffi.Void>".to_string(),
        Type::Custom(name) => format!("{}Native", name),
        _ => "ffi.Int64".to_string(),
    }
}

fn map_type_to_dart(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Bool => "bool".to_string(),
        Type::I8 | Type::I16 | Type::I32 | Type::I64 | Type::U8 | Type::U16 | Type::U32 | Type::U64 => "int".to_string(),
        Type::F32 | Type::F64 => "double".to_string(),
        Type::Str => "ffi.Pointer<pkg_ffi.Utf8>".to_string(),
        Type::Pointer(_) => "ffi.Pointer<ffi.Void>".to_string(),
        Type::Custom(name) => format!("{}Native", name),
        _ => "int".to_string(),
    }
}

fn map_type_to_csharp(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Bool => "bool".to_string(),
        Type::I8 => "sbyte".to_string(),
        Type::I16 => "short".to_string(),
        Type::I32 => "int".to_string(),
        Type::I64 => "long".to_string(),
        Type::U8 => "byte".to_string(),
        Type::U16 => "ushort".to_string(),
        Type::U32 => "uint".to_string(),
        Type::U64 => "ulong".to_string(),
        Type::F32 => "float".to_string(),
        Type::F64 => "double".to_string(),
        Type::Str => "[MarshalAs(UnmanagedType.LPUTF8Str)] string".to_string(),
        Type::Pointer(_) => "IntPtr".to_string(),
        Type::Custom(name) => name.clone(),
        _ => "long".to_string(),
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

