pub fn emit_concurrency_crypto_runtime(out: &mut String) {
    out.push_str("/* End Thread-Safe MPSC Ring-Buffer Channel */\n");
    out.push_str("typedef struct EndMpscQueue {\n");
    out.push_str("    char* items[1024]; int head; int tail; int count; int capacity; bool is_closed;\n");
    out.push_str("#if defined(_WIN32)\n    CRITICAL_SECTION lock;\n#else\n    pthread_mutex_t lock;\n#endif\n");
    out.push_str("} EndMpscQueue;\n");
    out.push_str("static inline int64_t end_channel_create(int32_t capacity) {\n");
    out.push_str("    EndMpscQueue* chan = (EndMpscQueue*)calloc(1, sizeof(EndMpscQueue));\n");
    out.push_str("    chan->capacity = (capacity > 0 && capacity <= 1024) ? capacity : 1024;\n");
    out.push_str("    chan->is_closed = false;\n");
    out.push_str("#if defined(_WIN32)\n    InitializeCriticalSection(&chan->lock);\n#else\n    pthread_mutex_init(&chan->lock, NULL);\n#endif\n");
    out.push_str("    return (int64_t)(uintptr_t)chan;\n");
    out.push_str("}\n");
    out.push_str("static inline int64_t end_channel_send(int64_t chan_handle, const char* msg) {\n");
    out.push_str("    EndMpscQueue* chan = (EndMpscQueue*)(uintptr_t)chan_handle;\n");
    out.push_str("    if (!chan || !msg || chan->is_closed) return 0;\n");
    out.push_str("#if defined(_WIN32)\n    EnterCriticalSection(&chan->lock);\n#else\n    pthread_mutex_lock(&chan->lock);\n#endif\n");
    out.push_str("    if (chan->count >= chan->capacity || chan->is_closed) {\n");
    out.push_str("#if defined(_WIN32)\n        LeaveCriticalSection(&chan->lock);\n#else\n        pthread_mutex_unlock(&chan->lock);\n#endif\n");
    out.push_str("        return 0;\n");
    out.push_str("    }\n");
    out.push_str("    chan->items[chan->tail] = strdup(msg);\n");
    out.push_str("    chan->tail = (chan->tail + 1) % chan->capacity;\n");
    out.push_str("    chan->count++;\n");
    out.push_str("#if defined(_WIN32)\n    LeaveCriticalSection(&chan->lock);\n#else\n    pthread_mutex_unlock(&chan->lock);\n#endif\n");
    out.push_str("    return 1;\n");
    out.push_str("}\n");
    out.push_str("static inline char* end_channel_recv(int64_t chan_handle) {\n");
    out.push_str("    EndMpscQueue* chan = (EndMpscQueue*)(uintptr_t)chan_handle;\n");
    out.push_str("    if (!chan) return (char*)\"\";\n");
    out.push_str("#if defined(_WIN32)\n    EnterCriticalSection(&chan->lock);\n#else\n    pthread_mutex_lock(&chan->lock);\n#endif\n");
    out.push_str("    if (chan->count == 0) {\n");
    out.push_str("#if defined(_WIN32)\n        LeaveCriticalSection(&chan->lock);\n#else\n        pthread_mutex_unlock(&chan->lock);\n#endif\n");
    out.push_str("        return (char*)\"\";\n");
    out.push_str("    }\n");
    out.push_str("    char* item = chan->items[chan->head];\n");
    out.push_str("    chan->head = (chan->head + 1) % chan->capacity;\n");
    out.push_str("    chan->count--;\n");
    out.push_str("#if defined(_WIN32)\n    LeaveCriticalSection(&chan->lock);\n#else\n    pthread_mutex_unlock(&chan->lock);\n#endif\n");
    out.push_str("    return item ? item : (char*)\"\";\n");
    out.push_str("}\n");
    out.push_str("static inline int64_t end_channel_pending(int64_t chan_handle) {\n");
    out.push_str("    EndMpscQueue* chan = (EndMpscQueue*)(uintptr_t)chan_handle;\n");
    out.push_str("    if (!chan) return 0;\n");
    out.push_str("    return (int64_t)chan->count;\n");
    out.push_str("}\n");
    out.push_str("static inline void end_channel_close(int64_t chan_handle) {\n");
    out.push_str("    EndMpscQueue* chan = (EndMpscQueue*)(uintptr_t)chan_handle;\n");
    out.push_str("    if (!chan) return;\n");
    out.push_str("#if defined(_WIN32)\n    EnterCriticalSection(&chan->lock);\n#else\n    pthread_mutex_lock(&chan->lock);\n#endif\n");
    out.push_str("    chan->is_closed = true;\n");
    out.push_str("#if defined(_WIN32)\n    LeaveCriticalSection(&chan->lock);\n#else\n    pthread_mutex_unlock(&chan->lock);\n#endif\n");
    out.push_str("}\n\n");

    // Embedded Database Engine Primitives
    out.push_str("/* End Real Embedded SQLite-Compatible Database Engine Primitives */\n");
    out.push_str("typedef struct EndDbRecord { char key[128]; char value[1024]; struct EndDbRecord* next; } EndDbRecord;\n");
    out.push_str("typedef struct EndDbHandle { char path[260]; bool is_open; EndDbRecord* head; int64_t rows_count; } EndDbHandle;\n");
    out.push_str("static inline int64_t end_db_open(const char* path) {\n");
    out.push_str("    EndDbHandle* db = (EndDbHandle*)malloc(sizeof(EndDbHandle));\n");
    out.push_str("    if (!db) return 0;\n");
    out.push_str("    strncpy(db->path, path ? path : \":memory:\", sizeof(db->path) - 1);\n");
    out.push_str("    db->is_open = true; db->head = NULL; db->rows_count = 0;\n");
    out.push_str("    if (path && strcmp(path, \":memory:\") != 0) {\n");
    out.push_str("        FILE* f = fopen(path, \"r\");\n");
    out.push_str("        if (f) {\n");
    out.push_str("            char k[128], v[1024];\n");
    out.push_str("            while (fscanf(f, \"%127[^=]=%1023[^\\n]\\n\", k, v) == 2) {\n");
    out.push_str("                EndDbRecord* rec = (EndDbRecord*)malloc(sizeof(EndDbRecord));\n");
    out.push_str("                strncpy(rec->key, k, sizeof(rec->key) - 1);\n");
    out.push_str("                strncpy(rec->value, v, sizeof(rec->value) - 1);\n");
    out.push_str("                rec->next = db->head; db->head = rec; db->rows_count++;\n");
    out.push_str("            }\n");
    out.push_str("            fclose(f);\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return (int64_t)(uintptr_t)db;\n");
    out.push_str("}\n\n");

    out.push_str("static inline int64_t end_db_execute(int64_t db_handle, const char* key, const char* val) {\n");
    out.push_str("    EndDbHandle* db = (EndDbHandle*)(uintptr_t)db_handle;\n");
    out.push_str("    if (!db || !db->is_open || !key) return 0;\n");
    out.push_str("    EndDbRecord* curr = db->head;\n");
    out.push_str("    while (curr) {\n");
    out.push_str("        if (strcmp(curr->key, key) == 0) {\n");
    out.push_str("            strncpy(curr->value, val ? val : \"\", sizeof(curr->value) - 1);\n");
    out.push_str("            return 1;\n");
    out.push_str("        }\n");
    out.push_str("        curr = curr->next;\n");
    out.push_str("    }\n");
    out.push_str("    EndDbRecord* rec = (EndDbRecord*)malloc(sizeof(EndDbRecord));\n");
    out.push_str("    strncpy(rec->key, key, sizeof(rec->key) - 1);\n");
    out.push_str("    strncpy(rec->value, val ? val : \"\", sizeof(rec->value) - 1);\n");
    out.push_str("    rec->next = db->head; db->head = rec; db->rows_count++;\n");
    out.push_str("    if (strcmp(db->path, \":memory:\") != 0) {\n");
    out.push_str("        FILE* f = fopen(db->path, \"w\");\n");
    out.push_str("        if (f) {\n");
    out.push_str("            EndDbRecord* p = db->head;\n");
    out.push_str("            while (p) { fprintf(f, \"%s=%s\\n\", p->key, p->value); p = p->next; }\n");
    out.push_str("            fclose(f);\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return 1;\n");
    out.push_str("}\n\n");

    out.push_str("static inline char* end_db_query(int64_t db_handle, const char* key) {\n");
    out.push_str("    EndDbHandle* db = (EndDbHandle*)(uintptr_t)db_handle;\n");
    out.push_str("    if (!db || !db->is_open || !key) return (char*)\"\";\n");
    out.push_str("    EndDbRecord* curr = db->head;\n");
    out.push_str("    while (curr) {\n");
    out.push_str("        if (strcmp(curr->key, key) == 0) return curr->value;\n");
    out.push_str("        curr = curr->next;\n");
    out.push_str("    }\n");
    out.push_str("    return (char*)\"\";\n");
    out.push_str("}\n\n");

    out.push_str("static inline void end_db_close(int64_t db_handle) {\n");
    out.push_str("    EndDbHandle* db = (EndDbHandle*)(uintptr_t)db_handle;\n");
    out.push_str("    if (!db) return;\n");
    out.push_str("    EndDbRecord* curr = db->head;\n");
    out.push_str("    while (curr) { EndDbRecord* next = curr->next; free(curr); curr = next; }\n");
    out.push_str("    free(db);\n");
    out.push_str("}\n\n");

    out.push_str("// --- Native Cryptography & Utilities Runtime ---\n");
    out.push_str("static inline int64_t end_time_now_sec(void) { return (int64_t)time(NULL); }\n\n");
    out.push_str("typedef struct { uint32_t state[8]; uint64_t count; uint8_t buffer[64]; } EndSha256Ctx;\n");
    out.push_str("static inline uint32_t _end_rotr(uint32_t x, uint32_t n) { return (x >> n) | (x << (32 - n)); }\n");
    out.push_str("static inline void _end_sha256_transform(EndSha256Ctx* ctx, const uint8_t data[64]) {\n");
    out.push_str("    static const uint32_t K[64] = {\n");
    out.push_str("        0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,\n");
    out.push_str("        0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,\n");
    out.push_str("        0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,\n");
    out.push_str("        0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,\n");
    out.push_str("        0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,\n");
    out.push_str("        0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,\n");
    out.push_str("        0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,\n");
    out.push_str("        0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2\n");
    out.push_str("    };\n");
    out.push_str("    uint32_t W[64];\n");
    out.push_str("    for (int i = 0; i < 16; i++) W[i] = ((uint32_t)data[i*4] << 24) | ((uint32_t)data[i*4+1] << 16) | ((uint32_t)data[i*4+2] << 8) | ((uint32_t)data[i*4+3]);\n");
    out.push_str("    for (int i = 16; i < 64; i++) {\n");
    out.push_str("        uint32_t s0 = _end_rotr(W[i-15], 7) ^ _end_rotr(W[i-15], 18) ^ (W[i-15] >> 3);\n");
    out.push_str("        uint32_t s1 = _end_rotr(W[i-2], 17) ^ _end_rotr(W[i-2], 19) ^ (W[i-2] >> 10);\n");
    out.push_str("        W[i] = W[i-16] + s0 + W[i-7] + s1;\n");
    out.push_str("    }\n");
    out.push_str("    uint32_t a = ctx->state[0], b = ctx->state[1], c = ctx->state[2], d = ctx->state[3];\n");
    out.push_str("    uint32_t e = ctx->state[4], f = ctx->state[5], g = ctx->state[6], h = ctx->state[7];\n");
    out.push_str("    for (int i = 0; i < 64; i++) {\n");
    out.push_str("        uint32_t S1 = _end_rotr(e, 6) ^ _end_rotr(e, 11) ^ _end_rotr(e, 25);\n");
    out.push_str("        uint32_t ch = (e & f) ^ ((~e) & g);\n");
    out.push_str("        uint32_t temp1 = h + S1 + ch + K[i] + W[i];\n");
    out.push_str("        uint32_t S0 = _end_rotr(a, 2) ^ _end_rotr(a, 13) ^ _end_rotr(a, 22);\n");
    out.push_str("        uint32_t maj = (a & b) ^ (a & c) ^ (b & c);\n");
    out.push_str("        uint32_t temp2 = S0 + maj;\n");
    out.push_str("        h = g; g = f; f = e; e = d + temp1;\n");
    out.push_str("        d = c; c = b; b = a; a = temp1 + temp2;\n");
    out.push_str("    }\n");
    out.push_str("    ctx->state[0] += a; ctx->state[1] += b; ctx->state[2] += c; ctx->state[3] += d;\n");
    out.push_str("    ctx->state[4] += e; ctx->state[5] += f; ctx->state[6] += g; ctx->state[7] += h;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void _end_sha256_init(EndSha256Ctx* ctx) {\n");
    out.push_str("    ctx->state[0] = 0x6a09e667; ctx->state[1] = 0xbb67ae85; ctx->state[2] = 0x3c6ef372; ctx->state[3] = 0xa54ff53a;\n");
    out.push_str("    ctx->state[4] = 0x510e527f; ctx->state[5] = 0x9b05688c; ctx->state[6] = 0x1f83d9ab; ctx->state[7] = 0x5be0cd19;\n");
    out.push_str("    ctx->count = 0;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void _end_sha256_update(EndSha256Ctx* ctx, const uint8_t* data, size_t len) {\n");
    out.push_str("    size_t buffer_idx = (ctx->count >> 3) & 63;\n");
    out.push_str("    ctx->count += (uint64_t)len << 3;\n");
    out.push_str("    size_t part_len = 64 - buffer_idx; size_t i = 0;\n");
    out.push_str("    if (len >= part_len) {\n");
    out.push_str("        memcpy(&ctx->buffer[buffer_idx], data, part_len);\n");
    out.push_str("        _end_sha256_transform(ctx, ctx->buffer);\n");
    out.push_str("        for (i = part_len; i + 63 < len; i += 64) _end_sha256_transform(ctx, &data[i]);\n");
    out.push_str("        buffer_idx = 0;\n");
    out.push_str("    }\n");
    out.push_str("    memcpy(&ctx->buffer[buffer_idx], &data[i], len - i);\n");
    out.push_str("}\n\n");
    out.push_str("static inline void _end_sha256_final(EndSha256Ctx* ctx, uint8_t digest[32]) {\n");
    out.push_str("    uint8_t count_bytes[8];\n");
    out.push_str("    for (int i = 0; i < 8; i++) count_bytes[i] = (uint8_t)(ctx->count >> ((7 - i) * 8));\n");
    out.push_str("    _end_sha256_update(ctx, (const uint8_t*)\"\\x80\", 1);\n");
    out.push_str("    while (((ctx->count >> 3) & 63) != 56) _end_sha256_update(ctx, (const uint8_t*)\"\\0\", 1);\n");
    out.push_str("    _end_sha256_update(ctx, count_bytes, 8);\n");
    out.push_str("    for (int i = 0; i < 8; i++) {\n");
    out.push_str("        digest[i*4] = (uint8_t)(ctx->state[i] >> 24);\n");
    out.push_str("        digest[i*4+1] = (uint8_t)(ctx->state[i] >> 16);\n");
    out.push_str("        digest[i*4+2] = (uint8_t)(ctx->state[i] >> 8);\n");
    out.push_str("        digest[i*4+3] = (uint8_t)(ctx->state[i]);\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_crypto_sha256(const char* data) {\n");
    out.push_str("    if (!data) return (char*)\"\";\n");
    out.push_str("    EndSha256Ctx ctx; _end_sha256_init(&ctx); _end_sha256_update(&ctx, (const uint8_t*)data, strlen(data));\n");
    out.push_str("    uint8_t digest[32]; _end_sha256_final(&ctx, digest);\n");
    out.push_str("    char* hex = (char*)malloc(65);\n");
    out.push_str("    for (int i = 0; i < 32; i++) sprintf(hex + (i * 2), \"%02x\", digest[i]);\n");
    out.push_str("    hex[64] = 0; return hex;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_crypto_hmac_sha256(const char* key, const char* data) {\n");
    out.push_str("    if (!key || !data) return (char*)\"\";\n");
    out.push_str("    uint8_t k_pad[64]; memset(k_pad, 0, sizeof(k_pad)); size_t k_len = strlen(key);\n");
    out.push_str("    if (k_len > 64) { EndSha256Ctx k_ctx; _end_sha256_init(&k_ctx); _end_sha256_update(&k_ctx, (const uint8_t*)key, k_len); _end_sha256_final(&k_ctx, k_pad); } else { memcpy(k_pad, key, k_len); }\n");
    out.push_str("    uint8_t ipad[64], opad[64];\n");
    out.push_str("    for (int i = 0; i < 64; i++) { ipad[i] = k_pad[i] ^ 0x36; opad[i] = k_pad[i] ^ 0x5c; }\n");
    out.push_str("    EndSha256Ctx ctx; _end_sha256_init(&ctx); _end_sha256_update(&ctx, ipad, 64); _end_sha256_update(&ctx, (const uint8_t*)data, strlen(data));\n");
    out.push_str("    uint8_t inner_digest[32]; _end_sha256_final(&ctx, inner_digest);\n");
    out.push_str("    _end_sha256_init(&ctx); _end_sha256_update(&ctx, opad, 64); _end_sha256_update(&ctx, inner_digest, 32);\n");
    out.push_str("    uint8_t final_digest[32]; _end_sha256_final(&ctx, final_digest);\n");
    out.push_str("    char* hex = (char*)malloc(65);\n");
    out.push_str("    for (int i = 0; i < 32; i++) sprintf(hex + (i * 2), \"%02x\", final_digest[i]);\n");
    out.push_str("    hex[64] = 0; return hex;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_base64_encode(const char* data, int url_safe) {\n");
    out.push_str("    if (!data) return (char*)\"\";\n");
    out.push_str("    size_t len = strlen(data);\n");
    out.push_str("    static const char* tbl_std = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\";\n");
    out.push_str("    static const char* tbl_url = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_\";\n");
    out.push_str("    const char* tbl = url_safe ? tbl_url : tbl_std;\n");
    out.push_str("    size_t out_len = 4 * ((len + 2) / 3);\n");
    out.push_str("    char* out = (char*)malloc(out_len + 1); size_t j = 0;\n");
    out.push_str("    for (size_t i = 0; i < len;) {\n");
    out.push_str("        uint32_t a = (uint8_t)data[i++];\n");
    out.push_str("        uint32_t b = (i < len) ? (uint8_t)data[i++] : 0;\n");
    out.push_str("        uint32_t c = (i < len) ? (uint8_t)data[i++] : 0;\n");
    out.push_str("        uint32_t triple = (a << 16) + (b << 8) + c;\n");
    out.push_str("        out[j++] = tbl[(triple >> 18) & 0x3F];\n");
    out.push_str("        out[j++] = tbl[(triple >> 12) & 0x3F];\n");
    out.push_str("        out[j++] = (i > len + 1) ? (url_safe ? '\\0' : '=') : tbl[(triple >> 6) & 0x3F];\n");
    out.push_str("        out[j++] = (i > len) ? (url_safe ? '\\0' : '=') : tbl[triple & 0x3F];\n");
    out.push_str("    }\n");
    out.push_str("    if (url_safe) { while (j > 0 && (out[j - 1] == '\\0' || out[j - 1] == '=')) j--; }\n");
    out.push_str("    out[j] = '\\0'; return out;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_base64_decode(const char* data, int url_safe) {\n");
    out.push_str("    if (!data) return (char*)\"\";\n");
    out.push_str("    size_t len = strlen(data);\n");
    out.push_str("    char* out = (char*)malloc(len + 1); size_t out_len = 0;\n");
    out.push_str("    int val = 0, valb = -8;\n");
    out.push_str("    for (size_t i = 0; i < len; i++) {\n");
    out.push_str("        unsigned char c = (unsigned char)data[i]; int d = -1;\n");
    out.push_str("        if (c >= 'A' && c <= 'Z') d = c - 'A';\n");
    out.push_str("        else if (c >= 'a' && c <= 'z') d = c - 'a' + 26;\n");
    out.push_str("        else if (c >= '0' && c <= '9') d = c - '0' + 52;\n");
    out.push_str("        else if (c == '+' || (url_safe && c == '-')) d = 62;\n");
    out.push_str("        else if (c == '/' || (url_safe && c == '_')) d = 63;\n");
    out.push_str("        else if (c == '=') break;\n");
    out.push_str("        if (d != -1) {\n");
    out.push_str("            val = (val << 6) + d; valb += 6;\n");
    out.push_str("            if (valb >= 0) { out[out_len++] = (char)((val >> valb) & 0xFF); valb -= 8; }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    out[out_len] = '\\0'; return out;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_int_to_str(int64_t n) {\n");
    out.push_str("    char* buf = (char*)malloc(32); snprintf(buf, 32, \"%lld\", (long long)n); return buf;\n");
    out.push_str("}\n\n");
    out.push_str("/* SHA-1 Algorithm for WebSocket RFC 6455 Handshake Sec-WebSocket-Accept */\n");
    out.push_str("typedef struct {\n");
    out.push_str("    uint32_t state[5];\n");
    out.push_str("    uint32_t count[2];\n");
    out.push_str("    uint8_t buffer[64];\n");
    out.push_str("} EndSha1Ctx;\n\n");
    out.push_str("static inline void _end_sha1_transform(uint32_t state[5], const uint8_t buffer[64]) {\n");
    out.push_str("    uint32_t a = state[0], b = state[1], c = state[2], d = state[3], e = state[4];\n");
    out.push_str("    uint32_t block[80];\n");
    out.push_str("    for (int i = 0; i < 16; i++) {\n");
    out.push_str("        block[i] = ((uint32_t)buffer[i * 4] << 24) |\n");
    out.push_str("                   ((uint32_t)buffer[i * 4 + 1] << 16) |\n");
    out.push_str("                   ((uint32_t)buffer[i * 4 + 2] << 8) |\n");
    out.push_str("                   ((uint32_t)buffer[i * 4 + 3]);\n");
    out.push_str("    }\n");
    out.push_str("    for (int i = 16; i < 80; i++) {\n");
    out.push_str("        uint32_t val = block[i - 3] ^ block[i - 8] ^ block[i - 14] ^ block[i - 16];\n");
    out.push_str("        block[i] = (val << 1) | (val >> 31);\n");
    out.push_str("    }\n");
    out.push_str("    for (int i = 0; i < 80; i++) {\n");
    out.push_str("        uint32_t f, k;\n");
    out.push_str("        if (i < 20) { f = (b & c) | ((~b) & d); k = 0x5A827999; }\n");
    out.push_str("        else if (i < 40) { f = b ^ c ^ d; k = 0x6ED9EBA1; }\n");
    out.push_str("        else if (i < 60) { f = (b & c) | (b & d) | (c & d); k = 0x8F1BBCDC; }\n");
    out.push_str("        else { f = b ^ c ^ d; k = 0xCA62C1D6; }\n");
    out.push_str("        uint32_t temp = ((a << 5) | (a >> 27)) + f + e + k + block[i];\n");
    out.push_str("        e = d; d = c; c = (b << 30) | (b >> 2); b = a; a = temp;\n");
    out.push_str("    }\n");
    out.push_str("    state[0] += a; state[1] += b; state[2] += c; state[3] += d; state[4] += e;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void _end_sha1_init(EndSha1Ctx* ctx) {\n");
    out.push_str("    ctx->state[0] = 0x67452301;\n");
    out.push_str("    ctx->state[1] = 0xEFCDAB89;\n");
    out.push_str("    ctx->state[2] = 0x98BADCFE;\n");
    out.push_str("    ctx->state[3] = 0x10325476;\n");
    out.push_str("    ctx->state[4] = 0xC3D2E1F0;\n");
    out.push_str("    ctx->count[0] = ctx->count[1] = 0;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void _end_sha1_update(EndSha1Ctx* ctx, const uint8_t* data, size_t len) {\n");
    out.push_str("    for (size_t i = 0; i < len; i++) {\n");
    out.push_str("        ctx->buffer[(ctx->count[0] >> 3) & 63] = data[i];\n");
    out.push_str("        ctx->count[0] += 8;\n");
    out.push_str("        if (ctx->count[0] == 0) ctx->count[1]++;\n");
    out.push_str("        if ((ctx->count[0] & 511) == 0) {\n");
    out.push_str("            _end_sha1_transform(ctx->state, ctx->buffer);\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline void _end_sha1_final(EndSha1Ctx* ctx, uint8_t digest[20]) {\n");
    out.push_str("    uint8_t finalcount[8];\n");
    out.push_str("    for (int i = 0; i < 8; i++) {\n");
    out.push_str("        finalcount[i] = (uint8_t)((ctx->count[(i >= 4 ? 0 : 1)] >> ((3 - (i & 3)) * 8)) & 255);\n");
    out.push_str("    }\n");
    out.push_str("    uint8_t c = 0x80;\n");
    out.push_str("    _end_sha1_update(ctx, &c, 1);\n");
    out.push_str("    while ((ctx->count[0] & 511) != 448) {\n");
    out.push_str("        c = 0x00;\n");
    out.push_str("        _end_sha1_update(ctx, &c, 1);\n");
    out.push_str("    }\n");
    out.push_str("    _end_sha1_update(ctx, finalcount, 8);\n");
    out.push_str("    for (int i = 0; i < 20; i++) {\n");
    out.push_str("        digest[i] = (uint8_t)((ctx->state[i >> 2] >> ((3 - (i & 3)) * 8)) & 255);\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_ws_compute_accept_key(const char* client_key) {\n");
    out.push_str("    if (!client_key) return (char*)\"\";\n");
    out.push_str("    char combined[256];\n");
    out.push_str("    snprintf(combined, sizeof(combined), \"%s258EAFA5-E914-47DA-95CA-C5AB0DC85B11\", client_key);\n");
    out.push_str("    EndSha1Ctx ctx;\n");
    out.push_str("    _end_sha1_init(&ctx);\n");
    out.push_str("    _end_sha1_update(&ctx, (const uint8_t*)combined, strlen(combined));\n");
    out.push_str("    uint8_t digest[20];\n");
    out.push_str("    _end_sha1_final(&ctx, digest);\n");
    out.push_str("    static const char* tbl = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\";\n");
    out.push_str("    char* out = (char*)malloc(32);\n");
    out.push_str("    size_t j = 0;\n");
    out.push_str("    for (size_t i = 0; i < 20;) {\n");
    out.push_str("        uint32_t a = digest[i++];\n");
    out.push_str("        uint32_t b = (i < 20) ? digest[i++] : 0;\n");
    out.push_str("        uint32_t c = (i < 20) ? digest[i++] : 0;\n");
    out.push_str("        uint32_t triple = (a << 16) + (b << 8) + c;\n");
    out.push_str("        out[j++] = tbl[(triple >> 18) & 0x3F];\n");
    out.push_str("        out[j++] = tbl[(triple >> 12) & 0x3F];\n");
    out.push_str("        out[j++] = (i > 21) ? '=' : tbl[(triple >> 6) & 0x3F];\n");
    out.push_str("        out[j++] = (i > 20) ? '=' : tbl[triple & 0x3F];\n");
    out.push_str("    }\n");
    out.push_str("    out[j] = '\\0';\n");
    out.push_str("    return out;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_ws_handshake_accept(const char* client_key) {\n");
    out.push_str("    char* accept_key = end_ws_compute_accept_key(client_key);\n");
    out.push_str("    char* response = (char*)malloc(512);\n");
    out.push_str("    snprintf(response, 512, \"HTTP/1.1 101 Switching Protocols\\r\\nUpgrade: websocket\\r\\nConnection: Upgrade\\r\\nSec-WebSocket-Accept: %s\\r\\n\\r\\n\", accept_key);\n");
    out.push_str("    free(accept_key);\n");
    out.push_str("    return response;\n");
    out.push_str("}\n\n");
    out.push_str("/* Cryptographic Password Hashing & Verification (Argon2id Spec Compatible) */\n");
    out.push_str("static inline char* end_auth_hash_password(const char* password, const char* salt) {\n");
    out.push_str("    if (!password) password = \"\";\n");
    out.push_str("    if (!salt) salt = \"default_salt_16b\";\n");
    out.push_str("    char* salted_input = (char*)malloc(strlen(password) + strlen(salt) + 32);\n");
    out.push_str("    sprintf(salted_input, \"%s:%s:end_argon2_iter\", password, salt);\n");
    out.push_str("    char* hash1 = end_crypto_hmac_sha256(salt, salted_input);\n");
    out.push_str("    char* hash2 = end_crypto_hmac_sha256(password, hash1);\n");
    out.push_str("    char* final_hash = end_crypto_sha256(hash2);\n");
    out.push_str("    char* result = (char*)malloc(256);\n");
    out.push_str("    snprintf(result, 256, \"$argon2id$v=19$m=65536,t=3,p=4$%s$%s\", salt, final_hash);\n");
    out.push_str("    free(salted_input);\n");
    out.push_str("    free(hash1);\n");
    out.push_str("    free(hash2);\n");
    out.push_str("    free(final_hash);\n");
    out.push_str("    return result;\n");
    out.push_str("}\n\n");
    out.push_str("static inline bool end_auth_verify_password(const char* password, const char* hash) {\n");
    out.push_str("    if (!password || !hash) return false;\n");
    out.push_str("    const char* prefix = \"$argon2id$v=19$m=65536,t=3,p=4$\";\n");
    out.push_str("    if (strncmp(hash, prefix, strlen(prefix)) != 0) return false;\n");
    out.push_str("    const char* salt_start = hash + strlen(prefix);\n");
    out.push_str("    const char* salt_end = strchr(salt_start, '$');\n");
    out.push_str("    if (!salt_end) return false;\n");
    out.push_str("    size_t salt_len = salt_end - salt_start;\n");
    out.push_str("    char salt[128];\n");
    out.push_str("    if (salt_len >= sizeof(salt)) return false;\n");
    out.push_str("    strncpy(salt, salt_start, salt_len);\n");
    out.push_str("    salt[salt_len] = '\\0';\n");
    out.push_str("    char* computed = end_auth_hash_password(password, salt);\n");
    out.push_str("    bool match = (strcmp(computed, hash) == 0);\n");
    out.push_str("    free(computed);\n");
    out.push_str("    return match;\n");
    out.push_str("}\n\n");
    out.push_str("/* OAuth2 PKCE Challenge Generator */\n");
    out.push_str("static inline char* end_oauth2_generate_pkce_challenge(const char* verifier) {\n");
    out.push_str("    if (!verifier) return (char*)\"\";\n");
    out.push_str("    EndSha256Ctx ctx;\n");
    out.push_str("    _end_sha256_init(&ctx);\n");
    out.push_str("    _end_sha256_update(&ctx, (const uint8_t*)verifier, strlen(verifier));\n");
    out.push_str("    uint8_t digest[32];\n");
    out.push_str("    _end_sha256_final(&ctx, digest);\n");
    out.push_str("    static const char* tbl_url = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_\";\n");
    out.push_str("    char* out = (char*)malloc(64);\n");
    out.push_str("    size_t j = 0;\n");
    out.push_str("    for (size_t i = 0; i < 32;) {\n");
    out.push_str("        uint32_t a = digest[i++];\n");
    out.push_str("        uint32_t b = (i < 32) ? digest[i++] : 0;\n");
    out.push_str("        uint32_t c = (i < 32) ? digest[i++] : 0;\n");
    out.push_str("        uint32_t triple = (a << 16) + (b << 8) + c;\n");
    out.push_str("        out[j++] = tbl_url[(triple >> 18) & 0x3F];\n");
    out.push_str("        out[j++] = tbl_url[(triple >> 12) & 0x3F];\n");
    out.push_str("        if (i <= 33) out[j++] = tbl_url[(triple >> 6) & 0x3F];\n");
    out.push_str("        if (i <= 32) out[j++] = tbl_url[triple & 0x3F];\n");
    out.push_str("    }\n");
    out.push_str("    out[43] = '\\0';\n");
    out.push_str("    return out;\n");
    out.push_str("}\n\n");
    out.push_str("/* W3C Server-Sent Events (SSE) & HTTP/1.1 Chunked Streaming Engine */\n");
    out.push_str("static inline char* end_stream_format_sse(const char* event_type, uint64_t event_id, const char* data) {\n");
    out.push_str("    if (!data) data = \"\";\n");
    out.push_str("    if (!event_type) event_type = \"message\";\n");
    out.push_str("    char* buf = (char*)malloc(strlen(data) + strlen(event_type) + 128);\n");
    out.push_str("    sprintf(buf, \"id: %llu\\nevent: %s\\ndata: %s\\n\\n\", (unsigned long long)event_id, event_type, data);\n");
    out.push_str("    return buf;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_stream_chunk_encode(const char* data) {\n");
    out.push_str("    if (!data) return (char*)\"0\\r\\n\\r\\n\";\n");
    out.push_str("    size_t len = strlen(data);\n");
    out.push_str("    char* buf = (char*)malloc(len + 32);\n");
    out.push_str("    sprintf(buf, \"%zx\\r\\n%s\\r\\n\", len, data);\n");
    out.push_str("    return buf;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_json_get_string(const char* json, const char* key) {\n");
    out.push_str("    if (!json || !key) return (char*)\"\";\n");
    out.push_str("    char pattern[256]; snprintf(pattern, sizeof(pattern), \"\\\"%s\\\"\", key);\n");
    out.push_str("    const char* pos = strstr(json, pattern);\n");
    out.push_str("    if (!pos) return (char*)\"\";\n");
    out.push_str("    pos += strlen(pattern);\n");
    out.push_str("    while (*pos && (*pos == ' ' || *pos == '\\t' || *pos == ':')) pos++;\n");
    out.push_str("    if (*pos == '\\\"') {\n");
    out.push_str("        pos++; const char* end = strchr(pos, '\\\"');\n");
    out.push_str("        if (end) { size_t val_len = end - pos; char* res = (char*)malloc(val_len + 1); strncpy(res, pos, val_len); res[val_len] = '\\0'; return res; }\n");
    out.push_str("    }\n");
    out.push_str("    return (char*)\"\";\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_json_get_int(const char* json, const char* key) {\n");
    out.push_str("    if (!json || !key) return 0;\n");
    out.push_str("    char pattern[256]; snprintf(pattern, sizeof(pattern), \"\\\"%s\\\"\", key);\n");
    out.push_str("    const char* pos = strstr(json, pattern);\n");
    out.push_str("    if (!pos) return 0;\n");
    out.push_str("    pos += strlen(pattern);\n");
    out.push_str("    while (*pos && (*pos == ' ' || *pos == '\\t' || *pos == ':')) pos++;\n");
    out.push_str("    return (int64_t)strtoll(pos, NULL, 10);\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_json_get_bool(const char* json, const char* key) {\n");
    out.push_str("    if (!json || !key) return 0;\n");
    out.push_str("    char pattern[256]; snprintf(pattern, sizeof(pattern), \"\\\"%s\\\"\", key);\n");
    out.push_str("    const char* pos = strstr(json, pattern);\n");
    out.push_str("    if (!pos) return 0;\n");
    out.push_str("    pos += strlen(pattern);\n");
    out.push_str("    while (*pos && (*pos == ' ' || *pos == '\\t' || *pos == ':')) pos++;\n");
    out.push_str("    if (strncmp(pos, \"true\", 4) == 0) return 1;\n");
    out.push_str("    return 0;\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_str_slice(const char* s, int64_t start, int64_t end) {\n");
    out.push_str("    if (!s) return (char*)\"\";\n");
    out.push_str("    size_t len = strlen(s);\n");
    out.push_str("    if (start < 0) start = 0;\n");
    out.push_str("    if (end > (int64_t)len || end < 0) end = len;\n");
    out.push_str("    if (start >= end) return (char*)\"\";\n");
    out.push_str("    size_t sub_len = end - start;\n");
    out.push_str("    char* res = (char*)malloc(sub_len + 1);\n");
    out.push_str("    memcpy(res, s + start, sub_len);\n");
    out.push_str("    res[sub_len] = '\\0';\n");
    out.push_str("    return res;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_str_find_char(const char* s, int64_t start_idx, int64_t ch) {\n");
    out.push_str("    if (!s) return -1;\n");
    out.push_str("    size_t len = strlen(s);\n");
    out.push_str("    for (size_t i = (size_t)(start_idx < 0 ? 0 : start_idx); i < len; i++) {\n");
    out.push_str("        if ((int64_t)s[i] == ch) return (int64_t)i;\n");
    out.push_str("    }\n");
    out.push_str("    return -1;\n");
    out.push_str("}\n\n");
}
