pub fn emit_desktop_and_memory_runtime(out: &mut String) {
    // Native Desktop Windowing & GUI Runtime
    out.push_str("/* End Native Desktop Windowing Runtime */\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("#define WIN32_LEAN_AND_MEAN\n");
    out.push_str("#include <windows.h>\n");
    out.push_str("typedef struct EndWindow {\n");
    out.push_str("    HWND hwnd;\n");
    out.push_str("    HDC hdc;\n");
    out.push_str("    int32_t width;\n");
    out.push_str("    int32_t height;\n");
    out.push_str("    bool is_open;\n");
    out.push_str("    BITMAPINFO bmi;\n");
    out.push_str("} EndWindow;\n");
    out.push_str("static LRESULT CALLBACK EndWndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {\n");
    out.push_str("    if (msg == WM_DESTROY || msg == WM_CLOSE) { PostQuitMessage(0); return 0; }\n");
    out.push_str("    return DefWindowProcA(hWnd, msg, wParam, lParam);\n");
    out.push_str("}\n");
    out.push_str("static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) {\n");
    out.push_str("    EndWindow* win = (EndWindow*)malloc(sizeof(EndWindow));\n");
    out.push_str("    win->width = width;\n");
    out.push_str("    win->height = height;\n");
    out.push_str("    win->is_open = true;\n");
    out.push_str("    HINSTANCE hInstance = GetModuleHandle(NULL);\n");
    out.push_str("    WNDCLASSEXA wc = {0};\n");
    out.push_str("    wc.cbSize = sizeof(WNDCLASSEXA);\n");
    out.push_str("    wc.lpfnWndProc = EndWndProc;\n");
    out.push_str("    wc.hInstance = hInstance;\n");
    out.push_str("    wc.hCursor = LoadCursor(NULL, IDC_ARROW);\n");
    out.push_str("    wc.lpszClassName = \"EndNativeWindow\";\n");
    out.push_str("    RegisterClassExA(&wc);\n");
    out.push_str("    win->bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);\n");
    out.push_str("    win->bmi.bmiHeader.biWidth = width;\n");
    out.push_str("    win->bmi.bmiHeader.biHeight = -height;\n");
    out.push_str("    win->bmi.bmiHeader.biPlanes = 1;\n");
    out.push_str("    win->bmi.bmiHeader.biBitCount = 32;\n");
    out.push_str("    win->bmi.bmiHeader.biCompression = BI_RGB;\n");
    out.push_str("    win->hwnd = CreateWindowExA(0, \"EndNativeWindow\", title, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, width + 16, height + 39, NULL, NULL, hInstance, NULL);\n");
    out.push_str("    win->hdc = GetDC(win->hwnd);\n");
    out.push_str("    ShowWindow(win->hwnd, SW_SHOW);\n");
    out.push_str("    UpdateWindow(win->hwnd);\n");
    out.push_str("    return win;\n");
    out.push_str("}\n");
    out.push_str("static inline bool window_poll(EndWindow* win) {\n");
    out.push_str("    if (!win) return false;\n");
    out.push_str("    MSG msg;\n");
    out.push_str("    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {\n");
    out.push_str("        if (msg.message == WM_QUIT) { win->is_open = false; return false; }\n");
    out.push_str("        TranslateMessage(&msg);\n");
    out.push_str("        DispatchMessageA(&msg);\n");
    out.push_str("    }\n");
    out.push_str("    return win->is_open;\n");
    out.push_str("}\n");
    out.push_str("static inline void window_present(EndWindow* win, uint32_t* pixels) {\n");
    out.push_str("    if (!win || !win->is_open || !pixels) return;\n");
    out.push_str("    StretchDIBits(win->hdc, 0, 0, win->width, win->height, 0, 0, win->width, win->height, pixels, &win->bmi, DIB_RGB_COLORS, SRCCOPY);\n");
    out.push_str("}\n");
    out.push_str("static inline void window_sleep(int32_t ms) {\n");
    out.push_str("    Sleep(ms);\n");
    out.push_str("}\n");
    out.push_str("#else\n");
    out.push_str("typedef struct EndWindow { int32_t width; int32_t height; bool is_open; } EndWindow;\n");
    out.push_str("static inline EndWindow* window_create(const char* title, int32_t width, int32_t height) { EndWindow* w = (EndWindow*)malloc(sizeof(EndWindow)); w->width = width; w->height = height; w->is_open = true; return w; }\n");
    out.push_str("static inline bool window_poll(EndWindow* win) { return false; }\n");
    out.push_str("static inline void window_present(EndWindow* win, uint32_t* pixels) {}\n");
    out.push_str("static inline void window_sleep(int32_t ms) {}\n");
    out.push_str("#endif\n\n");

    // Hybrid 3-Tier Memory Model & Region Promotion
    out.push_str("/* Hybrid 3-Tier Memory Model Runtime */\n");
    out.push_str("typedef struct EndRcHeader { int32_t ref_count; uint8_t data[]; } EndRcHeader;\n");
    out.push_str("static inline void* end_rc_new(size_t size, const void* src) {\n");
    out.push_str("    EndRcHeader* h = (EndRcHeader*)malloc(sizeof(EndRcHeader) + size);\n");
    out.push_str("    h->ref_count = 1;\n");
    out.push_str("    if (src) memcpy(h->data, src, size);\n");
    out.push_str("    return (void*)h->data;\n");
    out.push_str("}\n");
    out.push_str("static inline void* end_rc_clone(void* ptr) {\n");
    out.push_str("    if (!ptr) return NULL;\n");
    out.push_str("    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));\n");
    out.push_str("    h->ref_count++;\n");
    out.push_str("    return ptr;\n");
    out.push_str("}\n");
    out.push_str("static inline void end_rc_drop(void* ptr) {\n");
    out.push_str("    if (!ptr) return;\n");
    out.push_str("    EndRcHeader* h = (EndRcHeader*)((uint8_t*)ptr - sizeof(EndRcHeader));\n");
    out.push_str("    h->ref_count--;\n");
    out.push_str("    if (h->ref_count <= 0) free(h);\n");
    out.push_str("}\n");
    out.push_str("static inline void* end_promote(void* ptr, EndArena* target_arena, size_t size) {\n");
    out.push_str("    if (!ptr || !target_arena) return ptr;\n");
    out.push_str("    void* new_ptr = end_arena_alloc(target_arena, size);\n");
    out.push_str("    if (new_ptr) memcpy(new_ptr, ptr, size);\n");
    out.push_str("    return new_ptr ? new_ptr : ptr;\n");
    out.push_str("}\n\n");

    // Concurrency & Channel Primitives
    out.push_str("/* End Lightweight Concurrency & Channel Runtime */\n");
    out.push_str("typedef struct EndChannel { void** buffer; int32_t capacity; int32_t count; int32_t head; int32_t tail; } EndChannel;\n");
    out.push_str("static inline EndChannel* channel_create(int32_t cap) {\n");
    out.push_str("    EndChannel* ch = (EndChannel*)malloc(sizeof(EndChannel));\n");
    out.push_str("    ch->buffer = (void**)malloc(sizeof(void*) * cap);\n");
    out.push_str("    ch->capacity = cap; ch->count = 0; ch->head = 0; ch->tail = 0;\n");
    out.push_str("    return ch;\n");
    out.push_str("}\n");
    out.push_str("static inline void channel_send(EndChannel* ch, void* val) {\n");
    out.push_str("    if (ch->count < ch->capacity) {\n");
    out.push_str("        ch->buffer[ch->tail] = val;\n");
    out.push_str("        ch->tail = (ch->tail + 1) % ch->capacity;\n");
    out.push_str("        ch->count++;\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out.push_str("static inline void* channel_recv(EndChannel* ch) {\n");
    out.push_str("    if (ch->count == 0) return NULL;\n");
    out.push_str("    void* val = ch->buffer[ch->head];\n");
    out.push_str("        ch->head = (ch->head + 1) % ch->capacity;\n");
    out.push_str("        ch->count--;\n");
    out.push_str("    return val;\n");
    out.push_str("}\n\n");

    // High-Resolution Hardware Timer Runtime
    out.push_str("/* End High-Resolution Hardware Timer Runtime (std::time) */\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("static inline uint64_t end_time_now_nanos(void) {\n");
    out.push_str("    LARGE_INTEGER freq, counter;\n");
    out.push_str("    QueryPerformanceFrequency(&freq);\n");
    out.push_str("    QueryPerformanceCounter(&counter);\n");
    out.push_str("    return (uint64_t)((counter.QuadPart * 1000000000ULL) / freq.QuadPart);\n");
    out.push_str("}\n");
    out.push_str("static inline uint64_t end_time_now_micros(void) {\n");
    out.push_str("    LARGE_INTEGER freq, counter;\n");
    out.push_str("    QueryPerformanceFrequency(&freq);\n");
    out.push_str("    QueryPerformanceCounter(&counter);\n");
    out.push_str("    return (uint64_t)((counter.QuadPart * 1000000ULL) / freq.QuadPart);\n");
    out.push_str("}\n");
    out.push_str("static inline uint64_t end_time_now_millis(void) {\n");
    out.push_str("    LARGE_INTEGER freq, counter;\n");
    out.push_str("    QueryPerformanceFrequency(&freq);\n");
    out.push_str("    QueryPerformanceCounter(&counter);\n");
    out.push_str("    return (uint64_t)((counter.QuadPart * 1000ULL) / freq.QuadPart);\n");
    out.push_str("}\n");
    out.push_str("#else\n");
    out.push_str("#include <time.h>\n");
    out.push_str("static inline uint64_t end_time_now_nanos(void) {\n");
    out.push_str("    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);\n");
    out.push_str("    return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;\n");
    out.push_str("}\n");
    out.push_str("static inline uint64_t end_time_now_micros(void) { return end_time_now_nanos() / 1000ULL; }\n");
    out.push_str("static inline uint64_t end_time_now_millis(void) { return end_time_now_nanos() / 1000000ULL; }\n");
    out.push_str("#endif\n\n");
}
