pub fn emit_network_sockets_runtime(out: &mut String) {
    // Real Cross-Platform Native Socket Primitives
    out.push_str("/* End Real Native Socket Primitives (Cross-Platform WinSock2 / POSIX) */\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    #include <winsock2.h>\n");
    out.push_str("    #include <ws2tcpip.h>\n");
    out.push_str("    #pragma comment(lib, \"ws2_32.lib\")\n");
    out.push_str("    static inline void _end_socket_init(void) {\n");
    out.push_str("        static bool _inited = false;\n");
    out.push_str("        if (!_inited) { WSADATA wsa; WSAStartup(MAKEWORD(2, 2), &wsa); _inited = true; }\n");
    out.push_str("    }\n");
    out.push_str("    typedef SOCKET EndSocket;\n");
    out.push_str("    #define END_INVALID_SOCKET INVALID_SOCKET\n");
    out.push_str("    #define END_SOCKET_ERROR SOCKET_ERROR\n");
    out.push_str("    static inline void _end_socket_close(EndSocket s) { closesocket(s); }\n");
    out.push_str("#else\n");
    out.push_str("    #include <sys/types.h>\n");
    out.push_str("    #include <sys/socket.h>\n");
    out.push_str("    #include <netinet/in.h>\n");
    out.push_str("    #include <arpa/inet.h>\n");
    out.push_str("    #include <netdb.h>\n");
    out.push_str("    #include <unistd.h>\n");
    out.push_str("    #include <fcntl.h>\n");
    out.push_str("    static inline void _end_socket_init(void) {}\n");
    out.push_str("    typedef int EndSocket;\n");
    out.push_str("    #define END_INVALID_SOCKET (-1)\n");
    out.push_str("    #define END_SOCKET_ERROR (-1)\n");
    out.push_str("    static inline void _end_socket_close(EndSocket s) { close(s); }\n");
    out.push_str("#endif\n\n");

    out.push_str("static inline int64_t end_net_tcp_listen(int32_t port, int32_t backlog) {\n");
    out.push_str("    _end_socket_init();\n");
    out.push_str("    EndSocket s = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);\n");
    out.push_str("    if (s == END_INVALID_SOCKET) return -1;\n");
    out.push_str("    int opt = 1;\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (const char*)&opt, sizeof(opt));\n");
    out.push_str("#else\n");
    out.push_str("    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));\n");
    out.push_str("#endif\n");
    out.push_str("    struct sockaddr_in addr;\n");
    out.push_str("    memset(&addr, 0, sizeof(addr));\n");
    out.push_str("    addr.sin_family = AF_INET;\n");
    out.push_str("    addr.sin_addr.s_addr = INADDR_ANY;\n");
    out.push_str("    addr.sin_port = htons((uint16_t)port);\n");
    out.push_str("    if (bind(s, (struct sockaddr*)&addr, sizeof(addr)) == END_SOCKET_ERROR) { _end_socket_close(s); return -1; }\n");
    out.push_str("    if (listen(s, backlog > 0 ? backlog : 128) == END_SOCKET_ERROR) { _end_socket_close(s); return -1; }\n");
    out.push_str("    return (int64_t)s;\n");
    out.push_str("}\n\n");

    out.push_str("static inline int64_t end_net_tcp_accept(int64_t server_fd) {\n");
    out.push_str("    if (server_fd < 0) return -1;\n");
    out.push_str("    struct sockaddr_in client_addr;\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    int addr_len = sizeof(client_addr);\n");
    out.push_str("#else\n");
    out.push_str("    socklen_t addr_len = sizeof(client_addr);\n");
    out.push_str("#endif\n");
    out.push_str("    EndSocket client = accept((EndSocket)server_fd, (struct sockaddr*)&client_addr, &addr_len);\n");
    out.push_str("    if (client == END_INVALID_SOCKET) return -1;\n");
    out.push_str("    return (int64_t)client;\n");
    out.push_str("}\n\n");

    out.push_str("static inline int64_t end_net_tcp_connect(const char* host, int32_t port) {\n");
    out.push_str("    _end_socket_init();\n");
    out.push_str("    EndSocket s = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);\n");
    out.push_str("    if (s == END_INVALID_SOCKET) return -1;\n");
    out.push_str("    struct sockaddr_in addr;\n");
    out.push_str("    memset(&addr, 0, sizeof(addr));\n");
    out.push_str("    addr.sin_family = AF_INET;\n");
    out.push_str("    addr.sin_port = htons((uint16_t)port);\n");
    out.push_str("    if (inet_pton(AF_INET, host, &addr.sin_addr) <= 0) {\n");
    out.push_str("        struct hostent* he = gethostbyname(host);\n");
    out.push_str("        if (!he) { _end_socket_close(s); return -1; }\n");
    out.push_str("        memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);\n");
    out.push_str("    }\n");
    out.push_str("    if (connect(s, (struct sockaddr*)&addr, sizeof(addr)) == END_SOCKET_ERROR) { _end_socket_close(s); return -1; }\n");
    out.push_str("    return (int64_t)s;\n");
    out.push_str("}\n\n");

    out.push_str("static inline int64_t end_net_tcp_send(int64_t fd, const char* data, int64_t len) {\n");
    out.push_str("    if (fd < 0 || !data) return -1;\n");
    out.push_str("    int64_t to_send = len >= 0 ? len : (int64_t)strlen(data);\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    int sent = send((EndSocket)fd, data, (int)to_send, 0);\n");
    out.push_str("#else\n");
    out.push_str("    ssize_t sent = send((EndSocket)fd, data, (size_t)to_send, 0);\n");
    out.push_str("#endif\n");
    out.push_str("    return (int64_t)sent;\n");
    out.push_str("}\n\n");

    out.push_str("static inline char* end_net_tcp_recv(int64_t fd, int32_t max_bytes) {\n");
    out.push_str("    if (fd < 0 || max_bytes <= 0) return (char*)\"\";\n");
    out.push_str("    char* buf = (char*)malloc(max_bytes + 1);\n");
    out.push_str("    if (!buf) return (char*)\"\";\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    int n = recv((EndSocket)fd, buf, max_bytes, 0);\n");
    out.push_str("#else\n");
    out.push_str("    ssize_t n = recv((EndSocket)fd, buf, (size_t)max_bytes, 0);\n");
    out.push_str("#endif\n");
    out.push_str("    if (n <= 0) { free(buf); return (char*)\"\"; }\n");
    out.push_str("    buf[n] = '\\0';\n");
    out.push_str("    return buf;\n");
    out.push_str("}\n\n");

    out.push_str("static inline void end_net_tcp_close(int64_t fd) {\n");
    out.push_str("    if (fd >= 0) _end_socket_close((EndSocket)fd);\n");
    out.push_str("}\n\n");

    out.push_str("static inline int64_t end_net_set_nonblocking(int64_t fd, int nonblocking) {\n");
    out.push_str("    if (fd < 0) return 0;\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    u_long mode = nonblocking ? 1 : 0;\n");
    out.push_str("    return ioctlsocket((EndSocket)fd, FIONBIO, &mode) == 0 ? 1 : 0;\n");
    out.push_str("#else\n");
    out.push_str("    int flags = fcntl((int)fd, F_GETFL, 0);\n");
    out.push_str("    if (flags == -1) return 0;\n");
    out.push_str("    flags = nonblocking ? (flags | O_NONBLOCK) : (flags & ~O_NONBLOCK);\n");
    out.push_str("    return fcntl((int)fd, F_SETFL, flags) == 0 ? 1 : 0;\n");
    out.push_str("#endif\n");
    out.push_str("}\n\n");

    out.push_str("typedef struct EndEventLoop {\n");
    out.push_str("    EndSocket fds[256]; int count; int ready_count; EndSocket ready_fds[256];\n");
    out.push_str("} EndEventLoop;\n");
    out.push_str("static inline int64_t end_event_loop_create(void) { return (int64_t)(uintptr_t)calloc(1, sizeof(EndEventLoop)); }\n");
    out.push_str("static inline void end_event_loop_add(int64_t loop_handle, int64_t fd) {\n");
    out.push_str("    EndEventLoop* loop = (EndEventLoop*)(uintptr_t)loop_handle;\n");
    out.push_str("    if (!loop || fd < 0 || loop->count >= 256) return;\n");
    out.push_str("    for (int i = 0; i < loop->count; i++) { if (loop->fds[i] == (EndSocket)fd) return; }\n");
    out.push_str("    loop->fds[loop->count++] = (EndSocket)fd;\n");
    out.push_str("}\n");
    out.push_str("static inline int64_t end_event_loop_poll(int64_t loop_handle, int32_t timeout_ms) {\n");
    out.push_str("    EndEventLoop* loop = (EndEventLoop*)(uintptr_t)loop_handle;\n");
    out.push_str("    if (!loop || loop->count == 0) return 0;\n");
    out.push_str("    loop->ready_count = 0;\n");
    out.push_str("    fd_set read_fds; FD_ZERO(&read_fds); EndSocket max_fd = 0;\n");
    out.push_str("    for (int i = 0; i < loop->count; i++) {\n");
    out.push_str("        FD_SET(loop->fds[i], &read_fds);\n");
    out.push_str("        if (loop->fds[i] > max_fd) max_fd = loop->fds[i];\n");
    out.push_str("    }\n");
    out.push_str("    struct timeval tv;\n");
    out.push_str("    tv.tv_sec = timeout_ms / 1000;\n");
    out.push_str("    tv.tv_usec = (timeout_ms % 1000) * 1000;\n");
    out.push_str("    int res = select((int)max_fd + 1, &read_fds, NULL, NULL, timeout_ms >= 0 ? &tv : NULL);\n");
    out.push_str("    if (res > 0) {\n");
    out.push_str("        for (int i = 0; i < loop->count; i++) {\n");
    out.push_str("            if (FD_ISSET(loop->fds[i], &read_fds)) loop->ready_fds[loop->ready_count++] = loop->fds[i];\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return (int64_t)loop->ready_count;\n");
    out.push_str("}\n");
    out.push_str("static inline int64_t end_event_loop_get_ready(int64_t loop_handle, int32_t index) {\n");
    out.push_str("    EndEventLoop* loop = (EndEventLoop*)(uintptr_t)loop_handle;\n");
    out.push_str("    if (!loop || index < 0 || index >= loop->ready_count) return -1;\n");
    out.push_str("    return (int64_t)loop->ready_fds[index];\n");
    out.push_str("}\n");
    out.push_str("static inline void end_event_loop_destroy(int64_t loop_handle) { EndEventLoop* loop = (EndEventLoop*)(uintptr_t)loop_handle; if (loop) free(loop); }\n\n");
}
