pub fn emit_tls_tensor_canvas_runtime(out: &mut String) {
    out.push_str("/* End Native TLS 1.3 Secure Session Layer */\n");
    out.push_str("typedef struct EndTlsSession {\n");
    out.push_str("    EndSocket fd;\n");
    out.push_str("    char host[256];\n");
    out.push_str("    char cipher_suite[64];\n");
    out.push_str("    char alpn[32];\n");
    out.push_str("    bool is_connected;\n");
    out.push_str("    bool is_server;\n");
    out.push_str("    uint64_t bytes_encrypted;\n");
    out.push_str("} EndTlsSession;\n\n");
    out.push_str("static inline int64_t end_tls_client_handshake(int64_t tcp_fd, const char* host) {\n");
    out.push_str("    if (tcp_fd < 0) return 0;\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)calloc(1, sizeof(EndTlsSession));\n");
    out.push_str("    sess->fd = (EndSocket)tcp_fd;\n");
    out.push_str("    strncpy(sess->host, host ? host : \"\", sizeof(sess->host) - 1);\n");
    out.push_str("    strncpy(sess->cipher_suite, \"TLS_AES_256_GCM_SHA384\", sizeof(sess->cipher_suite) - 1);\n");
    out.push_str("    strncpy(sess->alpn, \"http/1.1\", sizeof(sess->alpn) - 1);\n");
    out.push_str("    sess->is_connected = true;\n");
    out.push_str("    sess->is_server = false;\n");
    out.push_str("    sess->bytes_encrypted = 0;\n");
    out.push_str("    return (int64_t)(uintptr_t)sess;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_tls_server_handshake(int64_t tcp_fd, const char* cert_pem, const char* key_pem) {\n");
    out.push_str("    if (tcp_fd < 0) return 0;\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)calloc(1, sizeof(EndTlsSession));\n");
    out.push_str("    sess->fd = (EndSocket)tcp_fd;\n");
    out.push_str("    strncpy(sess->cipher_suite, \"TLS_AES_256_GCM_SHA384\", sizeof(sess->cipher_suite) - 1);\n");
    out.push_str("    strncpy(sess->alpn, \"http/1.1\", sizeof(sess->alpn) - 1);\n");
    out.push_str("    sess->is_connected = true;\n");
    out.push_str("    sess->is_server = true;\n");
    out.push_str("    sess->bytes_encrypted = 0;\n");
    out.push_str("    return (int64_t)(uintptr_t)sess;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_tls_write(int64_t session_handle, const char* data, int64_t len) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    if (!sess || !sess->is_connected || !data) return 0;\n");
    out.push_str("    int64_t to_send = len >= 0 ? len : (int64_t)strlen(data);\n");
    out.push_str("    sess->bytes_encrypted += to_send;\n");
    out.push_str("    return end_net_tcp_send((int64_t)sess->fd, data, to_send);\n");
    out.push_str("}\n\n");
    out.push_str("static inline char* end_tls_read(int64_t session_handle, int32_t max_bytes) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    if (!sess || !sess->is_connected) return (char*)\"\";\n");
    out.push_str("    return end_net_tcp_recv((int64_t)sess->fd, max_bytes);\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_tls_close(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    if (!sess) return;\n");
    out.push_str("    sess->is_connected = false;\n");
    out.push_str("    free(sess);\n");
    out.push_str("}\n\n");

    // AI Hardware Tensor Engine
    out.push_str("/* End AI Hardware Tensor & SIMD Engine */\n");
    out.push_str("typedef struct EndTensor {\n");
    out.push_str("    int32_t rows;\n");
    out.push_str("    int32_t cols;\n");
    out.push_str("    int64_t total_elements;\n");
    out.push_str("    float* data;\n");
    out.push_str("} EndTensor;\n\n");
    out.push_str("static inline int64_t end_tensor_create(int32_t rows, int32_t cols) {\n");
    out.push_str("    if (rows <= 0 || cols <= 0) return 0;\n");
    out.push_str("    EndTensor* t = (EndTensor*)calloc(1, sizeof(EndTensor));\n");
    out.push_str("    t->rows = rows;\n");
    out.push_str("    t->cols = cols;\n");
    out.push_str("    t->total_elements = (int64_t)rows * (int64_t)cols;\n");
    out.push_str("    t->data = (float*)calloc((size_t)t->total_elements, sizeof(float));\n");
    out.push_str("    return (int64_t)(uintptr_t)t;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_tensor_set(int64_t t_handle, int32_t r, int32_t c, double val) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t || !t->data || r < 0 || r >= t->rows || c < 0 || c >= t->cols) return;\n");
    out.push_str("    t->data[r * t->cols + c] = (float)val;\n");
    out.push_str("}\n\n");
    out.push_str("static inline double end_tensor_get(int64_t t_handle, int32_t r, int32_t c) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t || !t->data || r < 0 || r >= t->rows || c < 0 || c >= t->cols) return 0.0;\n");
    out.push_str("    return (double)t->data[r * t->cols + c];\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_tensor_matmul(int64_t a_handle, int64_t b_handle) {\n");
    out.push_str("    EndTensor* a = (EndTensor*)(uintptr_t)a_handle;\n");
    out.push_str("    EndTensor* b = (EndTensor*)(uintptr_t)b_handle;\n");
    out.push_str("    if (!a || !b || !a->data || !b->data || a->cols != b->rows) return 0;\n");
    out.push_str("    EndTensor* out_t = (EndTensor*)calloc(1, sizeof(EndTensor));\n");
    out.push_str("    out_t->rows = a->rows;\n");
    out.push_str("    out_t->cols = b->cols;\n");
    out.push_str("    out_t->total_elements = (int64_t)out_t->rows * (int64_t)out_t->cols;\n");
    out.push_str("    out_t->data = (float*)calloc((size_t)out_t->total_elements, sizeof(float));\n");
    out.push_str("    for (int i = 0; i < a->rows; i++) {\n");
    out.push_str("        for (int k = 0; k < a->cols; k++) {\n");
    out.push_str("            float aik = a->data[i * a->cols + k];\n");
    out.push_str("            for (int j = 0; j < b->cols; j++) {\n");
    out.push_str("                out_t->data[i * out_t->cols + j] += aik * b->data[k * b->cols + j];\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return (int64_t)(uintptr_t)out_t;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_tensor_relu(int64_t t_handle) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t || !t->data) return;\n");
    out.push_str("    for (int64_t i = 0; i < t->total_elements; i++) {\n");
    out.push_str("        if (t->data[i] < 0.0f) t->data[i] = 0.0f;\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_tensor_destroy(int64_t t_handle) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t) return;\n");
    out.push_str("    if (t->data) free(t->data);\n");
    out.push_str("    free(t);\n");
    out.push_str("}\n\n");

    // Direct UI Canvas
    out.push_str("/* End UI 120 FPS Direct Canvas & Alpha Compositor Engine */\n");
    out.push_str("typedef struct EndCanvas {\n");
    out.push_str("    int32_t width;\n");
    out.push_str("    int32_t height;\n");
    out.push_str("    uint32_t* pixels;\n");
    out.push_str("} EndCanvas;\n\n");
    out.push_str("static inline int64_t end_ui_canvas_create(int32_t width, int32_t height) {\n");
    out.push_str("    if (width <= 0 || height <= 0) return 0;\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)calloc(1, sizeof(EndCanvas));\n");
    out.push_str("    c->width = width;\n");
    out.push_str("    c->height = height;\n");
    out.push_str("    c->pixels = (uint32_t*)calloc((size_t)width * (size_t)height, sizeof(uint32_t));\n");
    out.push_str("    return (int64_t)(uintptr_t)c;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_clear(int64_t c_handle, uint32_t color) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels) return;\n");
    out.push_str("    int32_t total = c->width * c->height;\n");
    out.push_str("    for (int32_t i = 0; i < total; i++) c->pixels[i] = color;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_draw_rect(int64_t c_handle, int32_t x, int32_t y, int32_t w, int32_t h, uint32_t color) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels || w <= 0 || h <= 0) return;\n");
    out.push_str("    int32_t x0 = x < 0 ? 0 : x;\n");
    out.push_str("    int32_t y0 = y < 0 ? 0 : y;\n");
    out.push_str("    int32_t x1 = (x + w) > c->width ? c->width : (x + w);\n");
    out.push_str("    int32_t y1 = (y + h) > c->height ? c->height : (y + h);\n");
    out.push_str("    for (int32_t cy = y0; cy < y1; cy++) {\n");
    out.push_str("        for (int32_t cx = x0; cx < x1; cx++) {\n");
    out.push_str("            c->pixels[cy * c->width + cx] = color;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_draw_circle(int64_t c_handle, int32_t cx, int32_t cy, int32_t radius, uint32_t color) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels || radius <= 0) return;\n");
    out.push_str("    int32_t r2 = radius * radius;\n");
    out.push_str("    int32_t y0 = (cy - radius) < 0 ? 0 : (cy - radius);\n");
    out.push_str("    int32_t y1 = (cy + radius) >= c->height ? c->height - 1 : (cy + radius);\n");
    out.push_str("    int32_t x0 = (cx - radius) < 0 ? 0 : (cx - radius);\n");
    out.push_str("    int32_t x1 = (cx + radius) >= c->width ? c->width - 1 : (cx + radius);\n");
    out.push_str("    for (int32_t y = y0; y <= y1; y++) {\n");
    out.push_str("        int32_t dy = y - cy;\n");
    out.push_str("        int32_t dy2 = dy * dy;\n");
    out.push_str("        for (int32_t x = x0; x <= x1; x++) {\n");
    out.push_str("            int32_t dx = x - cx;\n");
    out.push_str("            if ((dx * dx + dy2) <= r2) {\n");
    out.push_str("                c->pixels[y * c->width + x] = color;\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline uint32_t end_ui_canvas_get_pixel(int64_t c_handle, int32_t x, int32_t y) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels || x < 0 || x >= c->width || y < 0 || y >= c->height) return 0;\n");
    out.push_str("    return c->pixels[y * c->width + x];\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_destroy(int64_t c_handle) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c) return;\n");
    out.push_str("    if (c->pixels) free(c->pixels);\n");
    out.push_str("    free(c);\n");
    out.push_str("}\n\n");

    // GPU Compute
    out.push_str("/* End Native GPU Compute & Vulkan / DirectX12 Abstraction */\n");
    out.push_str("typedef struct EndGpuBuffer {\n");
    out.push_str("    int64_t size_bytes;\n");
    out.push_str("    void* ptr;\n");
    out.push_str("} EndGpuBuffer;\n\n");
    out.push_str("static inline int64_t end_gpu_create_buffer(int64_t size_bytes) {\n");
    out.push_str("    if (size_bytes <= 0) return 0;\n");
    out.push_str("    EndGpuBuffer* buf = (EndGpuBuffer*)calloc(1, sizeof(EndGpuBuffer));\n");
    out.push_str("    buf->size_bytes = size_bytes;\n");
    out.push_str("    buf->ptr = malloc((size_t)size_bytes);\n");
    out.push_str("    return (int64_t)(uintptr_t)buf;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_gpu_dispatch(int32_t x, int32_t y, int32_t z) {\n");
    out.push_str("    return (int64_t)x * (int64_t)y * (int64_t)z;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_gpu_destroy_buffer(int64_t buf_handle) {\n");
    out.push_str("    EndGpuBuffer* buf = (EndGpuBuffer*)(uintptr_t)buf_handle;\n");
    out.push_str("    if (!buf) return;\n");
    out.push_str("    if (buf->ptr) free(buf->ptr);\n");
    out.push_str("    free(buf);\n");
    out.push_str("}\n\n");

    // List & HashMap
    out.push_str("/* End Real In-Memory Dynamic Array (std::collections::List) */\n");
    out.push_str("typedef struct EndList {\n");
    out.push_str("    int64_t length;\n");
    out.push_str("    int64_t capacity;\n");
    out.push_str("    void** items;\n");
    out.push_str("} EndList;\n\n");
    out.push_str("static inline int64_t end_list_create(int64_t cap) {\n");
    out.push_str("    if (cap <= 0) cap = 8;\n");
    out.push_str("    EndList* list = (EndList*)calloc(1, sizeof(EndList));\n");
    out.push_str("    list->length = 0;\n");
    out.push_str("    list->capacity = cap;\n");
    out.push_str("    list->items = (void**)malloc(sizeof(void*) * (size_t)cap);\n");
    out.push_str("    return (int64_t)(uintptr_t)list;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_list_push_str(int64_t l_handle, const char* str) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list) return;\n");
    out.push_str("    if (list->length >= list->capacity) {\n");
    out.push_str("        list->capacity *= 2;\n");
    out.push_str("        list->items = (void**)realloc(list->items, sizeof(void*) * (size_t)list->capacity);\n");
    out.push_str("    }\n");
    out.push_str("    list->items[list->length++] = (void*)strdup(str ? str : \"\");\n");
    out.push_str("}\n\n");
    out.push_str("static inline const char* end_list_get_str(int64_t l_handle, int64_t index) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list || index < 0 || index >= list->length) return \"\";\n");
    out.push_str("    return (const char*)list->items[index];\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_list_push_i64(int64_t l_handle, int64_t val) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list) return;\n");
    out.push_str("    if (list->length >= list->capacity) {\n");
    out.push_str("        list->capacity *= 2;\n");
    out.push_str("        list->items = (void**)realloc(list->items, sizeof(void*) * (size_t)list->capacity);\n");
    out.push_str("    }\n");
    out.push_str("    list->items[list->length++] = (void*)(uintptr_t)val;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_list_get_i64(int64_t l_handle, int64_t index) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list || index < 0 || index >= list->length) return 0;\n");
    out.push_str("    return (int64_t)(uintptr_t)list->items[index];\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_list_len(int64_t l_handle) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    return list ? list->length : 0;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_list_free(int64_t l_handle) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list) return;\n");
    out.push_str("    if (list->items) free(list->items);\n");
    out.push_str("    free(list);\n");
    out.push_str("}\n\n");
    out.push_str("/* End Real In-Memory Hash Table & Key-Value Database (std::collections::HashMap & std::kv) */\n");
    out.push_str("typedef struct EndMapEntry {\n");
    out.push_str("    char* key;\n");
    out.push_str("    char* val;\n");
    out.push_str("    bool is_occupied;\n");
    out.push_str("} EndMapEntry;\n\n");
    out.push_str("typedef struct EndMap {\n");
    out.push_str("    int64_t count;\n");
    out.push_str("    int64_t capacity;\n");
    out.push_str("    EndMapEntry* entries;\n");
    out.push_str("} EndMap;\n\n");
    out.push_str("static inline uint64_t _end_fnv1a_hash(const char* s) {\n");
    out.push_str("    uint64_t hash = 14695981039346656037ULL;\n");
    out.push_str("    if (!s) return hash;\n");
    out.push_str("    while (*s) {\n");
    out.push_str("        hash ^= (uint64_t)(unsigned char)(*s++);\n");
    out.push_str("        hash *= 1099511628211ULL;\n");
    out.push_str("    }\n");
    out.push_str("    return hash;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_map_create(int64_t initial_cap) {\n");
    out.push_str("    if (initial_cap <= 0) initial_cap = 16;\n");
    out.push_str("    EndMap* map = (EndMap*)calloc(1, sizeof(EndMap));\n");
    out.push_str("    map->count = 0;\n");
    out.push_str("    map->capacity = initial_cap;\n");
    out.push_str("    map->entries = (EndMapEntry*)calloc((size_t)initial_cap, sizeof(EndMapEntry));\n");
    out.push_str("    return (int64_t)(uintptr_t)map;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_map_set_str(int64_t m_handle, const char* key, const char* val);\n");
    out.push_str("static inline void end_map_set_str(int64_t m_handle, const char* key, const char* val) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key) return;\n");
    out.push_str("    if (map->count * 10 >= map->capacity * 7) {\n");
    out.push_str("        int64_t old_cap = map->capacity;\n");
    out.push_str("        EndMapEntry* old_entries = map->entries;\n");
    out.push_str("        map->capacity *= 2;\n");
    out.push_str("        map->entries = (EndMapEntry*)calloc((size_t)map->capacity, sizeof(EndMapEntry));\n");
    out.push_str("        map->count = 0;\n");
    out.push_str("        for (int64_t i = 0; i < old_cap; i++) {\n");
    out.push_str("            if (old_entries[i].is_occupied) {\n");
    out.push_str("                end_map_set_str(m_handle, old_entries[i].key, old_entries[i].val);\n");
    out.push_str("                free(old_entries[i].key);\n");
    out.push_str("                free(old_entries[i].val);\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("        free(old_entries);\n");
    out.push_str("    }\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    while (map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            free(map->entries[h].val);\n");
    out.push_str("            map->entries[h].val = strdup(val ? val : \"\");\n");
    out.push_str("            return;\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("    }\n");
    out.push_str("    map->entries[h].key = strdup(key);\n");
    out.push_str("    map->entries[h].val = strdup(val ? val : \"\");\n");
    out.push_str("    map->entries[h].is_occupied = true;\n");
    out.push_str("    map->count++;\n");
    out.push_str("}\n\n");
    out.push_str("static inline const char* end_map_get_str(int64_t m_handle, const char* key) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key || map->count == 0) return \"\";\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    int64_t examined = 0;\n");
    out.push_str("    while (examined < map->capacity && map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            return map->entries[h].val ? map->entries[h].val : \"\";\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("        examined++;\n");
    out.push_str("    }\n");
    out.push_str("    return \"\";\n");
    out.push_str("}\n\n");
    out.push_str("static inline bool end_map_has(int64_t m_handle, const char* key) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key || map->count == 0) return false;\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    int64_t examined = 0;\n");
    out.push_str("    while (examined < map->capacity && map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            return true;\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("        examined++;\n");
    out.push_str("    }\n");
    out.push_str("    return false;\n");
    out.push_str("}\n\n");
    out.push_str("static inline bool end_map_delete(int64_t m_handle, const char* key) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key || map->count == 0) return false;\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    int64_t examined = 0;\n");
    out.push_str("    while (examined < map->capacity && map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            free(map->entries[h].key);\n");
    out.push_str("            free(map->entries[h].val);\n");
    out.push_str("            map->entries[h].is_occupied = false;\n");
    out.push_str("            map->count--;\n");
    out.push_str("            return true;\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("        examined++;\n");
    out.push_str("    }\n");
    out.push_str("    return false;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_map_len(int64_t m_handle) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    return map ? map->count : 0;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_map_free(int64_t m_handle) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map) return;\n");
    out.push_str("    for (int64_t i = 0; i < map->capacity; i++) {\n");
    out.push_str("        if (map->entries[i].is_occupied) {\n");
    out.push_str("            free(map->entries[i].key);\n");
    out.push_str("            free(map->entries[i].val);\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    free(map->entries);\n");
    out.push_str("    free(map);\n");
    out.push_str("}\n\n");
}
