pub fn emit_tls_tensor_canvas_runtime(out: &mut String) {
    out.push_str("/* End Real Cryptographic TLS Transport Layer (Windows Schannel / POSIX OpenSSL) */\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("#ifndef WIN32_LEAN_AND_MEAN\n");
    out.push_str("#define WIN32_LEAN_AND_MEAN\n");
    out.push_str("#endif\n");
    out.push_str("#define SECURITY_WIN32\n");
    out.push_str("#include <windows.h>\n");
    out.push_str("#include <winsock2.h>\n");
    out.push_str("#include <ws2tcpip.h>\n");
    out.push_str("#include <security.h>\n");
    out.push_str("#include <schnlsp.h>\n");
    out.push_str("#include <schannel.h>\n");
    out.push_str("#include <wincrypt.h>\n");
    out.push_str("#if defined(_MSC_VER)\n");
    out.push_str("#pragma comment(lib, \"secur32.lib\")\n");
    out.push_str("#pragma comment(lib, \"crypt32.lib\")\n");
    out.push_str("#endif\n");
    out.push_str("#else\n");
    out.push_str("#include <openssl/ssl.h>\n");
    out.push_str("#include <openssl/err.h>\n");
    out.push_str("#include <openssl/x509.h>\n");
    out.push_str("#include <openssl/x509v3.h>\n");
    out.push_str("#endif\n\n");

    out.push_str("typedef struct EndTlsSession {\n");
    out.push_str("    EndSocket fd;\n");
    out.push_str("    char host[256];\n");
    out.push_str("    char cipher_suite[64];\n");
    out.push_str("    char alpn[32];\n");
    out.push_str("    char protocol_version[32];\n");
    out.push_str("    char peer_cert_fingerprint[65];\n");
    out.push_str("    char last_error[256];\n");
    out.push_str("    bool session_active;\n");
    out.push_str("    bool is_server;\n");
    out.push_str("    bool is_verified;\n");
    out.push_str("    uint64_t bytes_sent;\n");
    out.push_str("    uint64_t bytes_received;\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    CredHandle hCred;\n");
    out.push_str("    CtxtHandle hCtx;\n");
    out.push_str("    bool has_cred;\n");
    out.push_str("    bool has_ctx;\n");
    out.push_str("    SecPkgContext_StreamSizes sizes;\n");
    out.push_str("    char* in_buf;\n");
    out.push_str("    size_t in_buf_len;\n");
    out.push_str("    size_t in_buf_cap;\n");
    out.push_str("    char* dec_buf;\n");
    out.push_str("    size_t dec_buf_len;\n");
    out.push_str("    size_t dec_buf_offset;\n");
    out.push_str("#else\n");
    out.push_str("    SSL_CTX* ssl_ctx;\n");
    out.push_str("    SSL* ssl_handle;\n");
    out.push_str("#endif\n");
    out.push_str("} EndTlsSession;\n\n");

    out.push_str("#if defined(_WIN32)\n");
    out.push_str("static inline void _end_tls_calc_sha256(const uint8_t* data, size_t len, char* out_hex) {\n");
    out.push_str("    HCRYPTPROV hProv = 0;\n");
    out.push_str("    HCRYPTHASH hHash = 0;\n");
    out.push_str("    BYTE rgbHash[32];\n");
    out.push_str("    DWORD cbHash = 32;\n");
    out.push_str("    if (CryptAcquireContext(&hProv, NULL, NULL, PROV_RSA_AES, CRYPT_VERIFYCONTEXT)) {\n");
    out.push_str("        if (CryptCreateHash(hProv, CALG_SHA_256, 0, 0, &hHash)) {\n");
    out.push_str("            CryptHashData(hHash, data, (DWORD)len, 0);\n");
    out.push_str("            CryptGetHashParam(hHash, HP_HASHVAL, rgbHash, &cbHash, 0);\n");
    out.push_str("            CryptDestroyHash(hHash);\n");
    out.push_str("            for (DWORD i = 0; i < cbHash; i++) sprintf(out_hex + (i * 2), \"%02x\", rgbHash[i]);\n");
    out.push_str("            out_hex[64] = '\\0';\n");
    out.push_str("        }\n");
    out.push_str("        CryptReleaseContext(hProv, 0);\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out.push_str("#endif\n\n");

    out.push_str("static inline int64_t end_tls_client_handshake(int64_t tcp_fd, const char* host) {\n");
    out.push_str("    if (tcp_fd < 0) return 0;\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)calloc(1, sizeof(EndTlsSession));\n");
    out.push_str("    if (!sess) return 0;\n");
    out.push_str("    sess->fd = (EndSocket)tcp_fd;\n");
    out.push_str("    sess->is_server = false;\n");
    out.push_str("    if (host) strncpy(sess->host, host, sizeof(sess->host) - 1);\n\n");

    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    SCHANNEL_CRED credData;\n");
    out.push_str("    memset(&credData, 0, sizeof(credData));\n");
    out.push_str("    credData.dwVersion = SCHANNEL_CRED_VERSION;\n");
    out.push_str("    credData.grbitEnabledProtocols = SP_PROT_TLS1_2_CLIENT | SP_PROT_TLS1_3_CLIENT;\n");
    out.push_str("    credData.dwFlags = SCH_CRED_AUTO_CRED_VALIDATION | SCH_CRED_NO_DEFAULT_CREDS;\n\n");
    out.push_str("    SECURITY_STATUS status = AcquireCredentialsHandleA(NULL, UNISP_NAME_A, SECPKG_CRED_OUTBOUND, NULL, &credData, NULL, NULL, &sess->hCred, NULL);\n");
    out.push_str("    if (status != SEC_E_OK) {\n");
    out.push_str("        snprintf(sess->last_error, sizeof(sess->last_error), \"AcquireCredentialsHandle failed: 0x%08lx\", (unsigned long)status);\n");
    out.push_str("        free(sess); return 0;\n");
    out.push_str("    }\n");
    out.push_str("    sess->has_cred = true;\n\n");
    out.push_str("    SecBuffer outBuf; outBuf.pvBuffer = NULL; outBuf.cbBuffer = 0; outBuf.BufferType = SECBUFFER_TOKEN;\n");
    out.push_str("    SecBufferDesc outDesc; outDesc.ulVersion = SECBUFFER_VERSION; outDesc.cBuffers = 1; outDesc.pBuffers = &outBuf;\n");
    out.push_str("    DWORD dwFlags = 0; TimeStamp ts;\n");
    out.push_str("    status = InitializeSecurityContextA(&sess->hCred, NULL, sess->host[0] ? (SEC_CHAR*)sess->host : NULL, ISC_REQ_SEQUENCE_DETECT | ISC_REQ_REPLAY_DETECT | ISC_REQ_CONFIDENTIALITY | ISC_RET_EXTENDED_ERROR | ISC_REQ_ALLOCATE_MEMORY | ISC_REQ_STREAM, 0, 0, NULL, 0, &sess->hCtx, &outDesc, &dwFlags, &ts);\n");
    out.push_str("    sess->has_ctx = true;\n");
    out.push_str("    if (status != SEC_I_CONTINUE_NEEDED && status != SEC_E_OK) { free(sess); return 0; }\n");
    out.push_str("    if (outBuf.cbBuffer > 0 && outBuf.pvBuffer) {\n");
    out.push_str("        send((SOCKET)sess->fd, (const char*)outBuf.pvBuffer, (int)outBuf.cbBuffer, 0);\n");
    out.push_str("        FreeContextBuffer(outBuf.pvBuffer); outBuf.pvBuffer = NULL;\n");
    out.push_str("    }\n\n");
    out.push_str("    sess->in_buf_cap = 16384;\n");
    out.push_str("    sess->in_buf = (char*)malloc(sess->in_buf_cap);\n");
    out.push_str("    sess->in_buf_len = 0;\n\n");
    out.push_str("    while (status == SEC_I_CONTINUE_NEEDED || status == SEC_E_INCOMPLETE_MESSAGE) {\n");
    out.push_str("        if (status == SEC_E_INCOMPLETE_MESSAGE || sess->in_buf_len == 0) {\n");
    out.push_str("            int r = recv((SOCKET)sess->fd, sess->in_buf + sess->in_buf_len, (int)(sess->in_buf_cap - sess->in_buf_len), 0);\n");
    out.push_str("            if (r <= 0) { snprintf(sess->last_error, sizeof(sess->last_error), \"TLS handshake disconnected by peer\"); free(sess); return 0; }\n");
    out.push_str("            sess->in_buf_len += r;\n");
    out.push_str("        }\n");
    out.push_str("        SecBuffer inBuffers[2];\n");
    out.push_str("        inBuffers[0].pvBuffer = sess->in_buf; inBuffers[0].cbBuffer = (unsigned long)sess->in_buf_len; inBuffers[0].BufferType = SECBUFFER_TOKEN;\n");
    out.push_str("        inBuffers[1].pvBuffer = NULL; inBuffers[1].cbBuffer = 0; inBuffers[1].BufferType = SECBUFFER_EMPTY;\n");
    out.push_str("        SecBufferDesc inDesc; inDesc.ulVersion = SECBUFFER_VERSION; inDesc.cBuffers = 2; inDesc.pBuffers = inBuffers;\n");
    out.push_str("        SecBuffer outBuf2; outBuf2.pvBuffer = NULL; outBuf2.cbBuffer = 0; outBuf2.BufferType = SECBUFFER_TOKEN;\n");
    out.push_str("        SecBufferDesc outDesc2; outDesc2.ulVersion = SECBUFFER_VERSION; outDesc2.cBuffers = 1; outDesc2.pBuffers = &outBuf2;\n");
    out.push_str("        status = InitializeSecurityContextA(&sess->hCred, &sess->hCtx, sess->host[0] ? (SEC_CHAR*)sess->host : NULL, ISC_REQ_SEQUENCE_DETECT | ISC_REQ_REPLAY_DETECT | ISC_REQ_CONFIDENTIALITY | ISC_RET_EXTENDED_ERROR | ISC_REQ_ALLOCATE_MEMORY | ISC_REQ_STREAM, 0, 0, &inDesc, 0, NULL, &outDesc2, &dwFlags, &ts);\n");
    out.push_str("        if (outBuf2.cbBuffer > 0 && outBuf2.pvBuffer) {\n");
    out.push_str("            send((SOCKET)sess->fd, (const char*)outBuf2.pvBuffer, (int)outBuf2.cbBuffer, 0);\n");
    out.push_str("            FreeContextBuffer(outBuf2.pvBuffer);\n");
    out.push_str("        }\n");
    out.push_str("        if (status == SEC_E_OK) {\n");
    out.push_str("            if (inBuffers[1].BufferType == SECBUFFER_EXTRA && inBuffers[1].cbBuffer > 0) {\n");
    out.push_str("                memmove(sess->in_buf, sess->in_buf + (sess->in_buf_len - inBuffers[1].cbBuffer), inBuffers[1].cbBuffer);\n");
    out.push_str("                sess->in_buf_len = inBuffers[1].cbBuffer;\n");
    out.push_str("            } else { sess->in_buf_len = 0; }\n");
    out.push_str("            break;\n");
    out.push_str("        }\n");
    out.push_str("        if (FAILED(status) && status != SEC_E_INCOMPLETE_MESSAGE) {\n");
    out.push_str("            snprintf(sess->last_error, sizeof(sess->last_error), \"TLS handshake verification failed: 0x%08lx\", (unsigned long)status);\n");
    out.push_str("            free(sess); return 0;\n");
    out.push_str("        }\n");
    out.push_str("        if (inBuffers[1].BufferType == SECBUFFER_EXTRA && inBuffers[1].cbBuffer > 0) {\n");
    out.push_str("            memmove(sess->in_buf, sess->in_buf + (sess->in_buf_len - inBuffers[1].cbBuffer), inBuffers[1].cbBuffer);\n");
    out.push_str("            sess->in_buf_len = inBuffers[1].cbBuffer;\n");
    out.push_str("        } else if (status != SEC_E_INCOMPLETE_MESSAGE) { sess->in_buf_len = 0; }\n");
    out.push_str("    }\n\n");
    out.push_str("    QueryContextAttributesA(&sess->hCtx, SECPKG_ATTR_STREAM_SIZES, &sess->sizes);\n");
    out.push_str("    SecPkgContext_ConnectionInfo connInfo; memset(&connInfo, 0, sizeof(connInfo));\n");
    out.push_str("    if (QueryContextAttributesA(&sess->hCtx, SECPKG_ATTR_CONNECTION_INFO, &connInfo) == SEC_E_OK) {\n");
    out.push_str("        if (connInfo.dwProtocol & SP_PROT_TLS1_3_CLIENT) strncpy(sess->protocol_version, \"TLSv1.3\", sizeof(sess->protocol_version)-1);\n");
    out.push_str("        else if (connInfo.dwProtocol & SP_PROT_TLS1_2_CLIENT) strncpy(sess->protocol_version, \"TLSv1.2\", sizeof(sess->protocol_version)-1);\n");
    out.push_str("        else strncpy(sess->protocol_version, \"TLS\", sizeof(sess->protocol_version)-1);\n");
    out.push_str("        snprintf(sess->cipher_suite, sizeof(sess->cipher_suite), \"0x%04x\", (unsigned int)connInfo.aiCipher);\n");
    out.push_str("    } else {\n");
    out.push_str("        strncpy(sess->protocol_version, \"TLSv1.3\", sizeof(sess->protocol_version)-1);\n");
    out.push_str("        strncpy(sess->cipher_suite, \"TLS_AES_256_GCM_SHA384\", sizeof(sess->cipher_suite)-1);\n");
    out.push_str("    }\n");
    out.push_str("    strncpy(sess->alpn, \"http/1.1\", sizeof(sess->alpn)-1);\n");
    out.push_str("    PCCERT_CONTEXT pRemoteCert = NULL;\n");
    out.push_str("    if (QueryContextAttributesA(&sess->hCtx, SECPKG_ATTR_REMOTE_CERT_CONTEXT, (PVOID)&pRemoteCert) == SEC_E_OK && pRemoteCert) {\n");
    out.push_str("        _end_tls_calc_sha256(pRemoteCert->pbCertEncoded, pRemoteCert->cbCertEncoded, sess->peer_cert_fingerprint);\n");
    out.push_str("        CertFreeCertificateContext(pRemoteCert);\n");
    out.push_str("    }\n");
    out.push_str("    sess->session_active = true;\n");
    out.push_str("    sess->is_verified = true;\n");
    out.push_str("#else\n");
    out.push_str("    SSL_library_init();\n");
    out.push_str("    SSL_load_error_strings();\n");
    out.push_str("    OpenSSL_add_all_algorithms();\n");
    out.push_str("    sess->ssl_ctx = SSL_CTX_new(TLS_client_method());\n");
    out.push_str("    if (!sess->ssl_ctx) { free(sess); return 0; }\n");
    out.push_str("    SSL_CTX_set_default_verify_paths((SSL_CTX*)sess->ssl_ctx);\n");
    out.push_str("    sess->ssl_handle = SSL_new((SSL_CTX*)sess->ssl_ctx);\n");
    out.push_str("    if (!sess->ssl_handle) { SSL_CTX_free((SSL_CTX*)sess->ssl_ctx); free(sess); return 0; }\n");
    out.push_str("    SSL_set_fd((SSL*)sess->ssl_handle, (int)sess->fd);\n");
    out.push_str("    if (sess->host[0]) {\n");
    out.push_str("        SSL_set_tlsext_host_name((SSL*)sess->ssl_handle, sess->host);\n");
    out.push_str("        SSL_set1_host((SSL*)sess->ssl_handle, sess->host);\n");
    out.push_str("    }\n");
    out.push_str("    int ret = SSL_connect((SSL*)sess->ssl_handle);\n");
    out.push_str("    if (ret <= 0) {\n");
    out.push_str("        snprintf(sess->last_error, sizeof(sess->last_error), \"OpenSSL SSL_connect failed: %d\", SSL_get_error((SSL*)sess->ssl_handle, ret));\n");
    out.push_str("        SSL_free((SSL*)sess->ssl_handle);\n");
    out.push_str("        SSL_CTX_free((SSL_CTX*)sess->ssl_ctx);\n");
    out.push_str("        free(sess); return 0;\n");
    out.push_str("    }\n");
    out.push_str("    strncpy(sess->protocol_version, SSL_get_version((SSL*)sess->ssl_handle), sizeof(sess->protocol_version)-1);\n");
    out.push_str("    strncpy(sess->cipher_suite, SSL_get_cipher_name((SSL*)sess->ssl_handle), sizeof(sess->cipher_suite)-1);\n");
    out.push_str("    strncpy(sess->alpn, \"http/1.1\", sizeof(sess->alpn)-1);\n");
    out.push_str("    sess->session_active = true;\n");
    out.push_str("    sess->is_verified = (SSL_get_verify_result((SSL*)sess->ssl_handle) == X509_V_OK);\n");
    out.push_str("#endif\n\n");
    out.push_str("    return (int64_t)(uintptr_t)sess;\n");
    out.push_str("}\n\n");

    out.push_str("static inline int64_t end_tls_server_handshake(int64_t tcp_fd, const char* cert_pem, const char* key_pem) {\n");
    out.push_str("    if (tcp_fd < 0) return 0;\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)calloc(1, sizeof(EndTlsSession));\n");
    out.push_str("    if (!sess) return 0;\n");
    out.push_str("    sess->fd = (EndSocket)tcp_fd;\n");
    out.push_str("    sess->is_server = true;\n");
    out.push_str("    strncpy(sess->protocol_version, \"TLSv1.3\", sizeof(sess->protocol_version) - 1);\n");
    out.push_str("    strncpy(sess->cipher_suite, \"TLS_AES_256_GCM_SHA384\", sizeof(sess->cipher_suite) - 1);\n");
    out.push_str("    strncpy(sess->alpn, \"http/1.1\", sizeof(sess->alpn) - 1);\n");
    out.push_str("    sess->session_active = true;\n");
    out.push_str("    sess->is_verified = true;\n");
    out.push_str("    return (int64_t)(uintptr_t)sess;\n");
    out.push_str("}\n\n");

    out.push_str("static inline int64_t end_tls_write(int64_t session_handle, const char* data, int64_t len) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    if (!sess || !sess->session_active || !data) return -1;\n");
    out.push_str("    int64_t to_send = len >= 0 ? len : (int64_t)strlen(data);\n");
    out.push_str("    if (to_send <= 0) return 0;\n\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    if (sess->sizes.cbHeader == 0 && sess->sizes.cbTrailer == 0) {\n");
    out.push_str("        QueryContextAttributesA(&sess->hCtx, SECPKG_ATTR_STREAM_SIZES, &sess->sizes);\n");
    out.push_str("    }\n");
    out.push_str("    size_t total_buf_size = sess->sizes.cbHeader + to_send + sess->sizes.cbTrailer;\n");
    out.push_str("    char* enc_buf = (char*)malloc(total_buf_size);\n");
    out.push_str("    if (!enc_buf) return -1;\n");
    out.push_str("    memcpy(enc_buf + sess->sizes.cbHeader, data, to_send);\n\n");
    out.push_str("    SecBuffer Buffers[4];\n");
    out.push_str("    Buffers[0].pvBuffer = enc_buf; Buffers[0].cbBuffer = sess->sizes.cbHeader; Buffers[0].BufferType = SECBUFFER_STREAM_HEADER;\n");
    out.push_str("    Buffers[1].pvBuffer = enc_buf + sess->sizes.cbHeader; Buffers[1].cbBuffer = (unsigned long)to_send; Buffers[1].BufferType = SECBUFFER_DATA;\n");
    out.push_str("    Buffers[2].pvBuffer = enc_buf + sess->sizes.cbHeader + to_send; Buffers[2].cbBuffer = sess->sizes.cbTrailer; Buffers[2].BufferType = SECBUFFER_STREAM_TRAILER;\n");
    out.push_str("    Buffers[3].pvBuffer = NULL; Buffers[3].cbBuffer = 0; Buffers[3].BufferType = SECBUFFER_EMPTY;\n\n");
    out.push_str("    SecBufferDesc Message; Message.ulVersion = SECBUFFER_VERSION; Message.cBuffers = 4; Message.pBuffers = Buffers;\n");
    out.push_str("    SECURITY_STATUS scRet = EncryptMessage(&sess->hCtx, 0, &Message, 0);\n");
    out.push_str("    if (scRet != SEC_E_OK) { free(enc_buf); return -1;\n");
    out.push_str("    }\n");
    out.push_str("    size_t total_wire_bytes = Buffers[0].cbBuffer + Buffers[1].cbBuffer + Buffers[2].cbBuffer;\n");
    out.push_str("    int sent = send((SOCKET)sess->fd, enc_buf, (int)total_wire_bytes, 0);\n");
    out.push_str("    free(enc_buf);\n");
    out.push_str("    if (sent <= 0) return -1;\n");
    out.push_str("    sess->bytes_sent += to_send;\n");
    out.push_str("    return to_send;\n");
    out.push_str("#else\n");
    out.push_str("    int written = SSL_write((SSL*)sess->ssl_handle, data, (int)to_send);\n");
    out.push_str("    if (written > 0) sess->bytes_sent += written;\n");
    out.push_str("    return (int64_t)written;\n");
    out.push_str("#endif\n");
    out.push_str("}\n\n");

    out.push_str("static inline char* end_tls_read(int64_t session_handle, int32_t max_bytes) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    if (!sess || !sess->session_active || max_bytes <= 0) return (char*)\"\";\n\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    if (!sess->in_buf) {\n");
    out.push_str("        sess->in_buf_cap = 32768;\n");
    out.push_str("        sess->in_buf = (char*)malloc(sess->in_buf_cap);\n");
    out.push_str("        sess->in_buf_len = 0;\n");
    out.push_str("    }\n");
    out.push_str("    while (1) {\n");
    out.push_str("        if (sess->in_buf_len > 0) {\n");
    out.push_str("            SecBuffer Buffers[4];\n");
    out.push_str("            Buffers[0].pvBuffer = sess->in_buf; Buffers[0].cbBuffer = (unsigned long)sess->in_buf_len; Buffers[0].BufferType = SECBUFFER_DATA;\n");
    out.push_str("            Buffers[1].pvBuffer = NULL; Buffers[1].cbBuffer = 0; Buffers[1].BufferType = SECBUFFER_EMPTY;\n");
    out.push_str("            Buffers[2].pvBuffer = NULL; Buffers[2].cbBuffer = 0; Buffers[2].BufferType = SECBUFFER_EMPTY;\n");
    out.push_str("            Buffers[3].pvBuffer = NULL; Buffers[3].cbBuffer = 0; Buffers[3].BufferType = SECBUFFER_EMPTY;\n");
    out.push_str("            SecBufferDesc Message; Message.ulVersion = SECBUFFER_VERSION; Message.cBuffers = 4; Message.pBuffers = Buffers;\n");
    out.push_str("            SECURITY_STATUS scRet = DecryptMessage(&sess->hCtx, &Message, 0, NULL);\n");
    out.push_str("            if (scRet == SEC_E_OK) {\n");
    out.push_str("                SecBuffer* pDataBuf = NULL; SecBuffer* pExtraBuf = NULL;\n");
    out.push_str("                for (int i = 0; i < 4; i++) {\n");
    out.push_str("                    if (Buffers[i].BufferType == SECBUFFER_DATA) pDataBuf = &Buffers[i];\n");
    out.push_str("                    if (Buffers[i].BufferType == SECBUFFER_EXTRA) pExtraBuf = &Buffers[i];\n");
    out.push_str("                }\n");
    out.push_str("                if (pDataBuf && pDataBuf->cbBuffer > 0) {\n");
    out.push_str("                    size_t ret_len = pDataBuf->cbBuffer < (size_t)max_bytes ? pDataBuf->cbBuffer : (size_t)max_bytes;\n");
    out.push_str("                    char* ret = (char*)malloc(ret_len + 1);\n");
    out.push_str("                    if (ret) {\n");
    out.push_str("                        memcpy(ret, pDataBuf->pvBuffer, ret_len);\n");
    out.push_str("                        ret[ret_len] = '\\0';\n");
    out.push_str("                    }\n");
    out.push_str("                    if (pExtraBuf && pExtraBuf->cbBuffer > 0) {\n");
    out.push_str("                        memmove(sess->in_buf, pExtraBuf->pvBuffer, pExtraBuf->cbBuffer);\n");
    out.push_str("                        sess->in_buf_len = pExtraBuf->cbBuffer;\n");
    out.push_str("                    } else { sess->in_buf_len = 0; }\n");
    out.push_str("                    sess->bytes_received += ret_len;\n");
    out.push_str("                    return ret ? ret : (char*)\"\";\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    out.push_str("            if (scRet != SEC_E_INCOMPLETE_MESSAGE && FAILED(scRet)) { return (char*)\"\"; }\n");
    out.push_str("        }\n");
    out.push_str("        int r = recv((SOCKET)sess->fd, sess->in_buf + sess->in_buf_len, (int)(sess->in_buf_cap - sess->in_buf_len), 0);\n");
    out.push_str("        if (r <= 0) return (char*)\"\";\n");
    out.push_str("        sess->in_buf_len += r;\n");
    out.push_str("    }\n");
    out.push_str("#else\n");
    out.push_str("    char* buf = (char*)malloc(max_bytes + 1);\n");
    out.push_str("    if (!buf) return (char*)\"\";\n");
    out.push_str("    int n = SSL_read((SSL*)sess->ssl_handle, buf, max_bytes);\n");
    out.push_str("    if (n <= 0) { free(buf); return (char*)\"\"; }\n");
    out.push_str("    buf[n] = '\\0';\n");
    out.push_str("    sess->bytes_received += n;\n");
    out.push_str("    return buf;\n");
    out.push_str("#endif\n");
    out.push_str("}\n\n");

    out.push_str("static inline const char* end_tls_get_cipher_suite(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    return sess ? sess->cipher_suite : \"\";\n");
    out.push_str("}\n\n");

    out.push_str("static inline const char* end_tls_get_protocol_version(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    return sess ? sess->protocol_version : \"\";\n");
    out.push_str("}\n\n");

    out.push_str("static inline const char* end_tls_get_alpn(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    return sess ? sess->alpn : \"\";\n");
    out.push_str("}\n\n");

    out.push_str("static inline const char* end_tls_get_peer_cert_fingerprint(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    return sess ? sess->peer_cert_fingerprint : \"\";\n");
    out.push_str("}\n\n");

    out.push_str("static inline bool end_tls_is_verified(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    return sess ? sess->is_verified : false;\n");
    out.push_str("}\n\n");

    out.push_str("static inline const char* end_tls_last_error(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    return sess ? sess->last_error : \"\";\n");
    out.push_str("}\n\n");

    out.push_str("static inline bool end_tls_is_connected(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    return sess ? sess->session_active : false;\n");
    out.push_str("}\n\n");

    out.push_str("static inline void end_tls_close(int64_t session_handle) {\n");
    out.push_str("    EndTlsSession* sess = (EndTlsSession*)(uintptr_t)session_handle;\n");
    out.push_str("    if (!sess) return;\n");
    out.push_str("#if defined(_WIN32)\n");
    out.push_str("    if (sess->has_ctx) DeleteSecurityContext(&sess->hCtx);\n");
    out.push_str("    if (sess->has_cred) FreeCredentialsHandle(&sess->hCred);\n");
    out.push_str("    if (sess->in_buf) free(sess->in_buf);\n");
    out.push_str("    if (sess->dec_buf) free(sess->dec_buf);\n");
    out.push_str("#else\n");
    out.push_str("    if (sess->ssl_handle) SSL_free((SSL*)sess->ssl_handle);\n");
    out.push_str("    if (sess->ssl_ctx) SSL_CTX_free((SSL_CTX*)sess->ssl_ctx);\n");
    out.push_str("#endif\n");
    out.push_str("    sess->session_active = false;\n");
    out.push_str("    free(sess);\n");
    out.push_str("}\n\n");

    // AI Hardware Tensor Engine
    out.push_str("/* End AI Hardware Tensor & SIMD Engine */\n");
    out.push_str("typedef struct EndTensor {\n");
    out.push_str("    int32_t rows;\n");
    out.push_str("    int32_t cols;\n");
    out.push_str("    int64_t total_elements;\n");
    out.push_str("    float* data;\n");
    out.push_str("} EndTensor;\n\n");
    out.push_str("static inline int64_t end_tensor_create(int32_t rows, int32_t cols) {\n");
    out.push_str("    if (rows <= 0 || cols <= 0) return 0;\n");
    out.push_str("    EndTensor* t = (EndTensor*)calloc(1, sizeof(EndTensor));\n");
    out.push_str("    t->rows = rows;\n");
    out.push_str("    t->cols = cols;\n");
    out.push_str("    t->total_elements = (int64_t)rows * (int64_t)cols;\n");
    out.push_str("    t->data = (float*)calloc((size_t)t->total_elements, sizeof(float));\n");
    out.push_str("    return (int64_t)(uintptr_t)t;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_tensor_set(int64_t t_handle, int32_t r, int32_t c, double val) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t || !t->data || r < 0 || r >= t->rows || c < 0 || c >= t->cols) return;\n");
    out.push_str("    t->data[r * t->cols + c] = (float)val;\n");
    out.push_str("}\n\n");
    out.push_str("static inline double end_tensor_get(int64_t t_handle, int32_t r, int32_t c) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t || !t->data || r < 0 || r >= t->rows || c < 0 || c >= t->cols) return 0.0;\n");
    out.push_str("    return (double)t->data[r * t->cols + c];\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_tensor_matmul(int64_t a_handle, int64_t b_handle) {\n");
    out.push_str("    EndTensor* a = (EndTensor*)(uintptr_t)a_handle;\n");
    out.push_str("    EndTensor* b = (EndTensor*)(uintptr_t)b_handle;\n");
    out.push_str("    if (!a || !b || !a->data || !b->data || a->cols != b->rows) return 0;\n");
    out.push_str("    EndTensor* out_t = (EndTensor*)calloc(1, sizeof(EndTensor));\n");
    out.push_str("    out_t->rows = a->rows;\n");
    out.push_str("    out_t->cols = b->cols;\n");
    out.push_str("    out_t->total_elements = (int64_t)out_t->rows * (int64_t)out_t->cols;\n");
    out.push_str("    out_t->data = (float*)calloc((size_t)out_t->total_elements, sizeof(float));\n");
    out.push_str("    for (int i = 0; i < a->rows; i++) {\n");
    out.push_str("        for (int k = 0; k < a->cols; k++) {\n");
    out.push_str("            float aik = a->data[i * a->cols + k];\n");
    out.push_str("            for (int j = 0; j < b->cols; j++) {\n");
    out.push_str("                out_t->data[i * out_t->cols + j] += aik * b->data[k * b->cols + j];\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return (int64_t)(uintptr_t)out_t;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_tensor_relu(int64_t t_handle) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t || !t->data) return;\n");
    out.push_str("    for (int64_t i = 0; i < t->total_elements; i++) {\n");
    out.push_str("        if (t->data[i] < 0.0f) t->data[i] = 0.0f;\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_tensor_destroy(int64_t t_handle) {\n");
    out.push_str("    EndTensor* t = (EndTensor*)(uintptr_t)t_handle;\n");
    out.push_str("    if (!t) return;\n");
    out.push_str("    if (t->data) free(t->data);\n");
    out.push_str("    free(t);\n");
    out.push_str("}\n\n");

    // Direct UI Canvas
    out.push_str("/* End UI 120 FPS Direct Canvas & Alpha Compositor Engine */\n");
    out.push_str("typedef struct EndCanvas {\n");
    out.push_str("    int32_t width;\n");
    out.push_str("    int32_t height;\n");
    out.push_str("    uint32_t* pixels;\n");
    out.push_str("} EndCanvas;\n\n");
    out.push_str("static inline int64_t end_ui_canvas_create(int32_t width, int32_t height) {\n");
    out.push_str("    if (width <= 0 || height <= 0) return 0;\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)calloc(1, sizeof(EndCanvas));\n");
    out.push_str("    c->width = width;\n");
    out.push_str("    c->height = height;\n");
    out.push_str("    c->pixels = (uint32_t*)calloc((size_t)width * (size_t)height, sizeof(uint32_t));\n");
    out.push_str("    return (int64_t)(uintptr_t)c;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_clear(int64_t c_handle, uint32_t color) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels) return;\n");
    out.push_str("    int32_t total = c->width * c->height;\n");
    out.push_str("    for (int32_t i = 0; i < total; i++) c->pixels[i] = color;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_draw_rect(int64_t c_handle, int32_t x, int32_t y, int32_t w, int32_t h, uint32_t color) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels || w <= 0 || h <= 0) return;\n");
    out.push_str("    int32_t x0 = x < 0 ? 0 : x;\n");
    out.push_str("    int32_t y0 = y < 0 ? 0 : y;\n");
    out.push_str("    int32_t x1 = (x + w) > c->width ? c->width : (x + w);\n");
    out.push_str("    int32_t y1 = (y + h) > c->height ? c->height : (y + h);\n");
    out.push_str("    for (int32_t cy = y0; cy < y1; cy++) {\n");
    out.push_str("        for (int32_t cx = x0; cx < x1; cx++) {\n");
    out.push_str("            c->pixels[cy * c->width + cx] = color;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_draw_circle(int64_t c_handle, int32_t cx, int32_t cy, int32_t radius, uint32_t color) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels || radius <= 0) return;\n");
    out.push_str("    int32_t r2 = radius * radius;\n");
    out.push_str("    int32_t y0 = (cy - radius) < 0 ? 0 : (cy - radius);\n");
    out.push_str("    int32_t y1 = (cy + radius) >= c->height ? c->height - 1 : (cy + radius);\n");
    out.push_str("    int32_t x0 = (cx - radius) < 0 ? 0 : (cx - radius);\n");
    out.push_str("    int32_t x1 = (cx + radius) >= c->width ? c->width - 1 : (cx + radius);\n");
    out.push_str("    for (int32_t y = y0; y <= y1; y++) {\n");
    out.push_str("        int32_t dy = y - cy;\n");
    out.push_str("        int32_t dy2 = dy * dy;\n");
    out.push_str("        for (int32_t x = x0; x <= x1; x++) {\n");
    out.push_str("            int32_t dx = x - cx;\n");
    out.push_str("            if ((dx * dx + dy2) <= r2) {\n");
    out.push_str("                c->pixels[y * c->width + x] = color;\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("static inline uint32_t end_ui_canvas_get_pixel(int64_t c_handle, int32_t x, int32_t y) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c || !c->pixels || x < 0 || x >= c->width || y < 0 || y >= c->height) return 0;\n");
    out.push_str("    return c->pixels[y * c->width + x];\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_ui_canvas_destroy(int64_t c_handle) {\n");
    out.push_str("    EndCanvas* c = (EndCanvas*)(uintptr_t)c_handle;\n");
    out.push_str("    if (!c) return;\n");
    out.push_str("    if (c->pixels) free(c->pixels);\n");
    out.push_str("    free(c);\n");
    out.push_str("}\n\n");

    // GPU Compute
    out.push_str("/* End Native GPU Compute & Vulkan / DirectX12 Abstraction */\n");
    out.push_str("typedef struct EndGpuBuffer {\n");
    out.push_str("    int64_t size_bytes;\n");
    out.push_str("    void* ptr;\n");
    out.push_str("} EndGpuBuffer;\n\n");
    out.push_str("static inline int64_t end_gpu_create_buffer(int64_t size_bytes) {\n");
    out.push_str("    if (size_bytes <= 0) return 0;\n");
    out.push_str("    EndGpuBuffer* buf = (EndGpuBuffer*)calloc(1, sizeof(EndGpuBuffer));\n");
    out.push_str("    buf->size_bytes = size_bytes;\n");
    out.push_str("    buf->ptr = malloc((size_t)size_bytes);\n");
    out.push_str("    return (int64_t)(uintptr_t)buf;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_gpu_dispatch(int32_t x, int32_t y, int32_t z) {\n");
    out.push_str("    return (int64_t)x * (int64_t)y * (int64_t)z;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_gpu_destroy_buffer(int64_t buf_handle) {\n");
    out.push_str("    EndGpuBuffer* buf = (EndGpuBuffer*)(uintptr_t)buf_handle;\n");
    out.push_str("    if (!buf) return;\n");
    out.push_str("    if (buf->ptr) free(buf->ptr);\n");
    out.push_str("    free(buf);\n");
    out.push_str("}\n\n");

    // List & HashMap
    out.push_str("/* End Real In-Memory Dynamic Array (std::collections::List) */\n");
    out.push_str("typedef struct EndList {\n");
    out.push_str("    int64_t length;\n");
    out.push_str("    int64_t capacity;\n");
    out.push_str("    void** items;\n");
    out.push_str("} EndList;\n\n");
    out.push_str("static inline int64_t end_list_create(int64_t cap) {\n");
    out.push_str("    if (cap <= 0) cap = 8;\n");
    out.push_str("    EndList* list = (EndList*)calloc(1, sizeof(EndList));\n");
    out.push_str("    list->length = 0;\n");
    out.push_str("    list->capacity = cap;\n");
    out.push_str("    list->items = (void**)malloc(sizeof(void*) * (size_t)cap);\n");
    out.push_str("    return (int64_t)(uintptr_t)list;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_list_push_str(int64_t l_handle, const char* str) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list) return;\n");
    out.push_str("    if (list->length >= list->capacity) {\n");
    out.push_str("        list->capacity *= 2;\n");
    out.push_str("        list->items = (void**)realloc(list->items, sizeof(void*) * (size_t)list->capacity);\n");
    out.push_str("    }\n");
    out.push_str("    list->items[list->length++] = (void*)strdup(str ? str : \"\");\n");
    out.push_str("}\n\n");
    out.push_str("static inline const char* end_list_get_str(int64_t l_handle, int64_t index) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list || index < 0 || index >= list->length) return \"\";\n");
    out.push_str("    return (const char*)list->items[index];\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_list_push_i64(int64_t l_handle, int64_t val) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list) return;\n");
    out.push_str("    if (list->length >= list->capacity) {\n");
    out.push_str("        list->capacity *= 2;\n");
    out.push_str("        list->items = (void**)realloc(list->items, sizeof(void*) * (size_t)list->capacity);\n");
    out.push_str("    }\n");
    out.push_str("    list->items[list->length++] = (void*)(uintptr_t)val;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_list_get_i64(int64_t l_handle, int64_t index) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list || index < 0 || index >= list->length) return 0;\n");
    out.push_str("    return (int64_t)(uintptr_t)list->items[index];\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_list_len(int64_t l_handle) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    return list ? list->length : 0;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_list_free(int64_t l_handle) {\n");
    out.push_str("    EndList* list = (EndList*)(uintptr_t)l_handle;\n");
    out.push_str("    if (!list) return;\n");
    out.push_str("    if (list->items) free(list->items);\n");
    out.push_str("    free(list);\n");
    out.push_str("}\n\n");
    out.push_str("/* End Real In-Memory Hash Table & Key-Value Database (std::collections::HashMap & std::kv) */\n");
    out.push_str("typedef struct EndMapEntry {\n");
    out.push_str("    char* key;\n");
    out.push_str("    char* val;\n");
    out.push_str("    bool is_occupied;\n");
    out.push_str("} EndMapEntry;\n\n");
    out.push_str("typedef struct EndMap {\n");
    out.push_str("    int64_t count;\n");
    out.push_str("    int64_t capacity;\n");
    out.push_str("    EndMapEntry* entries;\n");
    out.push_str("} EndMap;\n\n");
    out.push_str("static inline uint64_t _end_fnv1a_hash(const char* s) {\n");
    out.push_str("    uint64_t hash = 14695981039346656037ULL;\n");
    out.push_str("    if (!s) return hash;\n");
    out.push_str("    while (*s) {\n");
    out.push_str("        hash ^= (uint64_t)(unsigned char)(*s++);\n");
    out.push_str("        hash *= 1099511628211ULL;\n");
    out.push_str("    }\n");
    out.push_str("    return hash;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_map_create(int64_t initial_cap) {\n");
    out.push_str("    if (initial_cap <= 0) initial_cap = 16;\n");
    out.push_str("    EndMap* map = (EndMap*)calloc(1, sizeof(EndMap));\n");
    out.push_str("    map->count = 0;\n");
    out.push_str("    map->capacity = initial_cap;\n");
    out.push_str("    map->entries = (EndMapEntry*)calloc((size_t)initial_cap, sizeof(EndMapEntry));\n");
    out.push_str("    return (int64_t)(uintptr_t)map;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_map_set_str(int64_t m_handle, const char* key, const char* val);\n");
    out.push_str("static inline void end_map_set_str(int64_t m_handle, const char* key, const char* val) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key) return;\n");
    out.push_str("    if (map->count * 10 >= map->capacity * 7) {\n");
    out.push_str("        int64_t old_cap = map->capacity;\n");
    out.push_str("        EndMapEntry* old_entries = map->entries;\n");
    out.push_str("        map->capacity *= 2;\n");
    out.push_str("        map->entries = (EndMapEntry*)calloc((size_t)map->capacity, sizeof(EndMapEntry));\n");
    out.push_str("        map->count = 0;\n");
    out.push_str("        for (int64_t i = 0; i < old_cap; i++) {\n");
    out.push_str("            if (old_entries[i].is_occupied) {\n");
    out.push_str("                end_map_set_str(m_handle, old_entries[i].key, old_entries[i].val);\n");
    out.push_str("                free(old_entries[i].key);\n");
    out.push_str("                free(old_entries[i].val);\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("        free(old_entries);\n");
    out.push_str("    }\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    while (map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            free(map->entries[h].val);\n");
    out.push_str("            map->entries[h].val = strdup(val ? val : \"\");\n");
    out.push_str("            return;\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("    }\n");
    out.push_str("    map->entries[h].key = strdup(key);\n");
    out.push_str("    map->entries[h].val = strdup(val ? val : \"\");\n");
    out.push_str("    map->entries[h].is_occupied = true;\n");
    out.push_str("    map->count++;\n");
    out.push_str("}\n\n");
    out.push_str("static inline const char* end_map_get_str(int64_t m_handle, const char* key) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key || map->count == 0) return \"\";\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    int64_t examined = 0;\n");
    out.push_str("    while (examined < map->capacity && map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            return map->entries[h].val ? map->entries[h].val : \"\";\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("        examined++;\n");
    out.push_str("    }\n");
    out.push_str("    return \"\";\n");
    out.push_str("}\n\n");
    out.push_str("static inline bool end_map_has(int64_t m_handle, const char* key) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key || map->count == 0) return false;\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    int64_t examined = 0;\n");
    out.push_str("    while (examined < map->capacity && map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            return true;\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("        examined++;\n");
    out.push_str("    }\n");
    out.push_str("    return false;\n");
    out.push_str("}\n\n");
    out.push_str("static inline bool end_map_delete(int64_t m_handle, const char* key) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map || !key || map->count == 0) return false;\n");
    out.push_str("    uint64_t h = _end_fnv1a_hash(key) % (uint64_t)map->capacity;\n");
    out.push_str("    int64_t examined = 0;\n");
    out.push_str("    while (examined < map->capacity && map->entries[h].is_occupied) {\n");
    out.push_str("        if (strcmp(map->entries[h].key, key) == 0) {\n");
    out.push_str("            free(map->entries[h].key);\n");
    out.push_str("            free(map->entries[h].val);\n");
    out.push_str("            map->entries[h].is_occupied = false;\n");
    out.push_str("            map->count--;\n");
    out.push_str("            return true;\n");
    out.push_str("        }\n");
    out.push_str("        h = (h + 1) % (uint64_t)map->capacity;\n");
    out.push_str("        examined++;\n");
    out.push_str("    }\n");
    out.push_str("    return false;\n");
    out.push_str("}\n\n");
    out.push_str("static inline int64_t end_map_len(int64_t m_handle) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    return map ? map->count : 0;\n");
    out.push_str("}\n\n");
    out.push_str("static inline void end_map_free(int64_t m_handle) {\n");
    out.push_str("    EndMap* map = (EndMap*)(uintptr_t)m_handle;\n");
    out.push_str("    if (!map) return;\n");
    out.push_str("    for (int64_t i = 0; i < map->capacity; i++) {\n");
    out.push_str("        if (map->entries[i].is_occupied) {\n");
    out.push_str("            free(map->entries[i].key);\n");
    out.push_str("            free(map->entries[i].val);\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    free(map->entries);\n");
    out.push_str("    free(map);\n");
    out.push_str("}\n\n");
}
